### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by triska** [infradig/trealla#1]
Compiling on OSX 10.11.3, I get:
<pre>
<b>$ make</b>
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o tpl.o tpl.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o history.o history.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o builtins.o builtins.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o library.o library.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o parse.o parse.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o print.o print.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3"' -O3  -Wall -D_GNU_SOURCE   -c -o runtime.o runtime.c
runtime.c:40:2: warning: implicit declaration of function 'clock_gettime' is
      invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, &now);
        ^
<b>runtime.c:40:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &now);</b>
                      ^
1 warning and 1 error generated.
make: *** [<builtin>: runtime.o] Error 1
</pre>

My `cc` version is:

<pre>
<b>$ cc --version</b>
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
</pre>

Could you please have a look? Thank you a lot!

**Comment by infradig** [comment]
According to man 'clock_gettime':

_All implementations shall support a clock_id of CLOCK_REALTIME as defined in <time.h>._

Can you tell me what your system supports. OSX is not familiar to me.

**Comment by infradig** [comment]
Actually, I see I was not including <time.h>.
