### ISSUE TITLE
loading of deep taxonomy test takes quadratic time

### ISSUE THREAD

**Issue by josd** [infradig/trealla#103]
The following 5 files contain rules representing a deep taxonomy test
```
http://eulersharp.sourceforge.net/2009/12dtb/test-pl-10.pl
http://eulersharp.sourceforge.net/2009/12dtb/test-pl-100.pl
http://eulersharp.sourceforge.net/2009/12dtb/test-pl-1000.pl
http://eulersharp.sourceforge.net/2009/12dtb/test-pl-10000.pl
http://eulersharp.sourceforge.net/2009/12dtb/test-pl-100000.pl
```
Using `/usr/bin/time -f sec=%e0 tpl -g halt`  for the above files we get resp.
```
sec=0.010
sec=0.010
sec=0.100
sec=6.160
sec=600.310
```
Using `/usr/bin/time -f sec=%e0 swipl -g halt` we get resp.
```
sec=0.020
sec=0.030
sec=0.070
sec=0.510
sec=4.790
```

**Comment by infradig** [comment]
Yes, this will need addressing soon.

**Comment by infradig** [comment]
There's actually another problem, only the first file seems to actually run
with tpl. Seems an indexing issue.

**Comment by josd** [comment]
Exactly, I was about to say the same:
running `goal` gives resp.
```
true.
false.
false.
false.
false.
```

**Comment by infradig** [comment]
Fixed that. Seems I ignored my own advice in a code comment!

**Comment by josd** [comment]
Very well, now it works and once loaded, the performance to wade through 300K rules is really impressive!
```
$ tpl ~/eyesvn/2009/12dtb/test-pl-100000.pl
Warning: singleton: X, line 300005
Trealla ProLog (c) Infradig 2020, v1.2.108
?- time(goal).
Time elapsed 0.0971 secs
true.
?-
```

**Comment by infradig** [comment]
Great. How does it compare to swipl?

**Comment by josd** [comment]
```
?- time(goal).
% 100,003 inferences, **0.125** CPU in 0.125 seconds (100% CPU, 801918 Lips)
true.
```
so tpl beats swipl :-)

**Comment by infradig** [comment]
Excellent. I am looking into indexing the symbol table for atoms. It should
be fast then for loading as well.

**Comment by josd** [comment]
tpl also beats swipl in terms of memory footprint
```
$ /usr/bin/time -f "sec=%e0 kB=%M cpu=%P" tpl -g goal,halt ~/eyesvn/2009/12dtb/test-pl-100000.pl
Warning: singleton: X, line 300005
Command exited with non-zero status 1
sec=593.510 **kB=123156** cpu=99%
```
versus
```
$ /usr/bin/time -f "sec=%e0 kB=%M cpu=%P" swipl -g goal,halt ~/eyesvn/2009/12dtb/test-pl-100000.pl
Warning: /home/jdroo/eyesvn/2009/12dtb/test-pl-100000.pl:300005:
Warning:    Singleton variables: [X]
sec=4.840 **kB=137148** cpu=99%
```

**Comment by infradig** [comment]
Ok, new symbol table indexing now gives load times comparable to swipl.
Just need to add some cleanup code then it'll be done.

**Comment by josd** [comment]
Perfect!
This is so nice!
