### ISSUE TITLE
samples/fib.pl giving a segmentation fault

### ISSUE THREAD

**Issue by josd** [infradig/trealla#105]
Running samples/fib.pl actually gives a segmentation fault
```
$ tpl -g test2,halt samples/fib.pl
runtime.c:62 alloc_grow: memory pressure reduce 524288000 to 393216001
runtime.c:62 alloc_grow: memory pressure reduce 524288000 to 327680001
...
runtime.c:62 alloc_grow: memory pressure reduce 744401398 to 372200706
Error: uncaught exception... error(resource_error(out_of_slot_space,fib/2),fib/2)
Segmentation fault
```
An alternative implmentation runs fine
```
:- initialization(main).

main :-
    fib(40,F),
    F =:= 165580141,
    write('PASS'),
    nl,
    halt.

fib(A,B) :-
    fib(A,1,1,B).

fib(0,_,A,A).
fib(1,_,A,A).
fib(A,B,C,D) :-
    A > 1,
    E is A-1,
    F is B+C,
    fib(E,C,F,D).
```
and is runs fast
```
$ time tpl --ns fib.pl
PASS

real    0m0.010s
user    0m0.000s
sys     0m0.010s
```
Just as a wish, it would be nice to have bignum support
```
?- fib(91,X).
 X = 7540113804746346429.
?- fib(92,X).
Error: uncaught exception... error(domain_error(integer_overflow,4660046610375530309),+/)
?-
```

**Comment by infradig** [comment]
I don't see this. Running test2 i get the OOM-killer terminating the
process. 8GB system, no swap file.

That's a nice tail-recursive implementation. The original in samples isn't.

**Comment by infradig** [comment]
You can compile with 128-bit integer support. Don't know how high that will
go.

**Comment by infradig** [comment]
It's probably related to cehteh's issue.

**Comment by josd** [comment]
Compiling with `-DUSE_INT128=1` gives
```
Trealla ProLog (c) Infradig 2020, v1.2.109-3-g6ee0-dirty
?- fib(182,X).
 X = 78569350599398894027251472817058687522.
?- fib(183,X).
 X = 127127879743834334146972278486287885163.
?- fib(184,X).
 X = -3465294890923511181.
?-
```
so it is indeed 20 more digits, but there is no overflow detected.

**Comment by infradig** [comment]
Yes, it normally uses 128 bit ints to detect overflow in 64.

**Comment by infradig** [comment]
If there's a need for bignum support i would add it in. In the past I have used OpenSSL's bignums, and when the 128-bit accumulator detected overflow in 64-bit ints automatically converted to bignums, and that worked well and had no efficiency overhead. I would probably use GNU MP (aka GMP) this time as it does rationals as well. I may open a separate issue for this.

**Comment by josd** [comment]
Now the segmentation fault is gone
```
$ tpl -g test2,halt samples/fib.pl
runtime.c:62 alloc_grow: memory pressure reduce 524288000 to 393216001
Killed
```
Thanks!
