### ISSUE TITLE
Bignum support

### ISSUE THREAD

**Issue by infradig** [infradig/trealla#107]
Use GNU MP (aka GMP) for bignums. When 64-bit int operations overflow automatically promote to a bignum.

**Comment by josd** [comment]
That is an excellent idea and then
```
:- initialization(main).

main :-
    fib(365,F),
    F =:= 13803567055491817972029187936825113333650564850089197542855968899086435571688,
    write('PASS'),
    nl,
    halt.

fib(A,B) :-
    fib(A,1,1,B).

fib(0,_,A,A).
fib(1,_,A,A).
fib(A,B,C,D) :-
    A > 1,
    E is A-1,
    F is B+C,
    fib(E,C,F,D).
```
will PASS with tpl just as it does do with
```
$ swipl fib.pl
PASS
```
and with
```
$ scryer-prolog fib.pl
PASS
```

**Comment by UWN** [comment]
Just an observation: with bounded arithmetic, conforming integer overflow detection can become quite complex. Some systems switched to unbounded arithmetic just because of this. There, you have more liberty about the precise point when overflow happens. That is, both the overflow to switch between small integers and gmp-ed (which you may change as you please), as well as the programmer visible overflow (resource error) which happens much rarer and which may happen "at any stage of execution" (7.12.2 h).

**Comment by infradig** [comment]
Current Trealla use 64-bit ints but does 128-bit operations (when
supported, x86 only?) and detects overflow that way. I will definitely go
to bignums (GMP) when possible.

**Comment by infradig** [comment]
I read, but haven't verified, that GMP aborts on an alloc failure, making it unsuitable to use. There are alternatives such as imath.

**Comment by UWN** [comment]
[Related](https://stackoverflow.com/q/13328409/772868), not sure if there happened anything new in the meantime.

**Comment by infradig** [comment]
Yes, GMP is mess in thsi regard. They just don't see recovery as an issue.
Currently Trealla checks every arithmetic operation for overflow (where
possible) so checking for failure is no big deal.

To be honest i'm a bit cold on the idea of bignums for now.

**Comment by UWN** [comment]
Let us see if there is any update on GMP, just put a bounty out for it.

Systems without bigunums are more brittle to use and test, apart from their not being able to be used in some actual use cases like cryptography and the like.

(What I wonder is that  AFAIK Mathematica uses GMP (under some specific license) and so far I have not observed any of these issues there, though I am not a very versed user of it)

**Comment by infradig** [comment]
Implementing bigints & bigrats using imath package. In devel branch...

**Comment by josd** [comment]
Thanks for the implementation and I was testing https://github.com/josd/eye/blob/master/reasoning/trealla/fibonacci.pl
using your master branch v1.8.77-159-g7f0f1f
```
$ tpl -g test fibonacci.pl | tee /tmp/out.n3
[] :trealla-result "fibonacci(0,0)".
[] :trealla-result "fibonacci(1,1)".
[] :trealla-result "fibonacci(6,8)".
[] :trealla-result "fibonacci(91,4660046610375530309)".
[] :trealla-result "fibonacci(283,62232491515607091882574410635924603070626544377175485625797)".
[] :trealla-result "fibonacci(3674,295872959797101479478634366815157108100573212705250690577871041398423606408217262643449728342664061812585639168722421830407677671667740585806703531229882783069925750619720511808616484846128237251921414441458265138672827487722512845223115526738192067144721087756159352711138340620702266509343657403678256247195010013499661223527119909308682062873140767135468966093474944529418214755911968500799987099146489838560114063096775586903976827512299123202488315139397181279903459556726060805948910609527571241968534269554079076649680403030083743420820438603816095671532163428933363322524736324029745871445486444623006627119156710782085648303485296149604974010598940800770684835758031137479033374229914629583184427269638360355586190323578625395157899987377625662075558684705457)".
```
which looks fine except that the result /tmp/out.n3 is contains a null character
at position 0x104

```
$ hd /tmp/out.n3
00000000  5b 5d 20 3a 74 72 65 61  6c 6c 61 2d 72 65 73 75  |[] :trealla-resu|
00000010  6c 74 20 22 66 69 62 6f  6e 61 63 63 69 28 30 2c  |lt "fibonacci(0,|
00000020  30 29 22 2e 0a 5b 5d 20  3a 74 72 65 61 6c 6c 61  |0)"..[] :trealla|
00000030  2d 72 65 73 75 6c 74 20  22 66 69 62 6f 6e 61 63  |-result "fibonac|
00000040  63 69 28 31 2c 31 29 22  2e 0a 5b 5d 20 3a 74 72  |ci(1,1)"..[] :tr|
00000050  65 61 6c 6c 61 2d 72 65  73 75 6c 74 20 22 66 69  |ealla-result "fi|
00000060  62 6f 6e 61 63 63 69 28  36 2c 38 29 22 2e 0a 5b  |bonacci(6,8)"..[|
00000070  5d 20 3a 74 72 65 61 6c  6c 61 2d 72 65 73 75 6c  |] :trealla-resul|
00000080  74 20 22 66 69 62 6f 6e  61 63 63 69 28 39 31 2c  |t "fibonacci(91,|
00000090  34 36 36 30 30 34 36 36  31 30 33 37 35 35 33 30  |4660046610375530|
000000a0  33 30 39 29 22 2e 0a 5b  5d 20 3a 74 72 65 61 6c  |309)"..[] :treal|
000000b0  6c 61 2d 72 65 73 75 6c  74 20 22 66 69 62 6f 6e  |la-result "fibon|
000000c0  61 63 63 69 28 32 38 33  2c 36 32 32 33 32 34 39  |acci(283,6223249|
000000d0  31 35 31 35 36 30 37 30  39 31 38 38 32 35 37 34  |1515607091882574|
000000e0  34 31 30 36 33 35 39 32  34 36 30 33 30 37 30 36  |4106359246030706|
000000f0  32 36 35 34 34 33 37 37  31 37 35 34 38 35 36 32  |2654437717548562|
00000100  35 37 39 37 00 29 22 2e  0a 5b 5d 20 3a 74 72 65  |5797.)"..[] :tre|
...
```

**Comment by infradig** [comment]
Yes, I see it. This might explain a bug I have running Logtalk
tests/prolog/unbounded which has been driving me nuts for 2 days!

**Comment by infradig** [comment]
Champ, that was what I needed! Almost there...

% running tests from object tests
% file: /home/andrew/lgt3git/tests/prolog/unbounded/tests.lgt
%
% lgt_unbounded_unary_plus_01: success (in 8.392333984375e-05 seconds)
% lgt_unbounded_unary_minus_01: success (in 3.0040740966796875e-05 seconds)
% lgt_unbounded_addition_01: success (in 2.7894973754882812e-05 seconds)
% lgt_unbounded_addition_02: success (in 2.9087066650390625e-05 seconds)
% lgt_unbounded_addition_03: success (in 2.6941299438476562e-05 seconds)
% lgt_unbounded_addition_04: success (in 5.91278076171875e-05 seconds)
% lgt_unbounded_subtraction_01: success (in 3.1948089599609375e-05 seconds)
% lgt_unbounded_subtraction_02: success (in 2.8848648071289062e-05 seconds)
% lgt_unbounded_subtraction_03: success (in 2.7179718017578125e-05 seconds)
% lgt_unbounded_subtraction_04: success (in 2.9087066650390625e-05 seconds)
% lgt_unbounded_subtraction_05: success (in 5.7935714721679688e-05 seconds)
% lgt_unbounded_multiplication_01: success (in 2.9802322387695312e-05
seconds)
% lgt_unbounded_multiplication_02: success (in 2.86102294921875e-05 seconds)
% lgt_unbounded_multiplication_03: success (in 2.765655517578125e-05
seconds)
!     lgt_unbounded_multiplication_04: failure (in 8.487701416015625e-05
seconds)
!       test assertion failed: '=~='(1.342e+34,1.656790108545679e+63)
!       in file /home/andrew/lgt3git/tests/prolog/unbounded/tests.lgt
between lines 88-91
% lgt_unbounded_integer_division_01: success (in 3.0994415283203125e-05
seconds)
% lgt_unbounded_integer_division_02: success (in 2.8133392333984375e-05
seconds)
% lgt_unbounded_integer_division_03: success (in 3.2901763916015625e-05
seconds)
% lgt_unbounded_float_division_01: success (in 8.678436279296875e-05
seconds)
% lgt_unbounded_float_division_02: success (in 7.62939453125e-05 seconds)
% lgt_unbounded_float_division_03: success (in 9.1791152954101562e-05
seconds)
!     lgt_unbounded_float_division_04: failure (in 7.2956085205078125e-05
seconds)
!       test goal throws an error but should have succeeded:
error(type_error(evaluable,370370367037037036703703703670/0),(/)/2)
!       in file /home/andrew/lgt3git/tests/prolog/unbounded/tests.lgt
between lines 113-116
% lgt_unbounded_div_01: success (in 3.3855438232421875e-05 seconds)
% lgt_unbounded_div_02: success (in 2.7894973754882812e-05 seconds)
% lgt_unbounded_div_03: success (in 3.4093856811523438e-05 seconds)
% lgt_unbounded_rem_01: success (in 2.8848648071289062e-05 seconds)
% lgt_unbounded_rem_02: success (in 2.7894973754882812e-05 seconds)
% lgt_unbounded_rem_03: success (in 3.24249267578125e-05 seconds)

**Comment by josd** [comment]
Now with v1.8.77-171-gf4d4af our test result https://github.com/josd/eye/blob/master/reasoning/trealla/result.n3 is no longer a binary file ;-)
Thank you very much!

**Comment by infradig** [comment]
This is now in master. At the price of losing rationals.

**Comment by infradig** [comment]
I'm reopening this, as there is currently no bignum support for and/or/xor functions.

**Comment by josd** [comment]
The latest version gives
```
$ tpl
Trealla Prolog (c) Infradig 2020, v1.9.5
?- X is 33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333.
tpl: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```
whereas a slightly smaller number is fine
```
$ tpl
Trealla Prolog (c) Infradig 2020, v1.9.5
?- X is 33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333.
```

**Comment by infradig** [comment]
Fixed!

**Comment by josd** [comment]
Perfect!
```
$ tpl
Trealla Prolog (c) Infradig 2020, v1.9.6
?- X is 33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333+1.
X = 33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333334.
```
