### ISSUE TITLE
Top level: Cannot enter query as intended

### ISSUE THREAD

**Issue by triska** [infradig/trealla#11]
Using the current `devel` branch, I would like to post the following query:

<pre>
?- Ls = "abc", Ls = [a|_].
</pre>

However, I apparently cannot enter this query as intended: I get as far as:

<pre>
?- Ls = "abc", Ls = [a|_
</pre>

and when I then enter the closing `]`,  the query changes into:

<pre>
?- Ls = "abc", Ls = ]a|_
</pre>

This seems to be a problem with showing matching brackets.

I encounter this problem logging into a Debian machine via `ssh`, from OSX.

**Comment by infradig** [comment]
I'm currently massacring the devel branch

**Comment by triska** [comment]
I just tried it on `master` and get the same problem there too!

**Comment by triska** [comment]
For instance, when I enter (on `master`):

<pre>
?- Ls = [a]
</pre>

I unexpectedly get (when writing the final `]`):

<pre>
?- Ls = ]a
</pre>

**Comment by infradig** [comment]
I expect it's a term control issue over SSH. Local xterm seems fine. I'll
look into it

**Comment by infradig** [comment]
I tried SSH into my PI and it works ok.
Maybe need a disabling option.

**Comment by triska** [comment]
I now have this problem also on a local Debian installation!

Please let me know if there is anything I can do to help trace this down and correct it.

**Comment by infradig** [comment]
I have not been able to encounter this, using both Gnome & KDE on a variety of machines. Both SSH, Xterm and Virtualbox, virtual consoles seem ok.

When you enter the 'env' command what does thre TERM variable have?

**Comment by infradig** [comment]
Ok, I found this... https://stackoverflow.com/questions/28986776/ansi-escape-sequence-save-restore-cursor-position-support and there may still be problem on Macs?

It seems i should try using the DEC cursor save/restore instead of ANSI ones.

**Comment by triska** [comment]
Unfortunately, the issue still persists on Debian.

Due to #15, I currently cannot compile on OSX.

**Comment by infradig** [comment]
I did an install of Debian in Virtualbox and have no problems with it. At a
loss what to do about it.

**Comment by triska** [comment]
Would it be possible to use `readline` or `editline` as a portable implementation?

**Comment by infradig** [comment]
Should be, just not familiar with using it. Can look.

**Comment by infradig** [comment]
I can just disable the flash-check for now.

**Comment by infradig** [comment]
Ok, have disabled that feature for now. I will look at using readline, I
had never heard of editline before... looks more complex to approach.

**Comment by infradig** [comment]
And now I have switched to using readline. Hopefully this will sort things out. 

It has everything it had before except flash-check of parens/brackets/braces.  Since gprolog has this feature it must be doable.

**Comment by triska** [comment]
This works brilliantly now, thank you a lot!

Another thing that does not work any more is that pressing `Ctrl + d` now no longer halts the system. It would be great to be able to exit again in this way.

Since the core issue is now resolved, I am closing this issue, thank you a again!
