### ISSUE TITLE
Plans for Makefile improvement

### ISSUE THREAD

**Issue by cehteh** [infradig/trealla#118]
I will start a new branch where will improve the Makefile soon. Since that branch will *only*
track the Makefile it will stay parallel for some time I am not in a hurry to finish it.

Here are some proposals about the plan.

- Completely non recursive (never call make from the Makefile)
- Automatic dependency tracking.
- Fast/exact parallel builds.
- may have supplementary Makefiles which are included (makefiles/ subdir?).
- Configuration will not be a target, extra options/flags are passed as variable assignments.
  `make FLAVOR=debug OPTIONS=LTO=25 CC=clang CFLAGS= test` actually it will remember the
  FLAVOR/OPTIONS/... one passed, thus its not necessary to add them on subsequent make
  invocations. That is only needed to switch the build flavor.

  I am thinking for 3 Flavors: alpha, beta, release

- build in build dirs. Will become something like 'build_$flavor_$options/'

- It can and will drive a lot project related tasks (testsuite, benchmark, documentation,
  faultinject)

- ... more to come

Caveats:
- It will use gnu make (and few posix feature, sh, not bash, awk. ..)
- I can test and maintain that on Linux. For other platforms I need some help.

**Comment by infradig** [comment]
Sounds good.

Maybe source files (except tpl.c) should go to 'src' subdir to
facilitate build as a library or other targets.

I don't want to go to git sub-repos though, I hated that the one time I
used them.

**Comment by cehteh** [comment]
Welcome to the club, I have to met anyone who likes git-submodules. Still I wanted to point out the possibility. Sometimes they make sense despite all the horrors involved (not here).
