### ISSUE TITLE
Documentation system, pipadoc extractor

### ISSUE THREAD

**Issue by cehteh** [infradig/trealla#119]
Sooner or later trealla will need some documentation. About code internals/apis as well as
user and prolog library documentation.

Following some strong opinions...

I presume that some text markup language is preferred. My preferences would be asciidoc over
markdown, because being docbook based it has a much better semantic foundation and it has the
better toolchain as well (generating nice PDF's and HTML's).

For my own projects I created a documentation extractor https://github.com/cehteh/pipadoc I
like to add this to trealla (basically put it in a doc/ subdir, either directly or as git
subproject).

It helps to extract annotations and documentation from the source as well as having plaintext
documentation files and bring them into order for a complete document.

I would add a dependency on lua for documentation generation, otherwise its standalone.

Driven by 'make' targets it can then generate complete documentation (pdf, html, README,
manpages, ...)

**Comment by infradig** [comment]
I'll look at pipadoc.

**Comment by cehteh** [comment]
hint: pipadoc documents itself, mostly in a single file
  https://github.com/cehteh/pipadoc/blob/devel/pipadoc.lua

which eventually creates documentation:
  https://git.pipapo.org/?p=pipadoc;a=blob_plain;f=pipadoc.html

**Comment by infradig** [comment]
Thanks. I will look at it soon. I'm trying to debug Trealla running
Logtalk, and scanning 300K lines of Prolog trace is doing my head in.
