### ISSUE TITLE
Top level: Alternatives are sometimes not shown

### ISSUE THREAD

**Issue by triska** [infradig/trealla#12]
For instance, when I query:

<pre>
?- X = a ; Y = b.
</pre>

I get:

<pre>
X = a
</pre>

However, on backtracking, I expect to be shown the alternative `Y = b`. This means that if alternatives remain, the top level should provide a way to inspect them, for example by pressing `SPACE`.

Likewise for instance:

<pre>
?- member(E, "abc").
</pre>

which currently yields only `E = a`.

Ideally, alternatives are reported in such a way that the entire answer is a Prolog goal that is equivalent to the original query, and with a nice indentation. For instance, it would be nice to report them as:

<pre>
<b>?- member(E, "abc").</b>
   E = a
;  E = b
;  E = c
;  false.
</pre>

**Comment by infradig** [comment]
The top-level needs working on.

**Comment by pmoura** [comment]
Trying the new support for top-level alternatives as of v1.5.1-4-gbac53. I assume this is still work in progress? When the top-level stops for an alternative, only `;` seems to be accepted. Typing return (or enter) or the spacebar is not accepted as input to commit to the current solution or to ask for an alternative solution. E.g.

```text
$ tpl
Trealla ProLog (c) Infradig 2020, v1.5.1-4-gbac53
?- (X=1; X=2; X=3).
X = 1.
```

**Comment by infradig** [comment]
Yes, currently ';' or 'a' for abort or 'e' for end.

**Comment by infradig** [comment]
I will be working on it more.

**Comment by triska** [comment]
The better indentation I mentioned is not yet implemented. In particular, I get:

<pre>
<b>?- member(X, "abc").</b>
X = a ;
X = b ;
X = c ;
false.
</pre>

It is bad practice to write `;` at the end of a line, since it is so easily mistaken for `,` (which very often occurs at the end of a line).

So, a much better and more conventional indentation for the residual program is:

<pre>
<b>?- member(X, "abc").</b>
   X = a
;  X = b
;  X = c
;  false.
</pre>

This is what Scryer Prolog does for example. Are you interested in adding it? It would make toplevel output much more readable and conforming to all recommended conventions for Prolog programs.

**Comment by infradig** [comment]
Sure.

**Comment by infradig** [comment]
Done. I actually like it better as well.

**Comment by josd** [comment]
Perfect and it indeed feels better
```
$ tpl
Trealla Prolog (c) Infradig 2020, v1.7.19
?- member(X, "Andrew").
X = 'A'
; X = n
; X = d
; X = r
; X = e
; X = w
; false.
?-
```
