### ISSUE TITLE
calling tpl from /usr/local/bin/tpl gives segmentation fault

### ISSUE THREAD

**Issue by josd** [infradig/trealla#125]
Till yesterday calling tpl worked fine but now it gives
```
$ tpl
Segmentation fault (core dumped)
```
The following still works fine
```
$ /usr/local/bin/tpl
Trealla ProLog (c) Infradig 2020, v1.2.122-27-g0e33
?-
```
That location is linked as follows
```
$ ls -l /usr/local/bin/tpl
lrwxrwxrwx 1 root root 39 Nov 15 21:04 /usr/local/bin/tpl -> /home/jdroo/github.com/josd/trealla/tpl
```

**Comment by infradig** [comment]
It tries to set the library path location of the executable. To do with I
guess, I'll have a look.

**Comment by pmoura** [comment]
I'm seeing the same issue if I use the `tplgt` script from outside the `tpl` build directory. The crash is immediate. I wonder if a similar bug to the one you just fixed exists in the implementation of the `tpl -f` command-line option, which is used by the script.

**Comment by josd** [comment]
Now it works fine again, also for the tests at https://github.com/josd/eye/tree/master/retina
```
Using tpl -g halt
Running ./4colors.pl ...
Running ./complex.pl ...
Running ./curly.pl ...
Running ./dtb.pl ...
Running ./ea.pl ...
Running ./ebl.pl ...
Running ./equation.pl ...
Running ./equation4.pl ...
Running ./fft.pl ...
Running ./fib.pl ...
Running ./gcc.pl ...
Running ./graph.pl ...
Running ./hanoi.pl ...
Running ./lee.pl ...
Running ./likes.pl ...
Running ./pi.pl ...
Running ./polygon.pl ...
Running ./sieve.pl ...
Running ./tak.pl ...
Running ./turing.pl ...
Running ./unsat.pl ...

============
TEST SUMMARY
============
Failed: 0
Succeeded: 21
```

Thanks and have a nice evening!

**Comment by infradig** [comment]
Thanks for that. Good to have a win.

**Comment by infradig** [comment]
I don't know. I assume you mean -l not -f, though unknown options are
ignored and -l is optional.

**Comment by pmoura** [comment]
I mean:

```text
  -f file		- consult file
```

**Comment by infradig** [comment]
Since you have to build with NOLDLIBS=1 it means you need access to the
library directory to load library files (eg dcgs.pl, format.pl etc). You
will have to define the env TPL_LIBRARY_PATH or provide '--library path'.
You are probably doing that. Getting access to the current executable file
location is surprisingly difficult.
