### ISSUE TITLE
Add conditional compilation if/elif/endif directives

### ISSUE THREAD

**Issue by infradig** [infradig/trealla#127]
> Also Trealla doesn't have if/elif/endif directives, yet.

Those are handy. But note that Logtalk provides its own portable implementation of the conditional-compilation directives. Thus, it doesn't require that the backend Prolog system supports them.

P.S. Conditional-compilation directives were part of the last ISO Prolog Core standard revision proposal I worked on as WG17 editor with great cooperation from Prolog implementers back in 2009.

_Originally posted by @pmoura in https://github.com/infradig/trealla/issues/99#issuecomment-732887335_

**Comment by triska** [comment]
From a standardization perspective, this is not a good idea: Conditional compilation constructs tend to cement the differences between Prolog systems instead of increasing their mutual compatibility.

Programmers will use these constructs to work around incompatibilities instead of putting pressure on implementors to work towards common functionality.

This is why there are no provisions in the ISO standard to detect which Prolog system is currently running. There is no concept of "dialect" in the standard, though there are different levels of conformity to the standard.

**Comment by pmoura** [comment]
The current official and de facto standards only cover a small part of the functionality that programmers expect from a Prolog implementation. There will always be functionality that, although provided by different systems, it's provide in different forms. As an example, different Prolog systems have different sets of predicates to access the operating-system and the file-system. Thus, writing portable code often requires knowing in which Prolog system its running and act accordingly. Conditional-compilation directives, the `dialect` and `version_data` flags, are part of the tools that can be used to cope with the differences. But even within the scope of a single Prolog system, these features are useful. Prolog systems, evolve, gain new functionality, and testing for a version (that e.g. includes new functionality or a given set of bug fixes) is common.

Btw, these (and other) features were approved **unanimously** in the 2009 WG17 at Pasadena during ICLP. This was a WG17 meeting with a record number of participants. These features were also already implemented by then by most Prolog systems. These (and other) features were dropped from the Core revision proposal at the 2010 WG17 where the **3** participants there (IIRC) had a change of heart, decided they knew best than everyone else in the community, and moved to undo the work being done.

As far as the "putting pressure on implementors to work towards common functionality" goes, the history of Prolog standardization and standards adoption by implementers shows that pressure to be of little consequence. I did have good results and good cooperation from most Prolog implementers in getting necessary core features implemented that allows Logtalk to be written in portable code and run on most systems. But actual standardization takes a much bigger effort and willingness from Prolog implementers that often either see little value or that don't have the resources to participate in such time-consuming tasks up to completion (meaning, published standards).

When I started working with WG17 back in 2006, the DCGs standardization proposal was a two page document, mainly a letter of intent. When I resigned as WG17 editor in 2009, I left (among other proposals) a draft DCGs standardization proposal with substantial contents and work done by the community, including a reference implementation and a test set. It's 2020 and we still don't have a published ISO Prolog DCGs standard. Where's that "pressure" that you talk about? Attribute variables? Constraints? Never seen a standardization proposal. Most people in the community recognize their importance. But I still cannot use constraints in my code unless I restrict myself to a very small set of systems, often with cardinality 1. How's the "pressure" working here?

Meanwhile, me and a few other crazy people insist on writing portable code for non-trivial tasks. Thanks to the existence of de facto standards, we can actually do our work. Today.

**Comment by infradig** [comment]
Happy to drop it as there is nothing to be gained for Trealla, and Logtalk
doesn't need it.

**Comment by infradig** [comment]
Good point too.

**Comment by infradig** [comment]
Yet I notice now that clpz.pl uses them in at least one place, i'll have to do something.

**Comment by triska** [comment]
The latest version of `clpz.pl` is the one that ships with Scryer Prolog:

https://github.com/mthom/scryer-prolog/blob/master/src/lib/clpz.pl

It does not use conditional compilation, for the reasons I stated above.

**Comment by infradig** [comment]
Cool, less work!

**Comment by infradig** [comment]
Lot's of changes. Why sometimes between:between(...) and other times
clpz:between(..) and sometimes just between(...)?

**Comment by triska** [comment]
May I suggest starting with `clpb.pl`?

https://github.com/mthom/scryer-prolog/blob/master/src/lib/clpb.pl

This is easier to port since the code is much shorter, and it serves as a solid foundation for porting `clpz.pl`.

As to `between/3`: In the program where the expanded code is placed, `library(between)` may not be imported. But `clpz.pl` does import it, and therefore `between/3` is available there. `clpz:between(...)` should actually be changed to `between:between(...)` too.
