### ISSUE TITLE
Please add support for ~/.tplrc initialization file

### ISSUE THREAD

**Issue by triska** [infradig/trealla#129]
It would be nice for Trealla to automatically consult the file **`~/.tplrc`** (or similar) when started.

This feature could also be used by programmers who are interested in running different Prolog systems to add compatibility definitions. These definitions are automatically available in every application we run and can also be easily shared between interested programmers, and thus prevent the necessary conditional checks in each and every Prolog application that we want to run in several systems. In this way, this feature could also reduce the demand for conditional compilation (#127).

**Comment by infradig** [comment]
Will do.

**Comment by triska** [comment]
Perfect, thank you a lot!
