### ISSUE TITLE
DCG reference implementation

### ISSUE THREAD

**Issue by triska** [infradig/trealla#13]
Ulrich Neumerkel's [ISO Prolog page](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/) contains useful references for DCGs, including the latest draft ([dcgsdraft-2019-06-03.pdf](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dcgs/dcgsdraft-2019-06-03.pdf)), and a *reference&nbsp;implementation*:

**https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dcgs/dcgs_exp.pl**

Conceptually, if a term with principal functor `(-->)/2` is encountered when preparing Prolog text for execution, it should be expanded by invoking `dcg_rule/2`, and the expanded code should be prepared for execution.

I hope this is useful to implement DCGs, and thus to provide a key attraction of Prolog: Efficient and convenient analysis of large amounts of text!

**Comment by infradig** [comment]
There already is some DCG support, though not dcg_rule/2. I don't know why
there is no mention in the readme.

**Comment by infradig** [comment]
The reference implementation seems to run ok, at least with the few grammar rules I have thrown at it.

~/trealla >>> ./tpl samples/dcgs_exp.pl
Trealla ProLog (c) Infradig 2020, v1.2.33-4-g35e2
?- dcg_rule((as --> [a], as),R).
R = as(_7,_8) :- _7=[a|_32],as(_32,_8).
true
?- halt.

**Comment by triska** [comment]
Nice! This can be useful if you want to use more of the implementation to Prolog (which would be good as a useful built-in testing mechanism), and also to compare different implementation approaches!

**Comment by infradig** [comment]
Thanks for this tip. I have switched to using this implementation. Everything works fine except tests/tests/test062.pl which I notice relies on:

    :- set_prolog_flag(double_quotes, codes).

So I suspect this does not work well with it. If it's not something easily fixable I will drop that test.

**Comment by triska** [comment]
The flag only affects reading `"..."` terms (which denote either lists of characters or of integers depending on the flag), and writing lists of characters (which cannot be written as `"..."` and need instead to be written using list notation if `double_quotes` is set to `codes`).

`dcgs.pl` does not contain any occurrence of a term in double quotes, and so is in itself not affected by the flag in any way.

Also, the `double_quotes` flag seems to be correctly handled in DCGs. For example, with:

<pre>
:- set_prolog_flag(double_quotes, codes).

a --> "a".
</pre>

I get, as expected:

<pre>
<b>?- phrase(a, Ls).</b>
 Ls = [97].
</pre>

Therefore, I suspect that the issue is due to some other phenomenon that may occur in this specific case.

That being said, once this issue is resolved, I am very much in favour of changing `test062.pl` to use the recommended value `chars` for `double_quotes` because it makes the code much easier to work with, to trace etc. For example, using `chars`, we can simply specify the characters directly in `re_metachar/1`:

<pre>
...
re_metachar(*).
re_metachar(+).
re_metachar(.).
...
</pre>
