### ISSUE TITLE
Cylce check redesign

### ISSUE THREAD

**Issue by cehteh** [infradig/trealla#134]
I'd like to rework the cycle_error cyclic term check and want to ask for opinions first:

1. Don't store the state in `query.cycle_error` but make it return based. I started the work on
   that already in #133. Currently the functions returning pointers just return NULL whenever
   there is *any* error (cycle or allocation) thus the information about the cause gets lost. I'll add another
   sentinel to return a cycle error from that.

2. The point I am not sure about yet: currently there is a `if (depth >= 64000) {` to
   determine a cycle just by depth. This is rarely triggered but if it
   a) comes with a cost each cycle iterates til that limit, which call function recursively.
   b) may be false-positive if there is a legitimate deep nested term with more than 64k nodes
   w/o cycle.

   The plan how to fix is would be a rather dumb graph-coloring way:
    1. Have a global `uint32_t g_counter`.
       This counter gets incremented once at the start of each cycle check. That is the
       'current' color.
    2. For compound terms/lists use one of the unused fields in the cell as color marker.
       `if (cell->color != g_color) {cell->color = g_color;} else { return /*
       cycle_error!*/;}`
       That should reliably detect cycles with a extremely low chance of failure (counter
       overflow, then visit a cell that wasn't cycle checked for exactly 2^32 times before).

    Initially I thought this may have more costs, but since it'll use a unused field in the
    cells it won't even cost extra memory. Slight drawback will be that iterations are writing
    to memory, i'll see how much that costs, prolly negligible.

**Comment by infradig** [comment]
I want to hold off doing a proper cyclic error check, for now.
