### ISSUE TITLE
put_atts/2 and get_atts/2 should reside in modules that contain attribute/1 declarations

### ISSUE THREAD

**Issue by triska** [infradig/trealla#14]
Currently, the README mentions two predicates:

<pre>
atts:put_atts/2
atts:get_atts/2
</pre>

In the SICStus API for attributed variables, whose emulation I recommend for compatibility and flexibility, these predicates reside in each module in which attributes are defined. So, they cannot be made available in a single module called `atts`, but should be made available automatically in modules that define attributes with the `attribute/1` declaration.

In this way, different constraints solvers can interact by reasoning about attributes from other modules. For instance, CLP(ℤ) could be made to take CLP(B) constraints into account by invoking `clpb:get_atts/2`.

**Comment by infradig** [comment]
Noted. These are not in anyway functional yet.
