### ISSUE TITLE
directory_files/2 predicates

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#144]
Please consider adding a `directory_files/2` predicate where the first argument is as directory path (relative or absolute) and the second argument is unified with a list of relative paths (to the directory in the first argument) for the directory contents (both files and directories).

**Comment by triska** [comment]
Ideally, using the idea from #128 to represent files!

**Comment by pmoura** [comment]
Thanks for adding this predicate. I update the Logtalk `os` library to use it. Only a single test for this library now fails (an issue with the `rename_file/2` predicate; I will report it in a separate issue).

**Comment by pmoura** [comment]
P.S. Pushed an update to the `logtalk3` repo to account for this new predicate.

**Comment by infradig** [comment]
In logtalk3/adapters/trealla.pl $lgt_expand_path/2 (and others) would need
to be changed. Currently it assumes a chars list as output from
absolute_file_name/3.

**Comment by triska** [comment]
Personally, I regard a chars list as the ideal representation for file names. I regard #128 as a compromise so that people who want to use atoms can still use atoms.

If that compromise is now no longer needed or desired, then all the better, if list of characters are used now exclusively.

**Comment by infradig** [comment]
Seems to be working fine as a chars list for everyone, so unless @pmoura
wants extra work, i'll leave it.

 I did it both ways however for directory_files/2.

**Comment by pmoura** [comment]
> In logtalk3/adapters/trealla.pl $lgt_expand_path/2 (and others) would need to be changed. Currently it assumes a chars list as output from absolute_file_name/3.

The issue with that Logtalk internal predicate is that Trealla's `absolute_file_name/3` predicate accepts an atom as first argument but returns a list of characters for the second argument. This is one of the cases where it's **possible** (*) and **desirable** to have the output argument type be the same as the input argument type. If you're willing to do that, that will arguably render the `absolute_file_name/3` predicate **consistent** and I will happily update the adapter file.

(*) As we know this is not possible for the `working_directory/2` predicate.

**Comment by pmoura** [comment]
> Personally, I regard a chars list as the ideal representation for file names.

There is no **unqualified** "ideal representation for file names". Char lists may be ideal for **some** cases but definitely not for all. A notorious case is a reflection API where file paths are saved and make available for developer tools. Here, file paths are **not** transient text and thus atoms are the ideal representation. Want another example?  Compiler and linters text messages. Again, no transient text. To reuse a favorite argument of yours, if anyone needs a char list instead, it's just an `atom_chars/2` goal away.

Having written and maintaining a portable operating-system library, working with most Prolog systems, having written portable developer tools working with all those systems, several of them making use of the operating-system library and thus of file paths, the number of times I wished for a char list representation is small. Some goes for my industry work whenever file paths are used. You and other may have naturally a different experience in different usage scenarios. But, again, that's no argument for unqualified "ideal representation", being it atoms or char lists.

Most Prolog systems use an atom representation for file paths (making this representation a de facto standard). In my experience, this is a good thing: atoms are more portable, more memory efficient than a list, and several common operations on file paths can be easily performed without first converting file paths into a char lists. Are atoms not ideal for transient text? Of course. But transient lists are no better. That's why garbage collectors, including atom garbage collectors, exist.

**Comment by pmoura** [comment]
@infradig I see that you pushed a commit for the `absolute_file_name/2-3` predicates to mirror input type. That's a good thing. But there seems to uncovered an issue similar to the one you fixed for the `size_file/2` predicate: requiring the output argument to be unbound. But a call such as `absolute_file_name(Path, Path)` is a common idiom to verify that `Path` is (already) an absolute path. I can workaround this issue, of course, but the facto standard here is for the computed expanded path to be unified with the output argument. Let me know if you agree and can make that change and then I will push update Logtalk support.

**Comment by infradig** [comment]
I'll have a look at it...

**Comment by infradig** [comment]
Ok, that seems to work now with $lgt_expand_path changed to remove
atom-chars call.

**Comment by pmoura** [comment]
Pushed updated Trealla Prolog support for version 1.4.7 to the `logtalk3` repo.
