### ISSUE TITLE
rename_file/2 predicate fails for a non-existing file

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#147]
E.g.

```text
?- rename_file(non_existing_file, foo).
false.
```

It would be preferable to throw a `error(existence_error(file,non_existing_file), rename_file/2)` error in this case.

**Comment by pmoura** [comment]
All tests at `logtalk3/library/os/` now pass 👍 This is a key library, used by several of the developer tools.

**Comment by infradig** [comment]
Excellent.
