### ISSUE TITLE
OSX: Compilation problem

### ISSUE THREAD

**Issue by triska** [infradig/trealla#15]
With OSX 10.14.2, I get:

<pre>
<b>$ make -f OSXmakefile  nossl</b>
/Applications/Xcode.app/Contents/Developer/usr/bin/make 'OPT= -DUSE_OPENSSL=0' NOSSL=1
ld -r -b binary -o lists.o library/lists.pro
ld: warning: option -b is obsolete and being ignored
ld: file not found: binary
make[1]: *** [lists.o] Error 1
make: *** [nossl] Error 2
</pre>

**Comment by infradig** [comment]
Problem with '-f filename' not being passed down.

**Comment by infradig** [comment]
Can you tell me what 'uname -s' show on OSX, I assume 'Darwin'. I will try and fix GNUmakefile to detect that so mo '-f makefile' needed.

**Comment by triska** [comment]
I get:

<pre>
<b>$ uname -s</b>
Darwin
</pre>

When I specify `GNUmakefile`, I get:

<pre>
<b>$ make -f GNUmakefile nossl</b>
/Applications/Xcode.app/Contents/Developer/usr/bin/make 'OPT= -DUSE_OPENSSL=0' NOSSL=1
ld  -r -b binary -o lists.o library/lists.pro
ld: warning: option -b is obsolete and being ignored
ld: file not found: binary
make[1]: *** [lists.o] Error 1
make: *** [nossl] Error 2
</pre>

**Comment by infradig** [comment]
You shouldn't have to use -f option now.

**Comment by infradig** [comment]
Ok, I think i have it working now...

**Comment by triska** [comment]
On OSX 10.11.3, I get:

<pre>
<b>$ make</b>
ld -m elf_x86_64 -r -b binary -o http.o library/http.pro
ld: warning: option -m is obsolete and being ignored
ld: file not found: elf_x86_64
make: *** [GNUmakefile:79: http.o] Error 1
</pre>

**Comment by infradig** [comment]
And if you remove the '-m elf_x86_64' bit from the makefile? I thought you
needed that before?

**Comment by infradig** [comment]
You can also try gmake if it is installed.

**Comment by infradig** [comment]
You can lso do 'ld -V' to see what emulations are supported.

**Comment by triska** [comment]
With `gmake`, I get:

<pre>
<b>$ gmake</b>
ld -m elf_x86_64 -r -b binary -o http.o library/http.pro
ld: warning: option -m is obsolete and being ignored
ld: file not found: elf_x86_64
gmake: *** [GNUmakefile:79: http.o] Error 1
</pre>

`ld -V` yields:

<pre>
<b>$ ld -V</b>
ld: unknown option: -V
</pre>

**Comment by infradig** [comment]
So make = gmake on OSX.
Just try removing the '-m elf_x86_64'.

**Comment by triska** [comment]
When I remove `-m elf_x86_64`, I get:

<pre>
<b>$ make</b>
ld  -r -b binary -o http.o library/http.pro
ld: warning: option -b is obsolete and being ignored
ld: file not found: binary
make: *** [GNUmakefile:79: http.o] Error 1
</pre>

**Comment by triska** [comment]
When I remove `-m elf_x86_64` *and also* all `-b binary` switches, I get:

<pre>
<b>$ make</b>
ld  -r  -o lists.o library/lists.pl
ld: warning: -arch not specified
ld: warning: ignoring file library/lists.pl, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x6C 0x69 0x73 0x74 0x73 0x2C ) which is not the architecture being linked (x86_64): library/lists.pl
ld  -r  -o dict.o library/dict.pl
ld: warning: -arch not specified
ld: warning: ignoring file library/dict.pl, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x64 0x69 0x63 0x74 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/dict.pl
ld  -r  -o apply.o library/apply.pl
ld: warning: -arch not specified
ld: warning: ignoring file library/apply.pl, file was built for unsupported file format ( 0x6D 0x61 0x70 0x6C 0x69 0x73 0x74 0x28 0x5F 0x2C 0x20 0x5B 0x5D 0x29 0x2E 0x0A ) which is not the architecture being linked (x86_64): library/apply.pl
ld  -r  -o http.o library/http.pl
ld: warning: -arch not specified
ld: warning: ignoring file library/http.pl, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x68 0x74 0x74 0x70 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/http.pl
ld  -r  -o auth.o library/auth.pl
ld: warning: -arch not specified
ld: warning: ignoring file library/auth.pl, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x61 0x75 0x74 0x68 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/auth.pl
ld  -r  -o atts.o library/atts.pl
ld: warning: -arch not specified
ld: warning: ignoring file library/atts.pl, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x75 0x73 0x65 0x5F 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x6C 0x69 ) which is not the architecture being linked (x86_64): library/atts.pl
cc -o tpl tpl.o history.o builtins.o library.o parse.o print.o runtime.o skiplist.o base64.o network.o utf8.o lists.o dict.o apply.o http.o auth.o atts.o  -lreadline -L/usr/local/lib -lm -lssl -lcrypto
Undefined symbols for architecture x86_64:
  "__binary_library_apply_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_apply_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_auth_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_auth_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_http_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_http_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pl_start", referenced from:
      _g_libs in library.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [GNUmakefile:26: tpl] Error 1
</pre>

**Comment by cehteh** [comment]
Completely missed the part that the library/*.pl files are linked as blobs from makefile. This seem 'somehow' not working on OSX.

**Comment by triska** [comment]
Using `NOLDLIBS=1`, I get:

<pre>
<b>$ make NOLDLIBS=1 NOSSL=1</b>
cc -o tpl tpl.o history.o builtins.o library.o parse.o print.o runtime.o skiplist.o base64.o network.o utf8.o  -lreadline -L/usr/local/lib -lm
Undefined symbols for architecture x86_64:
  "__binary_library_apply_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_apply_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_error_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_error_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_http_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_http_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pl_start", referenced from:
      _g_libs in library.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tpl] Error 1
</pre>

My make version is:

<pre>
$ make -v

**Comment by triska** [comment]
I now get:

<pre>
<b>$ make</b>
GNUmakefile:76: *** missing separator.  Stop.
</pre>

When I change the `elifeq` to `endif ifeq`, I get again:

<pre>
<b>$ make NOSSL=1 NOLDLIBS=1</b>
cc -o tpl tpl.o history.o builtins.o library.o parse.o print.o runtime.o skiplist.o base64.o network.o utf8.o  -lreadline -L/usr/local/lib -lm
Undefined symbols for architecture x86_64:
  "__binary_library_apply_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_apply_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_error_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_error_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_http_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_http_pl_start", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pl_end", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pl_start", referenced from:
      _g_libs in library.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tpl] Error 1
</pre>

**Comment by infradig** [comment]
Are you sure library.o has been compiled with -DUSE_LDLIBS=0 in CFLAGS?

**Comment by triska** [comment]
I have now tried the compilation after `make clean`, and it worked perfectly.

Thank you a lot! I'm closing this issue.
