### ISSUE TITLE
GitHub Action for automating testing

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#153]
I created a GitHub Action for installing Trealla ProLog and run a couple of sanity tests:

https://github.com/logtalk-actions/setup-trealla-prolog

For now, it only supports Ubuntu but it can be easily extended. Next, I'm creating a workflow for running the Prolog standards compliance test suite bundled with Logtalk. After, I will submit a pull request so that the compliance tests will run everytime you push a commit. This should help tracking progress and detecting regressions.

**Comment by pmoura** [comment]
A sample [compliance](https://github.com/logtalk-actions/workflows/blob/master/compliance.yml) workflow is now available at:

https://github.com/logtalk-actions/workflows

**Comment by pmoura** [comment]
I have committed the workflow (customized for Trealla ProLog) in my fork:

https://github.com/pmoura/trealla/commit/47bcc2a8df54a4c70e65423ec5e5358ae153705a

The workflow takes ~16 minutes to run. Please take a look and let me know if you want further customization before I create the pull request. As of now, the workflow will run on every push to the repo to any branch.

**Comment by pmoura** [comment]
By creating a `gh-pages` branch, we can publish the compliance tests results for easy browsing:

https://pmoura.github.io/trealla/

**Comment by infradig** [comment]
I will look into this soon. A bit time limited at the moment.

**Comment by josd** [comment]
Glad that you are back :-)

**Comment by infradig** [comment]
I haven't been away! There's been plenty gone into the devel branch.

**Comment by infradig** [comment]
On every branch sounds excessive. I often have to switch machines multiple
times a day, and use devel branch (or other) to syn. I'd have to look at
staging somewhere else with this.

**Comment by pmoura** [comment]
> On every branch sounds excessive. I often have to switch machines multiple times a day, and use devel branch (or other) to syn. I'd have to look at staging somewhere else with this.

A possible solution is to run the workflow only when you pushed to a dedicated `testing` branch. You would do development as always and then, when reaching a point where the tests would be useful:

```bash
$ git checkout testing && git merge devel && git push
```

**Comment by pmoura** [comment]
I noticed that you already created a `gh-pages` branch. But you will need to delete it and recreate it by following the steps at e.g. https://jiafulow.github.io/blog/2020/07/09/create-gh-pages-branch-in-existing-repo/

**Comment by pmoura** [comment]
Update the https://pmoura.github.io/trealla/ report to also include the git commit and test sets that are reported as broken, crashed or timed out. Let me know if yo agree with a dedicated `testing` branch so that I can update the workflow accordingly and submit the pull request.

**Comment by infradig** [comment]
Ok, testing sounds good

**Comment by pmoura** [comment]
Good. Let mew know when you have created the `testing` branch and recreated the `gh-pages` branch following the steps described at https://jiafulow.github.io/blog/2020/07/09/create-gh-pages-branch-in-existing-repo/

**Comment by infradig** [comment]
Ok, but should gh-pages be published at / (root) or /docs?

**Comment by infradig** [comment]
I've done /docs

**Comment by infradig** [comment]
It doesn't like /docs so have tried / (root)...


GitHub <support@github.com>
10:36 AM (3 minutes ago)
 to Andrew
The page build failed for the `gh-pages` branch with the following error:

No `/docs` folder was found to build GitHub Pages. Check the source setting
for this repository. For more information, see
https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#missing-docs-folder
.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub
page at
https://support.github.com/contact?repo_id=287479920&page_build_id=227679078

**Comment by pmoura** [comment]
Indeed choose "root" instead and ignore any GitHub Pages build errors until the pull request is created and accepted. I will create it Monday morning (my time zone).

**Comment by pmoura** [comment]
Working as expected: https://infradig.github.io/trealla/ 👍

**Comment by infradig** [comment]
Yes, thanks.

**Comment by infradig** [comment]
>>> Working as expected: https://infradig.github.io/trealla/

Just a shame the past 2 months of improvements does not get reflected in
the graphs!

**Comment by infradig** [comment]
>>> Working as expected: https://infradig.github.io/trealla/

Also, most of the non-control errors (cut seems particularly egregious, but
I know what's going on) seem to be related to assertion / approx.equal /
deterministic, all of which fail automatically (or crash).

**Comment by pmoura** [comment]
Indeed, amazing progress! It does seem that a good number of the current test failures occur with meta-calls, which include test assertions, determinism checks, and approximate comparison of floats. But that also means once that underlying bug(s) are fixed, there will be a significant reduction on the number of failed tests.

**Comment by pmoura** [comment]
> >> Working as expected: https://infradig.github.io/trealla/
> Just a shame the past 2 months of improvements does not get reflected in the graphs!

Allure reports do support "trend" graphs. But that requires persisting some directories across runs. Easy to do locally (see https://logtalk3.readthedocs.io/en/latest/devtools/lgtunit.html#generating-allure-reports). It should also be possible in the context of GitHub Actions.

**Comment by pmoura** [comment]
P.S. Not sure if you noticed it, but when looking into the details of a failed test that generated an unexpected or wrong error, you can click on the issue name (e.g. "Error instead of success") on the "Overview" tab for further details.
