### ISSUE TITLE
atom_length/2: Semantic inconsistency

### ISSUE THREAD

**Issue by triska** [infradig/trealla#16]
I get:

<pre>
<b>?- atom_length(3, L).</b>
Error: uncaught exception... error(type_error(<b>atom</b>,3))
</pre>

This works exactly as expected, indicating that the first argument must be an **atom**.

However, I also get:

<pre>
<b>?- atom_length("abc", L).</b>

L = 3
</pre>

This means that the predicate may also succeed if the first argument is *not* an atom, but for example a *list*. This is not consistent with what the error told us about the predicate, and thus prevents automated logical&nbsp;reasoning about the code.

This is similar to #3.

**Comment by triska** [comment]
In addition, the type error is prescribed by the ISO standard for `atom_length/2`:

<pre>
8.16.1.3 Errors

  a) Atom is a variable
  - instantiation_error.

  b) Atom is neither a variable nor an atom
<b>  - type_error(atom, Atom).</b>
</pre>

**Comment by infradig** [comment]
I thought I removed that. Will look. I added a quick check  for string
length in length/2.

**Comment by triska** [comment]
I now get:

<pre>
<b>?- atom_length("abc", L).</b>
Error: uncaught exception... error(type_error(iso_atom,"abc"))
false.
</pre>

However, the expected type is `atom`, not `iso_atom`. Types are defined in:

<pre>
<b>7.12.2 Error classification</b>

Errors are classified according to the form of Error_term:

  ...

  b) There shall be a Type Error when the type of an
  argument or one of its components is incorrect, but not
  a variable. It has the form type_error(ValidType,
  Culprit) where

      ValidType E {
        atom,
        atomic,
        byte,
        callable,
        character,
        compound,
        evaluable,
        in_byte,
        in_character,
        integer,
        list,
        number,
        predicate_indicator,
        variable
      }.
</pre>

**Comment by infradig** [comment]
Oops

**Comment by triska** [comment]
This works nicely now, thank you a lot!
