### ISSUE TITLE
issue with numbervars/3

### ISSUE THREAD

**Issue by josd** [infradig/trealla#163]
This is with `Trealla Prolog (c) Infradig 2020, v1.6.16`
```
?- T = a([N, Y], b(N, E, V)), numbervars(T, 0, Q), writeln(T).
a([A,B],b(A,A,B))
T = a(['$VAR'(0),'$VAR'(1)],b('$VAR'(0),'$VAR'(0),'$VAR'(1))),
N = '$VAR'(0),
Y = '$VAR'(1),
E = '$VAR'(0),
V = '$VAR'(1),
Q = 4.
```
but I would rather expect
```
?- T = a([N, Y], b(N, E, V)), numbervars(T, 0, Q), writeq(T), nl.
a([A,B],b(A,C,D))
T = a(['$VAR'(0),'$VAR'(1)],b('$VAR'(0),'$VAR'(2),'$VAR'(3))),
N = '$VAR'(0),
Y = '$VAR'(1),
E = '$VAR'(2),
V = '$VAR'(3),
Q = 4.
```

PS am still reading K&R 'The C Programming Language' and your code
both look very impressive!

**Comment by infradig** [comment]
Did this work before?

**Comment by josd** [comment]
Not sure, but I think it never worked.
It might be that first argument list because what is working is
```
$ tpl
Trealla Prolog (c) Infradig 2020, v1.6.16
?- T = a(N, Y, b(N, E, V)), numbervars(T, 0, Q), writeq(T), nl.
a(A,B,b(A,C,D))
T = a('$VAR'(0),'$VAR'(1),b('$VAR'(0),'$VAR'(2),'$VAR'(3))),
N = '$VAR'(0),
Y = '$VAR'(1),
E = '$VAR'(2),
V = '$VAR'(3),
Q = 4.
?-
```

**Comment by infradig** [comment]
Oh, ok.

**Comment by infradig** [comment]
I went back a week or so and it didn't work, so yes is probably a case of
it never worked. And the list may be the clue, i'll look into it tomorrow.

**Comment by josd** [comment]
Excellent!
Have a good night and a happy weekend :-)

**Comment by infradig** [comment]
Turns out it was easy thanks to your clue!

**Comment by josd** [comment]
The solution looks nice https://github.com/infradig/trealla/commit/a9b58bea9974b1c05aa6dad43111beb60d9aec75
All tests in Seeye now look fine https://github.com/josd/seeye/commit/68a418f8469b011e18956895ceec300591185c63
Thank you very much!!
