### ISSUE TITLE
It should be wrapped in another level of parentheses https://github.com/infradig/trealla/issues/132#issuecomment-778749144

### ISSUE THREAD

**Issue by josd** [infradig/trealla#166]
The following is currently fine with Trealla ProLog
```
?- op(1150, xfx, '-:').
true.

?- assertz(re(b, X) -: not_re(c, X)).
true.
```
but it should be wrapped in another level of parentheses...

```
assertz((re(b, X) -: not_re(c, X)))
```
... to be portable.

**Comment by josd** [comment]
More specifically see https://swi-prolog.discourse.group/t/testing-seeye-with-tpl-swipl-and-scryer-prolog/3606/5?u=josderoo

**Comment by infradig** [comment]
The slackness here in Trealla is more by accident than design and when I
discovered it found SWI Prolog allowed it so left it in. I'm not as
tolerant now so will probably attempt to fix it soon.
