### ISSUE TITLE
WYSIWYG, What You See Is What You Get?

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#169]
Hello,
trealla is a great, clean codebase. Thank you very much indeed.

This is not a bug report but a display issue.
Unification example taken from book Clause and Effect, W.F.Clocksin.
Affected operator: /

Trealla Prolog (c) Infradig 2020, v1.6.22
?- g(Z,f(A,17,B),A/B,17) = g(C,f(D,D,E),C,E), assertz(g(Z/C)), g(M), N is M.
Z = 17/17,
A = 17,
B = 17,
C = 17/17,
D = 17,
E = 17,
M = 17/17/17/17,
N = 1.0.

?- assertz(g(17/17/17/17)).
true.
?- assertz(g(17/(17/17/17))).
true.

?- g(M).
M = 17/17/17/17 ;
M = 17/17/17/17 ;
M = 17/17/17/17.
?-  g(M), write_canonical(M).
/(/(17,17),/(17,17))M = 17/17/17/17 ;
/(/(/(17,17),17),17)M = 17/17/17/17 ;
/(17,/(/(17,17),17))M = 17/17/17/17.

?- g(M), X is M.
M = 17/17/17/17,
X = 1.0 ;
M = 17/17/17/17,
X = 0.0034602076124567475 ;
M = 17/17/17/17,
X = 289.0.

It seems that you don't always get what you see(YDNAGWYS).
In all cases I see: M = 17/17/17/17
(mental arithmetic tells me: get M = 0.0034602076124567475)

I wonder how this view display M = 17/17/17/17 is called? 

I guess no prolog system implements backtracking on associativity. 
Clearly, this doesn't work:
?- Y is 17/17/17/17.
Y = 0.0034602076124567475 ;
Y = 1.0 ;
Y = 289.0.

**Comment by infradig** [comment]
Thanks for highlighting this. Printing of operators is some code that is
decidedly not clean code.

**Comment by flexoron** [comment]
Yes, unpicturesque and there is an unbeautiful thing, too (in all prolog implementations).

?- A = 17/17, B = 17/17, C = A/B, X is C.
A = 17/17,
B = 17/17,
C = 17/17/17/17,
X = 1.0.

C = A/B should be handled symbolically(literally), 17/17/17/17,
and not implicitly functional, 17/17/(17/17), at that point.

As long as I do not 'calculate' but 'unify'
there is no need to apply the functional? /(17,17) representation of A and B
I want to express(concatenate) C symbolically.

And if I want the result X = 1.0, I would demand it explicit:
C = A/(B), X is C.

**Comment by infradig** [comment]
I don't have a problem with what Prolog does here, unification is not like
macro pasteing. The missing parenthesis by Trealla on printing is something
to be fixed.

**Comment by flexoron** [comment]
I do have a problem with what Prolog does here:
?- (17/(((((((((((((17/(17/17) = /(/(17,17),/(17,17)).
true.

**Comment by infradig** [comment]
But that's not Prolog, that's an error in Trealla.

**Comment by infradig** [comment]
And when you remove the redundant outer parenthesis it works...

?-  17/(((((((((((((17/(17/17) = /(/(17,17),/(17,17).
false.

But the original case is still handled wrong, definitely a bug.

**Comment by infradig** [comment]
My bad, I can't count. Ignore that last.

**Comment by infradig** [comment]
Trealla needs to improve unmatched parens checking.

**Comment by infradig** [comment]
But this

   (17/(17/(17/17))) = /(/(17,17),/(17,17).

should definitely fail, as it does. They are not the same.

**Comment by flexoron** [comment]
sorry, was just kidding, of course not a Prolog error but an now known error in Trealla.
