### ISSUE TITLE
Trealla toplevel...a road to nowhere?

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#170]
Hello,
perhaps it is known already, maybe it's an environment problem here.
If so, please close the issue. 

Example 1
Enter a single full-stop: ?- .\<Return\>
Ctrl-D does not work
I have to Stop and Kill the process.

linux-bash $ ./tpl
Trealla Prolog (c) Infradig 2020, v1.6.22-dirty
?- .

^Z
[1]+  Stopped   ./tpl
linux-bash $ kill -9 %1

main()
seems that the return of history_readline_eol()
disappears here: pl_eval(pl, line)

Example 2
Enter CR: ?- \<Return\>
This time Ctrl-D works, halt. doesn't.

Trealla Prolog (c) Infradig 2020, v1.6.22-dirty
?- 
 |      halt.
 |
^D
linux-bash $

**Comment by infradig** [comment]
Well spotted.

**Comment by flexoron** [comment]
no big deal...the prolog implementation deserves more attention.

I think the terminal input processing is the spot to fix it occasionally.

history.c
history_readline_eol()

Now this is kind of fun:
inserted 2 printf() 

LOOP:
printf("LOOP\n");
for (;;) {
printf("FOR\n");

In case of just CR I get this (you see 4 FORs):

Trealla Prolog (c) Infradig 2020, v1.6.22-dirty
LOOP
?- \<ret\> 
FOR
LOOP
 | \<ret\>
FOR
FOR
FOR
FOR
LOOP
 | \<ret\>
FOR
FOR
FOR
FOR
LOOP
 |

Whats going on here?
Even worse, restarted, and this time I count 5 FORs

Trealla Prolog (c) Infradig 2020, v1.6.22-dirty
LOOP
?- 
FOR
LOOP
 | \<ret\>
FOR
FOR
FOR
FOR
FOR
LOOP
 |

**Comment by flexoron** [comment]
and here I get a very strange realloc() core dump(after just hitting 24xCR)

printf() prints the cmd char in hex: a = line feed and n = 1,2,...23,24

if (cmd) {
size_t n = strlen(cmd) + strlen(line);
printf("free line cmd: %x  %d\n",*cmd,(int)n);
cmd = realloc(cmd, n+1);

$ ./tpl
Trealla Prolog (c) Infradig 2020, v1.6.22-dirty
?- \<ret\>
 |	\<ret\>
free line cmd: a  1
 |	\<ret\>
free line cmd: a  2
 |	
\:
free line cmd: a  23
 |	
free line cmd: a  24
realloc(): invalid next size
Aborted (core dumped)

btw
you free the line
free(line);
but still access the adress later
const char *end_ptr = line + strlen(line) - 1;
It works unless it doesn't!

**Comment by infradig** [comment]
Hope to look into this soon. Just finishing off something.

**Comment by flexoron** [comment]
"User Input" processing is a challenge.
Have rewritten that function history_readline_eol().
It works now and returns valid commands.
For example, I eliminate inserting newlines and input like this is possible:
 |	h
 |	a
 |	l
 |	t
 |	.
cmd: *halt.*
linx-bash $

Input which makes no sence is ignored, too.
Something like: spacespacespacefull-stop (entered at the very beginning)

In your code: free(line) is a bug
const char *s = line;
free(line);
int ch = get_char_utf8(&s);
Maybe this explaines why counting 4 LOOPS here and 5 LOOPS there.

**Comment by infradig** [comment]
Feel free to send a pull request, I'll have look.

**Comment by infradig** [comment]
The current code was a quick hack to remove a custom implementation and add
GNU readline. Feel free to also remove the goto!

**Comment by flexoron** [comment]
no, goto is ok.
right now, figuring out how to handle other stupid user input:
spacespacespacefull-stopspacespacespace

**Comment by flexoron** [comment]
// still unfinished but continues to avoid a road to nowhere

char *history_readline_eol(const char *prompt, char eol)
{
        char *cmd = NULL;
        char *line;

LOOP:

        if ((line = readline(prompt)) == NULL)
                return NULL;

        const char *s = line;
        const char *space_ptr = line;

        if (cmd) {
                size_t l = strlen(line);
                size_t c = strlen(cmd);
                size_t n = l + c;
                if ((l == 0) || (c == 0) || (n == 1)) {
                        if (*s == eol) {
                                free(line);
                                goto LOOP;
                        }
                        while (isspace(*space_ptr)) {
                                space_ptr++;
                                if (*space_ptr == eol) {
                                        free(line);
                                        goto LOOP;
                                }
                        }
                }
                l = strlen(space_ptr);
                cmd = realloc(cmd, l+c+1);
                ensure(cmd);
                strcat(cmd, space_ptr);
        } else {
                if (*s == eol) {
                        free(line);
                        goto LOOP;
                }
                while (isspace(*space_ptr)) {
                        space_ptr++;
                        if (*space_ptr == eol) {
                                free(line);
                                goto LOOP;
                        }
                }
                cmd = (char *)calloc(strlen(space_ptr)+1,sizeof(char));
                strcat(cmd, space_ptr);
        }

        for (;;) {
                int ch = get_char_utf8(&s);
                if (ch == 0) {
                        const char *end_ptr = line + strlen(line) - 1;
                        while (isspace(*end_ptr) && (end_ptr != line)) {
                                end_ptr--;
                        }
                        if (*end_ptr == eol) {
                                add_history(cmd);
                                free(line);
                                break;
                        }
                        free(line);
                        prompt = " |\t";
                        goto LOOP;
                }
        }
printf("cmd: *%s*\n",cmd);
        return cmd;
}

**Comment by flexoron** [comment]
nice but: just \<cr\>

 ./tpl                                        ±[master]
Trealla Prolog (c) Infradig 2020, v1.7.2
?- 
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
 |	
realloc(): invalid  size
abort (core dumped)  ./tpl

**Comment by flexoron** [comment]
using the still unfinished but continues to avoid that road to nowhere function
I don't get that core dump.

**Comment by flexoron** [comment]
$ ./tpl
Trealla Prolog (c) Infradig 2020, v1.7.4-dirty
?- halt excellent lets close the issue with this delayed full-stop here .
$

$ ./tpl
Trealla Prolog (c) Infradig 2020, v1.7.4-dirty
?- 
 |	halt
 |	to close or not to close
 |	that is the question....
$

**Comment by infradig** [comment]
This is actually a separate issue in the parser. It's taking all the extra
stuff after halt ignoring it and then calling the halt predicate. But leave
the issue open here to fix.

**Comment by infradig** [comment]
$ tpl
Trealla Prolog (c) Infradig 2020, v1.7.5
?- halt excellent lets close the issue with this delayed full-stop here .
Error: syntax error
false.
