### ISSUE TITLE
Android: Minor Compiling Issue, 1 Test failed

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#172]
Hello,

just fyi 

Android 10, Termux (termux.com)
clang version 11.1.0, Target: aarch64-unknown-linux-android24

The Android header file sys/types.h is bad:

cc -Isrc -I/usr/local/include -DVERSION='"v1.7.4"' -O3  -Wall -Wextra -D_GNU_SOURCE -DUSE_OPENSSL=1 -DUSE_LDLIBS=1   -c -o arith.o arith.c
In file included from arith.c:12:
./internal.h:45:20: error: typedef redefinition with different types ('__uint64_t' (aka 'unsigned long') vs 'unsigned int')
typedef __uint64_t uint_t;

/usr/include/sys/types.h:136:29: note: previous definition is here
typedef unsigned int uint_t;

1 error generated.

Taking the typedef out, Trealla compiles neatly; 1 test failed. 

$ make test
Running tests/issues/test081.pl...
2c2
 `< [[3.0000000000000036,2.0000000000000009],[5.0000000000000053,0.99999999999999267],[-5.773159728050814e-   15,1.0000000000000027],[0.99999999999999623,1.0000000000000036]]`

   `> [[3.000000000000004,2.0000000000000013],[5.0000000000000062,0.99999999999999312],[-6.2172489379008766e-   15,1.0000000000000022],[0.999999999999996,1.0000000000000033]]`

**Comment by infradig** [comment]
Ok, issues/test081 that's a common floating point discrepancy on ARM
devices.

**Comment by flexoron** [comment]
Ok, I recommend Type III Unum Posit.

**Comment by infradig** [comment]
I've been thinking of renaming the basic Trealla types, maybe tpint_t,
tpuint_t and tpflt_t etc to avoid such conflicts.

**Comment by flexoron** [comment]
The typedef in types.h is wrong

Old compatibility names for C types:
typedef unsigned short ushort;
typdef unsigned int uint;
typedef unsigned long int ulong;

uint_t does not belong to these definitions

hmm..maybe t_int, t_uint, ... as easy to read as int_t ...

**Comment by flexoron** [comment]
this
typedef unsigned long int uint_t;
is conflict-free but makes no sense.
On the other side your definitions help finding such errors.
