### ISSUE TITLE
Make predicate_property/2 backtrack & add meta_predicate/1 directive

### ISSUE THREAD

**Issue by infradig** [infradig/trealla#175]
> Btw, predicate_property/2 should be able to enumerate by backtracking all
> properties of a predicate when called with an unbound second argument (the first argument is required to be bound). That will have to wait a while.

I understand. No pressure. It's not an issue for the Logtalk compiler itself.

_Originally posted by @pmoura in https://github.com/infradig/trealla/issues/174#issuecomment-788831920_

**Comment by infradig** [comment]
I have pushed to devel an implementation that backtracks over the second arg. It is capable of doing the first arg as well but I have disabled that for now.

It also sets the meta_predicate property for built_in predicates. I have yet to add the meta_predicate/1 directive that works for user code.

**Comment by pmoura** [comment]
Looks good:

```text
$ tpl
Trealla Prolog (c) Infradig 2020, v1.7.20-30-g9ae76
?- predicate_property(task(_,_,_), P).
P = built_in 
; P = private 
; P = static 
; P = meta_predicate(task(2,?,?)) 
; false.
?- predicate_property(call(_,_,_), P).
P = built_in 
; P = private 
; P = static 
; P = meta_predicate(call(2,?,?)) 
; false.
```

Thanks for the quick fix. The only test failing is failure instead of a domain error for invalid properties.

**Comment by infradig** [comment]
> Thanks for the quick fix. The only test failing is failure instead of a
domain error for invalid properties.

I'll have add a memberchk to pickup that.

**Comment by pmoura** [comment]
All `predicate_property/2` tests now pass 🙂
