### ISSUE TITLE
test020.pl fails with Trealla Prolog (c) Infradig 2020, v1.7.25-2-g00886

### ISSUE THREAD

**Issue by josd** [infradig/trealla#177]
Running tests/issues/test020.pl ...
1c1
< Error: syntax error, parsing number, line 4, file '/home/andrew/trealla/tests/issues/test020.pl'
---
> Error: syntax error, parsing number, line 4, file '/home/jdroo/github.com/infradig/trealla/tests/issues/test020.pl'

**Comment by infradig** [comment]
I remember that, had to change the line number. But it has been running ok
for a while. So not seeing this...

**Comment by infradig** [comment]
Actually, I see what is going on here, the file name is localized. It
should be changed to just report 'tests020.pl' as the file.

**Comment by josd** [comment]
Very well and now it works fine.
Thanks a lot!
