### ISSUE TITLE
suggestion occurs_check:  flags error,true,false

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#182]
fyi
mentioned Trealla here: xxremoved referencexx
Scryer issue: One-Liner occurs_check error in vain #885

Hope this is ok for you.

Don't know how trealla does occurs_check

ok?

**Comment by infradig** [comment]
OK, will get look into it soon.

**Comment by flexoron** [comment]
?- [user].
rot([A|B]-[A|W],B-W).

?- set_prolog_flag(occurs_check, error). % ?

?- rot([1,2,3|X]-X,Y-Z), rot(Z-X,Y-Z).

**Comment by infradig** [comment]
The flag is accepted but does nothing as yet.

**Comment by flexoron** [comment]
That's good! 
Maybe there is a chance coming along with the programmer.

The messages so far are not very helpful.
scryer: caught: error(representation_error ... ? aha ?
gprolog: cannot display cyclic term for X ... ? I see ?

trealla: if it does something and if possible 

flag error ... debunk  programmer's  fault.
Error: cannot process cyclic term(s): 
X = [1,1,2,3|X], Y = [2,3,1,1|Y], Z = [1,2,3,1|Z].

flag true
false

flag false
burn programmer out

**Comment by infradig** [comment]
It's on the list, patience grasshopper.

**Comment by UWN** [comment]
> scryer: caught: error(representation_error ... ? aha ?

To cite scryer fully: `representation_error(term)`. See [this discussion](https://github.com/mthom/scryer-prolog/issues/783) why.
