### ISSUE TITLE
writing terms containing '-'

### ISSUE THREAD

**Issue by josd** [infradig/trealla#186]
This is a rather cosmetic detail, Trealla gives
```
$ tpl -g "writeln(exp(-x^2)), halt"
exp( -x^2)
```
whereas I would expect
```
$ swipl -g "writeln(exp(-x^2)), halt"
exp(-x^2)
```

**Comment by josd** [comment]
Thanks you very much for the fix and now it looks nice:
```
$ tpl -g "writeln(exp(-x^2)), halt"
exp(-x^2)
```

**Comment by infradig** [comment]
I'm not too keen on this...

$ tpl
?- write(exp(1- -x^2)), nl.
exp(1-(-x^2))

Will keep for an idle moment.

**Comment by josd** [comment]
I see and also
```
$ tpl
Trealla Prolog (c) Infradig 2020, v1.8.12
?- X = -1, write(-X), nl.
- -1
X = -1.
?-
```
and
```
?- X = -1, write(-(X)), nl.
-(-1)
X = -1.
?-
```

**Comment by josd** [comment]
It is currently fine as is and nothing is broken.
