### ISSUE TITLE
Apparent engine bug with recursive calls

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#188]
The following code is extracted from the Logtalk `os` library:

```logtalk
make_directory_path_portable(Path) :-
	absolute_file_name(Path, ExpandedPath),
	(	exists_directory(ExpandedPath) ->
		true
	;	sub_atom(ExpandedPath, _, 1, 0, '/') ->
		sub_atom(ExpandedPath, 0, _, 1, ExpandedPath1),
		path_parts(ExpandedPath1, [], Parts)
	;	path_parts(ExpandedPath, [], Parts)
	),
	make_parts(Parts).

path_parts(Path, Parts0, Parts) :-
	writeq(path_parts(Path, Parts0, Parts)), nl,
	decompose_file_name(Path, Directory, Name, Extension),
	(	Path == Directory ->
		atom_concat(Name, Extension, Part0),
		atom_concat('/', Part0, Part),
		Parts = [Part| Parts0]
	;	Directory == ('/') ->
		Parts = [Path| Parts0]
	;	Directory = './' ->
		atom_concat(Name, Extension, Part),
		Parts = [Part| Parts0]
	;	atom_concat(Name, Extension, Part0),
		atom_concat('/', Part0, Part),
		sub_atom(Directory, 0, _, 1, Directory1),
		path_parts(Directory1, [Part| Parts0], Parts),
		writeq(path_parts(Directory1, [Part| Parts0], Parts)), nl
	).

make_parts([]).
make_parts([Part| Parts]) :-
	make_parts_(Parts, Part).

make_parts_([], Part) :-
	(	exists_directory(Part) ->
		true
	;	make_directory(Part)
	).
make_parts_([Part| Parts], Root) :-
	(	exists_directory(Root) ->
		true
	;	make_directory(Root)
	),
	atom_concat(Root, Part, NewRoot),
	make_parts_(Parts, NewRoot).

decompose_file_name(File, Directory, Name, Extension) :-
	atom_codes(File, FileCodes),
	char_code('/', SlashCode),
	(	strrch(FileCodes, SlashCode, [_Slash| BasenameCodes]) ->
		atom_codes(Basename, BasenameCodes),
		atom_concat(Directory, Basename, File)
	;	Directory = './',
		Basename = File,
		BasenameCodes = FileCodes
	),
	char_code('.', DotCode),
	(	strrch(BasenameCodes, DotCode, ExtensionCodes) ->
		atom_codes(Extension, ExtensionCodes),
		atom_concat(Name, Extension, Basename)
	;	Name = Basename,
		Extension = ''
	).

% the following auxiliary predicate is simplified version of code
% written by Per Mildner and is used here with permission
strrch(Xs, G, Ys) :-
	Xs = [X| Xs1],
	(	X == G ->
		strrch1(Xs1, G, Xs, Ys)
	;	strrch(Xs1, G, Ys)
	).

strrch1([], _G, Ys, Ys).
strrch1([X| Xs1], G, Prev, Ys) :-
	(	X == G ->
		strrch1(Xs1, G, [X| Xs1], Ys)
	;	strrch1(Xs1, G, Prev, Ys)
	).
```
The code is already instrumented to print the calls to the `path_parts/3` recursive predicate. Assuming the code saved to a `mdp.pl` file, we get:

```text
$ tpl
Trealla Prolog (c) Infradig 2020, v1.8.37-21-g4a4a7
?- [mdp].
true.
?- make_directory_path_portable('foo/bar/baz').
path_parts('/Users/pmoura/Documents/Prolog/trealla/foo/bar/baz',[],_5)
path_parts('/Users/pmoura/Documents/Prolog/trealla/foo/bar',['/baz'],_5)
false.
```

I.e. the recursive call is failing to unify with the predicate head. Maybe a bug in variable handling? The code works perfectly in other Prolog systems (e.g. SWI-Prolog which provides the same predicate for checking directory existence).

**Comment by infradig** [comment]
Problem was the introduction of string slices, the first and only use so far was in sub_atom/5, and it seems it's not quite there yet. So backing off on that for now.

**Comment by pmoura** [comment]
The Logtalk `os` library tests that previously fail now pass with this fix but I get an error message running them that signals a different bug:

```text
Trealla Prolog (c) Infradig 2020, v1.8.40
?- {os(tester)}.
% 
% tests started at 2021-05-02, 16:14:24
% 
% running tests from object tests
% file: /Users/pmoura/logtalk/library/os/tests.lgt
% 
% os_time_stamp_1_01: success (in 0.00022816658020019531 seconds)
% os_time_stamp_1_012: success (in 1.52587890625e-05 seconds)
% os_date_time_7_01: success (in 1.5020370483398438e-05 seconds)
...
% os_directory_files_3_02: success (in 0.0012280941009521484 seconds)
% os_directory_files_3_03: success (in 0.0022451877593994141 seconds)
% os_directory_files_3_04: success (in 0.0010221004486083984 seconds)
exception: error(type_error(callable,'$lgt_debug'),'$lgt_debug'/2)
```

**Comment by pmoura** [comment]
The ``'$lgt_debug'`/2` predicate is a Logtalk compiler internal static predicate.

**Comment by pmoura** [comment]
Btw, this is a recent regression. Before the c06f752494bbb6073988c3687011cdd2b26fe503 fix, there were five failed tests for the `os` library but the test run completed, presenting the results and code coverage stats, without the type error above occurring. Thus, this error seems to be a regression introduced in the last couple of days.

**Comment by pmoura** [comment]
With c8bd939141fc4a4d47c5865db3550206bcfc2640, the test run to completion but we get a similar error:

```text
...
% 
% 95 tests: 1 skipped, 94 passed, 0 failed
% completed tests from object tests
% 
...
% 2 entities declared as covered containing 82 clauses
% 2 out of 2 entities covered, 100.0% entity coverage
% 79 out of 82 clauses covered, 96.341463414634148% clause coverage
% 
uncaught exception: error(type_error(callable,''),''/0)
```

**Comment by infradig** [comment]
I'm not seeing this error. Running on the new devel branch. The old devel branch got renamed to devel2 and a new devel branch created. You may have to reset your devel branch. I'll try against master.

**Comment by infradig** [comment]
Ok, master is good, But devel2 errors (actually crashe\s for me). The devel2 branch is now just a dead-end with some experiments I may salvage.

**Comment by pmoura** [comment]
With v1.8.51-2-g5037c I get a crash after the test run (all pass):

```text
...
% 2 entities declared as covered containing 82 clauses
% Segmentation fault: 11
```

With the `master` branch (v1.8.51), I get the error above:

```text
% 
% 2 entities declared as covered containing 82 clauses
% 2 out of 2 entities covered, 100.0% entity coverage
% 79 out of 82 clauses covered, 96.341463414634148% clause coverage
% 
uncaught exception: error(type_error(callable,''),''/0)
```

**Comment by infradig** [comment]
This is what I get on master...

:~/lgt3git/library/os$ tpl --version
Trealla Prolog (c) Infradig 2020, v1.8.52
:~/lgt3git/library/os$ time ~/lgt3git/scripts/logtalk_tester.sh -p trealla
-g "set_logtalk_flag(clean,on)" -w -t 240
% Batch testing started @ 2021-05-15 09:06:26
%         Logtalk version: 3.47.0-b01
%         Trealla Prolog version: 1.8.52
%
% lgt3git/library/os
%         95 tests: 1 skipped, 94 passed, 0 failed
%         completed tests from object tests
%         clause coverage 96.341463414634148%
%
% Skipped tests
lgt3git/library/os/tests.lgt - os_command_line_arguments_1_01 @ tests
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timeouts, 0 crashes
% 95 tests: 1 skipped, 94 passed, 0 failed
%
% Batch testing ended @ 2021-05-15 09:06:38

real 0m12.239s
user 0m6.059s
sys 0m0.199s
:~/lgt3git/library/os$

**Comment by pmoura** [comment]
If I run the tests using the `logtalk_tester` automation (`master` branch for Trealla) like you did I get:

```text
$ logtalk_tester -p trealla
% Batch testing started @ 2021-05-15 00:09:52
%         Logtalk version: 3.47.0-b01
%         Trealla Prolog version: 1.8.51
%
% logtalk/library/os
%         95 tests: 1 skipped, 94 passed, 0 failed
%         completed tests from object tests
%         clause coverage 
%
% Skipped tests
logtalk/library/os/tests.lgt - os_command_line_arguments_1_01 @ tests
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timeouts, 0 crashes
% 95 tests: 1 skipped, 94 passed, 0 failed
%
% Batch testing ended @ 2021-05-15 00:10:01
```

Note that the clause coverage percentage is missing. Running the tests manually shows why:

```text
?- {tester}.
% 
...
% 
% 2 entitiesuncaught exception: error(type_error(callable,''),''/0)
```
I'm compiling with clang on macOS:

```text
$ cc --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

That may explain the different results. But I don't get any compilation warnings with either `master` or `devel` branches.

**Comment by pmoura** [comment]
No longer get that type error with v1.8.66.
