### ISSUE TITLE
phrase/2: Grammar goals do not work

### ISSUE THREAD

**Issue by triska** [infradig/trealla#19]
Currently, I get:

<pre>
?- phrase({true}, _).
Error: uncaught exception... error(existence_error(procedure,[]/2),[]/2)
</pre>

Expected: Success.

See also #18 , and #13 for a reference implementation that I hope is useful to implement this correctly.

**Comment by infradig** [comment]
There's still a problem with the REPL, perhaps unrelated but relevant...

~/trealla >>> swipl -l samples/grammar.pro -g "phrase(np,Ls),writeln(Ls),halt"                                            [the,woman]

~/trealla >>> ./tpl -l samples/grammar.pro -g "phrase(np,Ls),writeln(Ls),halt"                                            ±[the,woman]

~/trealla >>> ./tpl -l samples/grammar.pro                                                                                ±[●][devel]
?- phrase(np,Ls),writeln(Ls).
[the,woman]
Ls = [the,woman]
true.

?- phrase(np,Ls).
Ls = [the]
true.
?- 

The last query where it just shows [the] needs looking into.

So don't close this.

**Comment by infradig** [comment]
Think this is fixed.

**Comment by triska** [comment]
Very nice, thank you a lot!
