### ISSUE TITLE
UTF-8 files with a BOM cannot be consulted

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#195]
The same files with the BOM removed can be consulted without issues.

**Comment by infradig** [comment]
What tesst is this? The tests/prolog/unicode tests all run clean.

**Comment by infradig** [comment]
Actually, I see the problem.

**Comment by pmoura** [comment]
The test set is `logtalk3/tests/logtalk/directives/encoding_1`. Before running it, please update to the latest Logtalk git version as I pushed an update to the Trealla Prolog adapter file.

Just tried the `master` branch:

```text
Trealla Prolog (c) Infradig 2020, v1.8.51
?- {split}.
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
% [ /Users/pmoura/Documents/Logtalk/logtalk3/tests/logtalk/directives/encoding_1/split.lgt loaded ]
% (0 warnings)
```

Same with v1.8.51-2-g5037c (`devel` branch). The error I was seeing was with an older commit.

But trying to run the tests I get an error. Not sure yet why.

**Comment by infradig** [comment]
Ok, seeing that error on {skip}. When I run {tester} i get:


!     Domain error: value 'ISO-8859-1' is not in domain text_encoding
!       in directive encoding/1
!       in auxiliary clause generated for file
/home/andrew/lgt3git/tests/logtalk/directives/encoding_1/include_iso_8859_1.lgt
!

**Comment by pmoura** [comment]
Be sure to pull `logtalk3` **and** that you're on the `master` branch.

**Comment by infradig** [comment]
Wasn't on master

**Comment by infradig** [comment]
:~/lgt3git/tests/logtalk/directives/encoding_1$
~/lgt3git/scripts/logtalk_tester.sh -p trealla -g
"set_logtalk_flag(clean,on)" -w -t 240
% Batch testing started @ 2021-05-15 09:21:08
%         Logtalk version: 3.47.0-b01
%         Trealla Prolog version: 1.8.52
%
% lgt3git/tests/logtalk/directives/encoding_1
%         5 tests: 0 skipped, 4 passed, 1 failed
%         completed tests from object tests
%         clause coverage n/a
%
% Compilation errors/warnings and failed unit tests
% (compilation errors/warnings might be expected depending on the test)
!     encoding_1_includes: failure (in 0.00051784515380859375 seconds)
!       test assertion failed: ['Paulo Moura','John Smith','Anto Sim','Cia
Concei','João Raínho','Luís Araújo']==['Paulo Moura','John Smith','António
Simões','Cátia Conceição','João Raínho','Luís Araújo']
!       in file
/home/andrew/lgt3git/tests/logtalk/directives/encoding_1/tests.lgt between
lines 5-8
*     The encoding/1 directive is ignored
*       while compiling file
*       in auxiliary clause generated for file
/home/andrew/lgt3git/tests/logtalk/directives/encoding_1/iso_8859_1.lgt
*
%
% Failed tests
lgt3git/tests/logtalk/directives/encoding_1/tests.lgt - encoding_1_includes
@ tests
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timeouts, 0 crashes
% 5 tests: 0 skipped, 4 passed, 1 failed
%
% Batch testing ended @ 2021-05-15 09:21:14
:~/lgt3git/tests/logtalk/directives/encoding_1$

**Comment by infradig** [comment]
Or if I do it this way...

:~/lgt3git/tests/logtalk/directives/encoding_1$
~/lgt3git/integration/tplgt.sh -g "{tester},halt"

Logtalk 3.47.0-b01
Copyright (c) 1998-2021 Paulo Moura

% Default lint compilation flags:
%   unknown_predicates: warning, undefined_predicates: warning
%   unknown_entities: warning, steadfastness: silent, naming: silent
%   missing_directives: warning, duplicated_directives: warning
%   duplicated_clauses: silent, portability: silent, deprecated: warning
%   redefined_built_ins: silent, redefined_operators: warning
%   trivial_goal_fails: warning, always_true_or_false_goals: warning
%   lambda_variables: warning, suspicious_calls: warning
%   disjunctions: warning, tail_recursive: silent
%   singleton_variables: warning, underscore_variables: dont_care
% Default optional features compiler flags:
%   complements: deny, dynamic_declarations: deny
%   context_switching_calls: allow, events: deny
% Other default compilation flags:
%   report: on, scratch_directory: ./.lgt_tmp/
%   source_data: on, code_prefix: '$', hook: n/d
%   optimize: off, debug: off, clean: on, reload: changed
% Backend Prolog compiler file compilation and loading flags:
%   prolog_compiler: []
%   prolog_loader:   []
% Read-only compilation flags (backend Prolog compiler features):
%   prolog_dialect: trealla, modules: supported, threads: unsupported
%   engines: unsupported, tabling: unsupported, coinduction: unsupported
%   unicode: full, encoding_directive: source
%
% No settings file found in startup, Logtalk user, home, or config
directories.
% Using default flag values set in the backend Prolog compiler adapter file.
%
% For Logtalk help on libraries, entities, and built-in features, use:
% ?- {help(loader)}. or ?- logtalk_load(help(loader)).
%
% For Logtalk compiler warnings/errors explanations and fix suggestions,
use:
% ?- {tutor(loader)}. or ?- logtalk_load(tutor(loader)).
%
%
% tests started at 2021-05-15, 09:23:13
%
% running tests from object tests
% file: /home/andrew/lgt3git/tests/logtalk/directives/encoding_1/tests.lgt
%
% encoding_1_us_ascii: success (in 0.064220905303955078 seconds)
*     The encoding/1 directive is ignored
*       while compiling file
*       in auxiliary clause generated for file
/home/andrew/lgt3git/tests/logtalk/directives/encoding_1/iso_8859_1.lgt
*
% encoding_1_iso_8859_1: success (in 0.062808036804199219 seconds)
% encoding_1_utf_8_bom: success (in 0.062613010406494141 seconds)
% encoding_1_utf_8_no_bom: success (in 0.06294703483581543 seconds)
!     encoding_1_includes: failure (in 0.000553131103515625 seconds)
!       test assertion failed: ['Paulo Moura','John Smith','Anto Sim','Cia
Concei','João Raínho','Luís Araújo']==['Paulo Moura','John Smith','António
Simões','Cátia Conceição','João Raínho','Luís Araújo']
!       in file
/home/andrew/lgt3git/tests/logtalk/directives/encoding_1/tests.lgt between
lines 5-8
%
% 5 tests: 0 skipped, 4 passed, 1 failed
% completed tests from object tests
%
% no code coverage information collected
% tests ended at 2021-05-15, 09:23:13
%
:~/lgt3git/tests/logtalk/directives/encoding_1$

**Comment by pmoura** [comment]
Same for me with `master` (v1.8.52). But I still get:

```text
Trealla Prolog (c) Infradig 2020, v1.8.52
?- {split}.
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
% [ /Users/pmoura/Documents/Logtalk/logtalk3/tests/logtalk/directives/encoding_1/split.lgt loaded ]
% (0 warnings)
true .
false.
?- 
```

This puzzling warnings may be due to the same bug that is causing the `encoding_1_includes` test to fail (the `split.lgt` source file contains `include/1` directives).

**Comment by pmoura** [comment]
Also:

```text
Trealla Prolog (c) Infradig 2020, v1.8.52
?- consult('include_iso_8859_1.lgt').
true.
?- name(Name).
Name = 'Anto Sim' 
; Name = 'Cia Concei'.
?- 
```

As an ISO-8859-1 file can be read as a UTF-8 file, not sure why the characters with diacritics are missing.

**Comment by infradig** [comment]
Isn't the encoding-1_includes problem due to no ISO-8859-1 support?

**Comment by pmoura** [comment]
Yes, sorry. Late here. ISO-8859-1 maps 1:1 to Unicode code points but not to UTF-8 for characters above 127.

**Comment by pmoura** [comment]
I will look into updating the test set.

**Comment by infradig** [comment]
Yeah, i'm pretty sure I don't want to support other character sets.

**Comment by pmoura** [comment]
I have pushed a fix to the adapter file.

**Comment by pmoura** [comment]
Fixed the test set. It will now be skipped when running on Trealla.

**Comment by pmoura** [comment]
With v1.8.54 (`master` branch), any Logtalk file I try to load results in several puzzling repeated warnings. For example:

```text
Trealla Prolog (c) Infradig 2020, v1.8.54
?- {ack(ack)}.
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
Warning: singleton: UTF, near line 11, file ''
% [ /Users/pmoura/logtalk/examples/ack/ack.lgt loaded ]
% (0 warnings)
true .
false.
```

**Comment by pmoura** [comment]
Thanks for the fix!
