### ISSUE TITLE
New built-in predicate suggestion: make_directory_path/1

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#197]
This predicate is expected to create a directory and, if necessary, any of the parent directories (in contrast, the `make_directory/1` is expected to throw an exception if the parent directories don't exist). The `make_directory_path/1` is expected to succeed if the directory already exists.

I looked into implementing this predicate myself and submit a pull request. But in C there isn't a built-in function that we can call that implements this functionality, unlike in other languages. There are, however, several open-source implementation available that may be possible to adapt/reuse.

**Comment by infradig** [comment]
Should be easy enough.

**Comment by pmoura** [comment]
Just tested it. an issue, hopefully an easy fix:

```text
?- make_directory_path('foo/bar').
true.
?- make_directory_path('foo/bar').
uncaught exception: error(existence_error(already_exists,'foo/bar'),make_directory_path/1)
false.
```

The second query is also expected to succeed. I.e. the predicate should succeed when the directory already exists. This matches the behavior in other systems (e.g. SWI-Prolog or Logtalk with its portable -but slow- implementation of this predicate).

**Comment by pmoura** [comment]
P.S. With that fix, all tests by `{os(tester)}` should pass.

**Comment by infradig** [comment]
Hm, odd, make_directory/1 throws if it already exists. Wonder why different.

**Comment by pmoura** [comment]
Because this predicate recursively creates the parent directories **if** they don’t exist. The last directory in the path is just handled the same (as a base case). Moreover, the existence both `make_directory/1` and `make_directory_path/1` means that the user can choose one of the other depending if N exception is wanted or not when the directory already exists.

**Comment by pmoura** [comment]
All `os` library tests pass now. Thanks for adding this built-in predicate.
