### ISSUE TITLE
Compilation error #2

### ISSUE THREAD

**Issue by triska** [infradig/trealla#2]
When I comment out the line indicated in #1, compilation proceeds as follows:

<pre>
<b>$ make</b>
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3-dirty"' -O3  -Wall -D_GNU_SOURCE   -c -o runtime.o runtime.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3-dirty"' -O3  -Wall -D_GNU_SOURCE   -c -o skiplist.o skiplist.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3-dirty"' -O3  -Wall -D_GNU_SOURCE   -c -o base64.o base64.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3-dirty"' -O3  -Wall -D_GNU_SOURCE   -c -o network.o network.c
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.3-dirty"' -O3  -Wall -D_GNU_SOURCE   -c -o utf8.o utf8.c
ld -r -b binary -o lists.o library/lists.pro
<b>ld: warning: option -b is obsolete and being ignored
ld: file not found: binary
make: *** [GNUmakefile:70: lists.o] Error 1</b>
</pre>

**Comment by infradig** [comment]
Should be using the BSDmakefile on OS/X?

**Comment by triska** [comment]
With the BSDmakefile, I get:

<pre>
<b>$ make -f BSDmakefile</b>
BSDmakefile:5: *** missing separator.  Stop.
</pre>

**Comment by infradig** [comment]
You must be using GNU make on OSX? That is an option with FreeBSD but I don't go there, the default is the standrd BSD version. If so, it would indeed need the GNUmakefile for syntax, but the 'ld' command should probably be as per the BSDmakefile.

**Comment by infradig** [comment]
Added OSXmakefile, it's basically GNUmakefile but with '-b binary' removed. I can't do this on Linux (or FREEBSD).

**Comment by triska** [comment]
With `OSXmakefile`, I get:

<pre>
<b>$ make -f OSXmakefile</b>
cc -Isrc -I/usr/local/include -DUSE_OPENSSL=1 -DVERSION='"v1.2.5-dirty"' -O3  -Wall -D_GNU_SOURCE   -c -o runtime.o runtime.c
ld -r -o lists.o library/lists.pro
ld: warning: -arch not specified
ld: warning: ignoring file library/lists.pro, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x6C 0x69 0x73 0x74 0x73 0x2C ) which is not the architecture being linked (x86_64): library/lists.pro
ld -r -o dict.o library/dict.pro
ld: warning: -arch not specified
ld: warning: ignoring file library/dict.pro, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x64 0x69 0x63 0x74 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/dict.pro
ld -r -o apply.o library/apply.pro
ld: warning: -arch not specified
ld: warning: ignoring file library/apply.pro, file was built for unsupported file format ( 0x6D 0x61 0x70 0x6C 0x69 0x73 0x74 0x28 0x5F 0x2C 0x20 0x5B 0x5D 0x29 0x2E 0x0A ) which is not the architecture being linked (x86_64): library/apply.pro
ld -r -o http.o library/http.pro
ld: warning: -arch not specified
ld: warning: ignoring file library/http.pro, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x68 0x74 0x74 0x70 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/http.pro
ld -r -o auth.o library/auth.pro
ld: warning: -arch not specified
ld: warning: ignoring file library/auth.pro, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x61 0x75 0x74 0x68 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/auth.pro
ld -r -o atts.o library/atts.pro
ld: warning: -arch not specified
ld: warning: ignoring file library/atts.pro, file was built for unsupported file format ( 0x3A 0x2D 0x20 0x6D 0x6F 0x64 0x75 0x6C 0x65 0x28 0x61 0x74 0x74 0x73 0x2C 0x20 ) which is not the architecture being linked (x86_64): library/atts.pro
cc -o tpl tpl.o history.o builtins.o library.o parse.o print.o runtime.o skiplist.o base64.o network.o utf8.o lists.o dict.o apply.o http.o auth.o atts.o  -L/usr/local/lib -lm -lssl -lcrypto
Undefined symbols for architecture x86_64:
  "__binary_library_apply_pro_end", referenced from:
      _g_libs in library.o
  "__binary_library_apply_pro_start", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pro_end", referenced from:
      _g_libs in library.o
  "__binary_library_atts_pro_start", referenced from:
      _g_libs in library.o
  "__binary_library_auth_pro_end", referenced from:
      _g_libs in library.o
  "__binary_library_auth_pro_start", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pro_end", referenced from:
      _g_libs in library.o
  "__binary_library_dict_pro_start", referenced from:
      _g_libs in library.o
  "__binary_library_http_pro_end", referenced from:
      _g_libs in library.o
  "__binary_library_http_pro_start", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pro_end", referenced from:
      _g_libs in library.o
  "__binary_library_lists_pro_start", referenced from:
      _g_libs in library.o
<b>ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [OSXmakefile:20: tpl] Error 1</b>
</pre>

**Comment by triska** [comment]
Perfect, it works now, thank you a lot!
