### ISSUE TITLE
absolute_file_name/3 bug when using both expand/1 and relative_to/1 options

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#203]
```text
$ tpl
Trealla Prolog (c) Infradig 2020, v1.8.66
?- absolute_file_name('$LOGTALKUSER/tests/logtalk/directives/include_1/sub', Path, [expand(true)]).
Path = '/Users/pmoura/logtalk/tests/logtalk/directives/include_1/tests/logtalk/directives/include_1/sub'.
?-  working_directory(Current, Current), absolute_file_name('$LOGTALKUSER/tests/logtalk/directives/include_1/sub', Path, [expand(true), relative_to(Current)]).
Current = "/Users/pmoura/logtalk/tests/logtalk/directives/include_1/",
Path = '/Users/pmoura/logtalk/tests/logtalk/directives/include_1/tests/logtalk/directives/include_1/sub'.
```

The `relative_to/1` should only apply if processing the `expand/1 ` doesn't result in an absolute path. This doesn't seem to be the case above, resulting in a non-existing path.

**Comment by pmoura** [comment]
P.S. This bug breaks running the `logtalk3/tests/logtalk/directives/include_1` tests.

**Comment by infradig** [comment]
I don't think absolute_file_name/3 is working as intended anyway...

:~/trealla$ pwd
/home/andrew/trealla
:~/trealla$ echo $LOGTALKUSER
/home/andrew/lgt3git
:~/trealla$ tpl
Trealla Prolog (c) Infradig 2020, v1.8.66-1-g8cb6f
?-
absolute_file_name('$LOGTALKUSER/tests/logtalk/directives/include_1/sub',
Path, [expand(true)]).
Path = '/home/andrew/trealla/tests/logtalk/directives/include_1/sub'.
?-
:~/trealla$

**Comment by pmoura** [comment]
Thanks for the fix. We now get the expected result:

```text
✔ ~/logtalk/tests/logtalk/directives/include_1 
09:50 $ tpl
Trealla Prolog (c) Infradig 2020, v1.8.66-3-gc4128
?- working_directory(Current, Current), absolute_file_name('$LOGTALKUSER/tests/logtalk/directives/include_1/sub', Path, [expand(true), relative_to(Current)]).
Current = "/Users/pmoura/logtalk/tests/logtalk/directives/include_1/",
Path = '/Users/pmoura/logtalk/tests/logtalk/directives/include_1/sub'.
```
