### ISSUE TITLE
writing anonymous variable instead of atom

### ISSUE THREAD

**Issue by josd** [infradig/trealla#205]
Given the following prolog code:
```
$ cat graph.pl
% Traversing graph paths

oneway(paris, orleans).
oneway(paris, chartres).
oneway(paris, amiens).
oneway(orleans, blois).
oneway(orleans, bourges).
oneway(blois, tours).
oneway(chartres, lemans).
oneway(lemans, angers).
oneway(lemans, tours).
oneway(angers, nantes).

path(A, B) :-
    oneway(A, B).
path(A, C) :-
    oneway(A, B),
    path(B, C).
```
we get
```
$ tpl -g "path(X, nantes), write(X), nl, fail; halt" graph.pl
angers
paris
_0
_0
```
whereas we would expect
```
$ scryer-prolog -g "path(X, nantes), write(X), nl, fail; halt" graph.pl
angers
paris
chartres
lemans
```

**Comment by infradig** [comment]
Interesting:

~/trealla$ tpl -O0 -g "path(X, nantes), write(X), nl, fail; halt" graph.pl
angers
paris
chartres
lemans


works. I'll look into it.

**Comment by infradig** [comment]
And this works:

$ tpl -g "findall(X, path(X, nantes), L), write(L), nl, halt" graph.pl
[angers,paris,chartres,lemans]

**Comment by infradig** [comment]
Interesting, if you put:

test :- path(X, nantes), write(X), nl, fail; halt.
:- initialization(test).


in the graph.pl file it also works.

**Comment by infradig** [comment]
This also works with the original graph.pl file:


~/trealla$ tpl -g "call((path(X, nantes), write(X), nl, fail)); halt"
graph.pl


This is not a surprise, I expected it as it's basically what an
initialization directive does,

**Comment by josd** [comment]
remarkable ;-)
also
```
$ tpl -g "call(path(X, nantes)), write(X), nl, fail; halt" graph.pl
angers
paris
chartres
lemans
```
works fine

**Comment by infradig** [comment]
I think I'm going to cheat and just wrap the top-level query in a call.

**Comment by josd** [comment]
Now it works fine :-)
Thank you very much!
