### ISSUE TITLE
More efficient implementation of atom_chars/2

### ISSUE THREAD

**Issue by triska** [infradig/trealla#211]
An ideal implementation of `atom_chars/2` works in *O(1)* when the first argument is instantiated.

This is possible if atom names are internally represented in the same way as strings (lists of characters), because then we can simply make the string point to the address of the atom name in memory.

For example, in:

<pre>
atom_chars(hello, Cs)
</pre>

The atom name of `hello` could internally be represented as a sequence of raw&nbsp;bytes, with the same internal representation as lists of characters in such a way that `0`-bytes can also be included. Then, `Cs` could simply point to the same sequence of bytes, and be tagged as a string.

A very efficient implementation of `atom_chars/2` would strongly favour the usage of `chars` (over `codes`) in commits such as 0a08d286e7c8ce12481f46de7ae15b28d2a91620.

**Comment by infradig** [comment]
I agree absolutely. It was part of the evolution to use slices for things
like this and just flip flags on pointers, but just haven't completed the
work yet.

**Comment by infradig** [comment]
master:

~/trealla$ time tpl -g "between(1,100000000,_), atom_chars('the quick brown
fox jumped over the lazy dog', Cs), fail; halt."

real 0m13.739s
user 0m13.735s
sys 0m0.005s

devel:

:~/trealla$ time tpl -g "between(1,100000000,_), atom_chars('the quick
brown fox jumped over the lazy dog', Cs), fail; halt."

real 0m11.454s
user 0m11.439s
sys 0m0.000s

So a quite significant saving.

**Comment by josd** [comment]
Indeed and very impressive!
Here I get for devel
```
$ time tpl -g "between(1,100000000,_), atom_chars('the quick brown fox jumped over the lazy dog', Cs), fail; halt."

real    0m6.126s
user    0m6.126s
sys     0m0.000s
```
compared to
```
$ time swipl -g "between(1,100000000,_), atom_chars('the quick brown fox jumped over the lazy dog', Cs), fail; halt."

real    0m19.274s
user    0m19.274s
sys     0m0.000s
```
and
```
$ time scryer-prolog -g "use_module(library(between)), between(1,100000000,_), atom_chars('the quick brown fox jumped
over the lazy dog', Cs), fail; halt."
^Cuse_module(library(between)),between(1,100000000,_783),atom_chars(the quick brown fox jumped over the lazy dog,_790),fail;halt causes: error($interrupt_thrown,repl)
?-

real    65m3.606s
user    64m50.585s
sys     0m2.370s
```
which was not yet finished after more than 1 hour ...

**Comment by infradig** [comment]
The power of packed chars-lists. Thanks Markus for that. BTW I just put up
a slight fix for that update.

**Comment by triska** [comment]
Awesome, thank you a lot!

What's especially notable now is the extreme efficiency advantage of `atom_chars/2` over `atom_codes/2`.

For example, with **`atom_chars/2`**

<pre>
<b>$ time ./tpl -g "between(1,100000000,_), atom_chars('the quick brown fox jumped over the lazy dog', Cs), fail; halt."</b>

real	0m10.111s
user	0m9.192s
sys	0m0.132s

</pre>

whereas for `atom_codes/2`, we get:

<pre>
<b>$ time ./tpl -g "between(1,100000000,_), atom_codes('the quick brown fox jumped over the lazy dog', Cs), fail; halt."</b>

real	1m56.671s
user	1m39.774s
sys	0m1.464s
</pre>

In this light, `atom_chars/2` is strongly preferable, in addition to yielding more readable results.

Next, I wanted to test whether `atom_chars/2` now works in *O(1)* if the first argument is instantiated, so I tried the following:

<pre>
$ for i in `seq 1 10`; do echo $i; time ./tpl -g "L is 2^$i, findall(a, between(1,L,_), As), atom_chars(A, As), between(1,100000000,_), atom_chars(A, Cs), fail; halt."; done
</pre>

This runs `atom_chars/2` with atoms of length 2<sup>1</sup>, 2<sup>2</sup>, ..., 2<sup>10</sup>. I noticed an unexpectedly high variation in run-times, since the query sometimes runs twice as fast even though the atom names are longer:

<pre>
1

real	0m16.480s
user	0m16.461s
sys	0m0.008s
2

<b>real	0m17.120s
user	0m16.557s
sys	0m0.034s</b>
3

real	0m16.941s
user	0m16.830s
sys	0m0.036s
4

real	0m9.359s
user	0m9.204s
sys	0m0.093s
5

real	0m9.247s
user	0m9.099s
sys	0m0.086s
6

real	0m9.242s
user	0m9.089s
sys	0m0.091s
7

real	0m9.266s
user	0m9.097s
sys	0m0.077s
8

<b>real	0m9.191s
user	0m9.091s
sys	0m0.060s</b>
9

real	0m9.424s
user	0m9.334s
sys	0m0.060s
10

real	0m9.202s
user	0m9.094s
sys	0m0.067s
</pre>

In the above run (timings vary!), notice for example the huge difference between 2<sup>2</sup> and 2<sup>8</sup>, i.e., the atom `aaaa` and `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`.

I get this on OSX 10.14.2 with the latest version of Trealla. Can you reproduce this difference?

**Comment by infradig** [comment]
Ironically yes, longer atoms truly are faster than short because short
atoms are stored in the cell and must be copied (as before) to make a
string. Longer atoms can just flip a bit!

**Comment by triska** [comment]
Perfect, I'm closing this issue, thank you a lot!

I hope this improvement makes `atom_chars/2` more attractive in the sample programs that ship with Trealla&nbsp;Prolog.
