### ISSUE TITLE
backtracking gives anonymous variable answers for graph traversal example

### ISSUE THREAD

**Issue by josd** [infradig/trealla#219]
Using the latest v1.10.0 (both master and devel) to run https://github.com/josd/eye/blob/master/two/graph.pl
we get
```
$ tpl -g test graph.pl
path(angers,nantes).
path(paris,nantes).
_1.
_1.
```
instead of
```
$ scryer-prolog -g test graph.pl
path(angers,nantes).
path(paris,nantes).
path(chartres,nantes).
path(lemans,nantes).
```

**Comment by infradig** [comment]
And yet...

:~/trealla$ tpl -g test graph.pl
path(angers,nantes).
path(paris,nantes).
_1.
_1.
:~/trealla$ tpl -g "call(test)" graph.pl
path(angers,nantes).
path(paris,nantes).
path(chartres,nantes).
path(lemans,nantes).
:~/trealla$

**Comment by josd** [comment]
Thank you so much Andrew, it now works perfectly!
