### ISSUE TITLE
exception when using between/3

### ISSUE THREAD

**Issue by josd** [infradig/trealla#223]
The following code
```
$ cat sample.pl
:- use_module(library(between)).
:- use_module(library(format)).

main :-
    (   between(0,9,I),
        J is I+1,
        format("type(X,class(n~d)) :- type(X,class(n~d)).~n",[J,I]),
        format("type(X,class(i~d)) :- type(X,class(n~d)).~n",[J,I]),
        format("type(X,class(j~d)) :- type(X,class(n~d)).~n",[J,I]),
        fail
    ;   true
    ),
    halt.
```
gives
```
$ tpl -g main sample.pl
type(X,class(n1)) :- type(X,class(n0)).
type(X,class(i1)) :- type(X,class(n0)).
type(X,class(j1)) :- type(X,class(n0)).
uncaught exception: error(type_error(chars,format:[t,y,p,e,'(','X',',',c,l,a,s,s,'(',j,'1',')',')',' ',:,-,' ',t,y,p,e,'(','X',',',c,l,a,s,s,'(',n,'0',')',')','.',newline]),'$put_chars'/2)
```
whereas we expect
```
type(X,class(n1)) :- type(X,class(n0)).
type(X,class(i1)) :- type(X,class(n0)).
type(X,class(j1)) :- type(X,class(n0)).
type(X,class(n2)) :- type(X,class(n1)).
type(X,class(i2)) :- type(X,class(n1)).
type(X,class(j2)) :- type(X,class(n1)).
type(X,class(n3)) :- type(X,class(n2)).
type(X,class(i3)) :- type(X,class(n2)).
type(X,class(j3)) :- type(X,class(n2)).
type(X,class(n4)) :- type(X,class(n3)).
type(X,class(i4)) :- type(X,class(n3)).
type(X,class(j4)) :- type(X,class(n3)).
type(X,class(n5)) :- type(X,class(n4)).
type(X,class(i5)) :- type(X,class(n4)).
type(X,class(j5)) :- type(X,class(n4)).
type(X,class(n6)) :- type(X,class(n5)).
type(X,class(i6)) :- type(X,class(n5)).
type(X,class(j6)) :- type(X,class(n5)).
type(X,class(n7)) :- type(X,class(n6)).
type(X,class(i7)) :- type(X,class(n6)).
type(X,class(j7)) :- type(X,class(n6)).
type(X,class(n8)) :- type(X,class(n7)).
type(X,class(i8)) :- type(X,class(n7)).
type(X,class(j8)) :- type(X,class(n7)).
type(X,class(n9)) :- type(X,class(n8)).
type(X,class(i9)) :- type(X,class(n8)).
type(X,class(j9)) :- type(X,class(n8)).
type(X,class(n10)) :- type(X,class(n9)).
type(X,class(i10)) :- type(X,class(n9)).
type(X,class(j10)) :- type(X,class(n9)).
```
So the first iteration of between works fine, the second gives an error.

**Comment by infradig** [comment]
Interesting, you have to go back to 1.7.N for it to work.

In the meantime use legacy_format instead of format.

**Comment by josd** [comment]
this works better and gives
```
type(X,class(n1)) :- type(X,class(n0)).
type(X,class(i1)) :- type(X,class(n0)).
type(X,class(j1)) :- type(X,class(n0)).
type(X,class(n2)) :- type(X,class(n1)).
type(X,class(i2)) :- type(X,class(n1)).
type(X,class(j2)) :- type(X,class(n1)).
type(X,class(n3)) :- type(X,class(n2)).
type(X,class(i3)) :- type(X,class(n2)).
type(X,class(j3)) :- type(X,class(n2)).
type(X,class(n4)) :- type(X,class(n3)).
type(X,class(i4)) :- type(X,class(n3)).
type(X,class(j4)) :- type(X,class(n3)).
type(X,class(n5)) :- type(X,class(n4)).
type(X,class(i5)) :- type(X,class(n4)).
type(X,class(j5)) :- type(X,class(n4)).
type(X,class(n6)) :- type(X,class(n5)).
type(X,class(i6)) :- type(X,class(n5)).
type(X,class(j6)) :- type(X,class(n5)).
type(X,class(n7)) :- type(X,class(n6)).
type(X,class(i7)) :- type(X,class(n6)).
type(X,class(j7)) :- type(X,class(n6)).
type(X,class(n8)) :- type(X,class(n7)).
type(X,class(i8)) :- type(X,class(n7)).
type(X,class(j8)) :- type(X,class(n7)).
type(X,class(n9)) :- type(X,class(n8)).
type(X,class(i9)) :- type(X,class(n8)).
type(X,class(j9)) :- type(X,class(n8)).
type(X,class(n.10)) :- type(X,class(n9)).
type(X,class(i.10)) :- type(X,class(n9)).
type(X,class(j.10)) :- type(X,class(n9)).
```
but the the `.` in `type(X,class(n.10))`, `type(X,class(i.10))` and `type(X,class(j.10))`
is not expected

**Comment by infradig** [comment]
Yeah, fixing that as well!

**Comment by josd** [comment]
using `~w` instead of `~d` works fine

**Comment by infradig** [comment]
It was this change I added to format.pl

     ~Nc   use the next argument here, which must be character code   % AD
Mar 11, 2021

**Comment by josd** [comment]
so https://github.com/infradig/trealla/commit/d9aa0ce067dcdba67f887e8b7887815f4ce4d031#diff-9f16bec1cb0e1b9f2c78cf6d117857d92a3537e682efe2461889d1b0b8228037

**Comment by infradig** [comment]
Yes. That change was to fix a couple of errors in Logtalk tests.

**Comment by infradig** [comment]
| using ~w instead of ~d works fine

Not for me.

**Comment by infradig** [comment]
| using ~w instead of ~d works fine

Oh, you meant with legacy_format. Sorry.

**Comment by josd** [comment]
indeed, for legacy_format/3

**Comment by infradig** [comment]
I am reverting the change to format.pl  to add ~c & ~Nc (which will make
Markus happy, Paulo not so much). It will require some work to figure out.

**Comment by josd** [comment]
Now it works and running https://github.com/josd/eye/blob/f612fea44604f424ac65cf805cc9f3a9f27a5016/two/tmp/gendt.pl
gives https://github.com/josd/eye/blob/f612fea44604f424ac65cf805cc9f3a9f27a5016/two/tmp/dt.pl
but takes 
```
$ t tpl -g main gendt.pl
sec=2.170 kB=9108 cpu=99%
```
whereas using the legacy_format https://github.com/josd/eye/blob/f700454079aa48d1866a08bdff803e999c70c013/two/tmp/gendt.pl
takes about 10 msec

**Comment by pmoura** [comment]
Given that `sample.pl` doesn't use either `~c` or `~Nc`, isn't the code exposing a **backtracking** bug in the implementation of the `format/2-3` predicates?

There's  a de facto standard spec for the `format/2-3` predicates. New Prolog systems like Trealla are free to choose to comply with it or diverge from it. That's all there's to it. It's up to both users and implementers to decide how much they care for standards.

**Comment by infradig** [comment]
Yes, format//2 is slow.

**Comment by infradig** [comment]
It's just temporary.

**Comment by infradig** [comment]
Also, I haven't ruled out reverting back to using legacy_format as the
default, purely on speed grounds (as Jos points out). I think it needs work
on tabing though.

**Comment by infradig** [comment]
Also, I don't have time to debug format.pl now.

**Comment by infradig** [comment]
Ok, format/[1-3] now uses the Trealla built-in legacy format code. You
don't need to include a 'use_module(library(format))' directive unless you
want to use format_//[2,3] which has reverted to Markus' original version.

**Comment by pmoura** [comment]
These changes introduced a bug in the `findall/4` predicate:

```text
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.10.8
?- findall(X, (X=1;X=2;X=3), L, [4,5]).
uncaught exception: error(existence_error(procedure,append(_18,'$findall'(_18,(_18=1;_18=2;_18=3),[1,2,3]),[1,2,3])),append/3)
false.
```

**Comment by infradig** [comment]
Also, tests/prolog/predicates/write_term_3 crashes, for no good reason I
can see.

**Comment by pmoura** [comment]
Btw, an easy to fix compilation warning:

```text
cc -Isrc -I/usr/local/include -DVERSION='"v1.10.9"' -O3  -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations   -c -o src/predicates.o src/predicates.c
src/predicates.c:8829:18: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
                } else if ((ch == 's')) {
                            ~~~^~~~~~
src/predicates.c:8829:18: note: remove extraneous parentheses around the comparison to silence this warning
                } else if ((ch == 's')) {
                           ~   ^     ~
src/predicates.c:8829:18: note: use '=' to turn this equality comparison into an assignment
                } else if ((ch == 's')) {
                               ^~
                               =
1 warning generated.
```

**Comment by pmoura** [comment]
By switching the Logtalk adapter file to use Trealla's native `format/2-3` predicates, I don't get a crash running the `write_term/3` tests but I do get an odd test failure:

```text
!     lgt_write_term_3_25: failure (in 0.0014220000000000343 seconds)
!       test assertion failed: 'A'=='\'\''
!       in file /Users/pmoura/logtalk/tests/prolog/predicates/write_term_3/tests.lgt between lines 142-148
```

I.e. we get `''` instead of `A`. The test is:

```logtalk
test(lgt_write_term_3_25, true(Assertion)) :-
	^^set_text_output(''),
	current_output(S),
	{write_term(S, 'A', [quoted(false)])},
	^^text_output_assertion('A', Assertion).
```

However:

```text
?- tests::run(lgt_write_term_3_25).
% lgt_write_term_3_25: success (in 0.0024879999999999998 seconds)
% 
% 1 tests: 0 skipped, 1 passed, 0 failed (0 flaky)
% completed tests from object tests
% 
% no code coverage information collected

?- current_output(S), write_term(S, 'A', [quoted(false)]), nl.
A
S = 1.

?- current_output(S), write_term(S, 'A', [quoted(true)]), nl.
'A'
S = 1.
```

This may actually be one of these bugs that require a non-trivial context to be triggered.

**Comment by pmoura** [comment]
Switching Logtalk to the native `format/2-3` predicates and running all Logtalk distribution tests show:

``text
% 518 test sets: 433 completed, 80 skipped, 0 broken, 2 timedout, 3 crashed
% 6831 tests: 108 skipped, 5973 passed, 750 failed (0 flaky)
```

There are less 6 failed tests and less 5 crashed tests. But most likely these reductions are due to less complex code being run then any bug in Markus `format` library. Total time to run all the tests is also noticeably smaller.

**Comment by infradig** [comment]
Yes, any problem with format.pl was due to my mods and I'm  glad to remove
them.

**Comment by infradig** [comment]
> Now it works and running https://github.com/josd/eye/blob/f612fea44604f424ac65cf805cc9f3a9f27a5016/two/tmp/gendt.pl
> gives https://github.com/josd/eye/blob/f612fea44604f424ac65cf805cc9f3a9f27a5016/two/tmp/dt.pl
> but takes
> 
> ```
> $ t tpl -g main gendt.pl
> sec=2.170 kB=9108 cpu=99%
> ```
> 
> whereas using the legacy_format https://github.com/josd/eye/blob/f700454079aa48d1866a08bdff803e999c70c013/two/tmp/gendt.pl
> takes about 10 msec

Now, with library(format) removed, you should be seeing 5ms 😀

**Comment by josd** [comment]
Yes indeed, well actually 20ms here, but it is impressive! Thanks 😀

**Comment by josd** [comment]
FYI after adding
```
:- use_module(library(between)).
:- use_module(library(format)).
```
to https://github.com/josd/eye/blob/f9a8edd652c81db9af4193592131b314e5bf8b40/two/gen/gendt.pl
it also works for scryer-prolog
```
$ time scryer-prolog -g main gen/gendt.pl

real    0m59.310s
user    0m59.176s
sys     0m0.090s
```
be it about 2000 times slower.
When implementing reasoning my goal is to be declarative and sub-second and Trealla Works that Out!
