### ISSUE TITLE
Unification

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#231]
```
?- -X=X, acyclic_term(X).
false.                                    % good
?- -X=X, writeq([X]),nl.
[[]]                                      % ?
X = -false.                               % ?
?- s(X)=X, writeq([X]),nl.
[[]]                                      % ?
X = s(false).                             %  ?
?- -X=X,-Y=Y,X=Y.
X = -false,                               % ?
Y = -false.
?- -X=X, writeq([X]),nl,ground(X).
[[]]                                      % ?
X = -false.                               % success unexpected
?- X*X=X, Y*Y=Y, X=Y.
*loops*                                  % ok
```

Strictly speaking, from the moment of the STO-unification on, everything is undefined. Still, one would expect some behavior that  somehow is related to the program. Also, it would be nice if somehow a loop can be interrupted. ^C does not work.

**Comment by infradig** [comment]
The false is because 'false' is the zeroth element in the atom table, and
the X is slot #0, and it's trying to print a variable as an atom (the
variable name X in this case) and getting things wrong. That used to work
and according to git bisect did on May 31st when some string manipulation
changes went in. Something to work on...

**Comment by infradig** [comment]
And it seems to only be an issue when running from the top-level. For
example tests/issues/test031.pl seems to work fine...

:-initialization(main).

main :-
  X = f(X), X == X, writeln(X), halt.

**Comment by UWN** [comment]
And what about ground/1 succeeding, when there is no variable left?

**Comment by infradig** [comment]
Yes, a few things to look at. Thanks for pointing  this out.

**Comment by UWN** [comment]
As for printing variable names consider the [write option variable_names/1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names) for rapid inclusion. With it a lot of quirks in printing variable names can be omitted. You seem to have the read option already.

**Comment by pmoura** [comment]
The `write_term/3` predicate option `variable_names/1` is implemented and passes all tests bundled with the Logtalk distribution. However, there's seems to be an odd top-level issue that makes it look like the option is accepted but not implemented:

```text
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.10.20-1-g8a355
?- current_output(S), write_term(S, foo(A,B,C), [variable_names(['X'=A,'Y'=B,'Z'=C])]), nl.
foo(_1,_2,_3)
S = 1.
?- [user].
p :- current_output(S), write_term(S, foo(A,B,C), [variable_names(['X'=A,'Y'=B,'Z'=C])]), nl.
true.
?- p.
foo(X,Y,Z)
true.
```

**Comment by UWN** [comment]
Good point, but I stopped at [#1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#1):
```
?- write_term(T,[quoted(true),
 variable_names([N=T])]).
uncaught exception: error(domain_error(write_option,variable_names([_8=_9])),write_term/2)
true.
```

**Comment by pmoura** [comment]
The argument of the `variable_names/1` is malformed (typo?) and thus the domain error is expected:

```text
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.10.20-1-g8a355
?- write_term(T,[quoted(true), variable_names([N=T])]), nl.
uncaught exception: error(domain_error(write_option,variable_names([_8=_9])),write_term/2)
false.
?- write_term(T,[quoted(true), variable_names(['N'=T])]), nl.
_0
true.
```

**Comment by infradig** [comment]
I have to rework the top-level, it's not in Prolog unfortunately.

**Comment by UWN** [comment]
The standard requires in [#1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#1) an instantiation error. This can be easily seen from  [#2](www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#2) where an additional substitution is added in front of the query and thus resulting in a valid option.

This is a classical situation for an instantiation error see 7.12.2. Even SWI is conforming. I have not checked the other systems recently, but I assume they did not change. In above link there is also a link to Cor.3.

**Comment by pmoura** [comment]
The Logtalk bundled tests for this option expect an instantiation error but currently also accept a domain error:

https://github.com/LogtalkDotOrg/logtalk3/blob/master/tests/prolog/predicates/write_term_3/tests.lgt

As more systems are updated for Corrigenda 3, the tests will likely be updated at some point to only expect/accept the instantiation error.

**Comment by UWN** [comment]
Now:

```
Trealla Prolog (c) Infradig 2020-2021, v1.13.62
?- -X=X, writeq([X]),nl.
[[]]
X = - (null).     % unexpected
```

**Comment by josd** [comment]
Now it gives
```
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.13.63
?- -X=X, writeq([X]),nl.
[_4]
X = - X.    % expected
```

**Comment by infradig** [comment]
Ok, I see what you mean...

$ tpl
?- X = -X, writeq(X), nl, writeq([X]), nl.
- _4
[_4]
X = - X.
?-

**Comment by UWN** [comment]
Just a reminder:

```
ulrich@TU-Wien:/opt/gupu/trealla$ ./tpl -f
Trealla Prolog (c) Infradig 2020-2021, v1.18.28
?- X*X=X, Y*Y=Y, X=Y, false.
Segmentation fault (core dumped)
```

**Comment by UWN** [comment]
In any case concerning [priorities](https://github.com/infradig/trealla/issues/300#issuecomment-997182155) this needs to be fixed prior to further advances in `dif/2`.

**Comment by infradig** [comment]
I thought it was.

**Comment by UWN** [comment]
```
Trealla Prolog (c) Infradig 2020-2021, v1.18.31
?- X*X=X, Y*Y=Y, X=Y, false.
   false.
```
Now it is.

**Comment by UWN** [comment]
Closing this, because the other issues are too much spread in between.

**Comment by infradig** [comment]
May have been a few days ago, and I might not have mentioned the issue # in
the commit.
