### ISSUE TITLE
discontiguous predicate not identified

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#238]
$ cat d.pl
q :- write(d1), p.
p :- write(d2).
p :- write(d3).
y.
p :- write(d4).

$ trealla/tpl -l d.pl
Trealla Prolog (c) Infradig 2020-2021, v1.10.37
?- q,false.
d1d2d3d4false. % unexpected
?-

$ gprolog  --consult-file d.pl
d.pl:5: warning: discontiguous predicate p/0 - clause ignored
| ?- q,false.
d1d2d3
no
| ?-

$ scryer-prolog d.pl
Warning: overwriting p/0
?- q,false.
d1d4false.
?-

@iso ?
gprolog  p:d2,d3
scryer p:d4

**Comment by pmoura** [comment]
As per the ISO Prolog standard, any discontiguous predicate must be declared using the `discontiguous/1` directive. When this directive is not present, IIRC, behavior is up the Prolog system.

**Comment by flexoron** [comment]
ok, thank you....then it is not an issue.

**Comment by flexoron** [comment]
so trealla doesn't care und directive discontiguous is useless?

**Comment by infradig** [comment]
It should care, and discontinuous predicate is not necessary  in Trealla
but recommended for portability.

**Comment by flexoron** [comment]
so it is not possible to control this feature (switch on/off if it ever makes sense).
multifile:
d.pl % switch on discontiguous
e.pl %  switch off
f.pl % switch on

**Comment by flexoron** [comment]
@iso (pmoura) ... behavior is up to the Prolog system
why?

**Comment by infradig** [comment]
No, you can use modules to achieve true localisation.

**Comment by pmoura** [comment]
> so it is not possible to control this feature in trealla (switch on/off if it ever makes sense).
> multifile:
> d.pl % switch on discontiguous
> e.pl % switch off
> f.pl % switch on

Not sure I follow. But if you're defining clauses for the same predicate in multiple files, then each file must have a `multifile/1` directive for that predicate (as per ISO standard). That's orthogonal to the predicate clauses being  discontiguous.

**Comment by pmoura** [comment]
> @iso (pmoura) ... behavior is up to the Prolog system
> why?

IIRC, the ISO standard doesn't specify the expected behavior for a Prolog system when a predicate have discontiguous clauses but not `discontiguous/1` directive is present for the predicate.

**Comment by infradig** [comment]
Trealla doesn't  implement (that is, ignores) the multifile directive,
maybe that's a problem.

**Comment by pmoura** [comment]
> Trealla doesn't implement (that is, ignores) the multifile directive, maybe that's a problem.
> […](#)

Logtalk uses several multifile directives **and** runs on Trealla. Thus, at least on the case of Logtalk, the handling of the multifile directive by Trealla is not causing issues as far as I can tell.

**Comment by flexoron** [comment]
ok,
thank you infradig, pmoura.
at the moment I investigate scryers discontiguous implementaion and directive multifile as well.
it is clear now how to compare results(trealla,gprolog,scryer),
thnk u.
