### ISSUE TITLE
catch/3 sometimes does not catch errors

### ISSUE THREAD

**Issue by triska** [infradig/trealla#24]
Currently, I get:

<pre>
<b>?- catch(X=f(X), E, true).</b>

Error: max depth exceeded
Error: max depth exceeded
X = f(f(f(f(f(f(f(f(f(f(f(f(...
</pre>

Expected: *Success*, with a binding for `E = ...`, and no binding for `X`.

**Comment by infradig** [comment]
Doesn't do cycle checking yet.

**Comment by triska** [comment]
This works nicely now, thank you a lot!
