### ISSUE TITLE
format/2 missing ~r

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#243]
```
?- format('~r',[8]).
Floating point exception (core dumped)   % expected: 10
```
(as does SICStus and Quintus, also GNU-Prolog)

(for the moment, this is the last issue I am posting, there are currently 10 issues open)

**Comment by infradig** [comment]
Are you saying it should default to octal if no radix specified?

**Comment by UWN** [comment]
Yes, that's what the doc says and [also in older versions](http://www.complang.tuwien.ac.at/sicstus/sicstus_10.html#IDX355) said. Still do not know the very exact source. Prior to 1987 to be sure. It was not in DEC10.
