### ISSUE TITLE
length/2 and call_nth/2

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#246]
```
?- call_nth(length(L, N), M).
L = 1,         % expected L = [], M = 1
N = 0 
; L = 1,
N = 1 
; L = 1,
N = 2 
```

**Comment by UWN** [comment]
`call_nth/2`is central to testing which essentially looks like:

`?- gen(T), badtest(T).`

were `gen(T)` describes an infinite sequence of answers/solutions in a fair manner. And after a couple of months ..it happens (something heinous of information technology). How to reproduce such a case rapidly? Usually, systems do not succeed (which would be nice), but just abort. So some kind of checkpointing is needed. That's where `call_nth/2` comes into play.

Checkpointing is also important, if you do not have control over the systems you are using (you never have), or their power supply. Just think of Condor. After reboot you do not want to rerun everything from scratch. Just from the last checkpoint on:

`?- call_nth(gen(T),Nth), Nth > 123456, badtest(T).`

And it's not only checkpointing but also parallelization. With `N` processors say on the `I`th processor:

`?- I = 377, N = 1024, call_nth(gen(T), Nth), I =:= Nth mod 1024, ...`

There are many [possible implementations](https://stackoverflow.com/a/11400256/772868), ideally a clean implementation would also lead to some stable related built-ins.

**Comment by UWN** [comment]
```
?- _=[M1,M2,N,L],call_nth(( true;true;true;true;call_nth(length(L,N),M2) ), M1).
M1 = 1 
; M1 = 2 
; M1 = 3 
; M1 = 4 
; M1 = 2,        % unexpected. Expected M1 = 5
M2 = 1,
N = 0,
L = [] 
; M1 = 4,
M2 = 3,
N = 1,
L = [_12] 
```


[Reference](https://youtu.be/a8kgAkTS7oM?t=24).

**Comment by UWN** [comment]
Scryer:

```
?- _=[M1,M2,N,L],call_nth(( true;true;true;true;call_nth(length(L,N),M2) ), M1).

   M1 = 1
;  M1 = 2
;  M1 = 3
;  M1 = 4
;  M1 = 5, M2 = 1, N = 0, L = []
;  M1 = 6, M2 = 2, N = 1, L = [_A]
;  M1 = 7, M2 = 3, N = 2, L = [_A,_B]
;  M1 = 8, M2 = 4, N = 3, L = [_A,_B,_C]
;  M1 = 9, M2 = 5, N = 4, L = [_A,_B,_C,_D]
;  M1 = 10, M2 = 6, N = 5, L = [_A,_B,_C,_D,_E]
;  M1 = 11, M2 = 7, N = 6, L = [_A,_B,_C,_D,_E,_F]
;  M1 = 12, M2 = 8, N = 7, L = [_A,_B,_C,_D,_E,_F,_G]
;  M1 = 13, M2 = 9, N = 8, L = [_A,_B,_C,_D,_E,_F,_G,_H]
;  M1 = 14, M2 = 10, N = 9, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I]
;  ...
```

**Comment by UWN** [comment]
And now:

```
ulrich@TU-Wien:/opt/gupu/trealla$ git pull&&make OPT=-std=c99 NOSSL=1&&kill%1;date;git describe;./tpl
Already up to date.
make: Nothing to be done for 'all'.
kill%1: command not found
So Aug 22 09:04:14 CEST 2021
fatal: No annotated tags can describe '44326245132d4fc8934a3ee4054baa33897ba071'.
However, there were unannotated tags: try --tags.
Trealla Prolog (c) Infradig 2020-2021, v1.11.7-4-g44326
?- _=[M1,M2,N,L],call_nth(( true;true;true;true;call_nth(length(L,N),M2) ), M1).
M1 = 1 
; M1 = 2 
; M1 = 3 
; M1 = 4 
; M1 = 6, % unexpected
M2 = 5,
N = 0,
L = [] 
; M1 = 8,
M2 = 7,
N = 1,
L = [_12] 
```

**Comment by UWN** [comment]
Maybe [this one](https://youtu.be/pCmsMCSyeMk?t=20) is clearer.

**Comment by infradig** [comment]
https://youtu.be/JTEFKFiXSx4I like this one

**Comment by UWN** [comment]
Pah, Steinway, what do you expect?

**Comment by infradig** [comment]
I get this...

~/trealla (devel) $ tpl
?- _=[M1,M2,N,L],call_nth(( true;true;true;true;call_nth(length(L,N),M2) ),
M1).
   M1 = 1
;  M1 = 2
;  M1 = 3
;  M1 = 4
;  M1 = 5, M2 = 1, N = 0, L = []
;  M1 = 6, M2 = 2, N = 1, L = [_A]
;  M1 = 7, M2 = 3, N = 2, L = [_A,_B]
;  M1 = 8, M2 = 4, N = 3, L = [_A,_B,_C]
;  M1 = 9, M2 = 5, N = 4, L = [_A,_B,_C,_D]
;  M1 = 10, M2 = 6, N = 5, L = [_A,_B,_C,_D,_E]
;  M1 = 11, M2 = 7, N = 6, L = [_A,_B,_C,_D,_E,_F]
;  ... .
?-
