### ISSUE TITLE
use tags in git

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#248]
```
ulrich@TU-Wien:/opt/gupu/trealla$ git describe
fatal: No annotated tags can describe 'c93fc9b1dae0c8edbbd42ad4ebd635da0275bda3'.
However, there were unannotated tags: try --tags.
```

This could be much more informative like in Scryer:

```
ulrich@TU-Wien:/opt/gupu/scryer-prolog$ git describe
v0.8.123-611-gfce7f8a
         ^^^ pseudo-sequential nr
```

This number is particularly useful, it is kind of time nr. (Yes, we all know that git does not know this) But for simple temporal navigation it is good enough.

**Comment by josd** [comment]
I see that there is an unannotated tag
```
$ git describe --tags
v1.11.9
```
but no annotated tag.
What I typically do in https://github.com/josd/eye/blob/master/mkeye is
```
git tag -a $RELEASE -m "$1"
git push origin $RELEASE
```

**Comment by josd** [comment]
> This number is particularly useful, it is kind of time nr. (Yes, we all know that git does not know this) But for simple temporal navigation it is good enough.

according to https://git-scm.com/docs/git-describe#_examples
that number is he number of additional commits since the
last release tag, so maybe after 611 commits it is time for
a new Scryer release :-)
