### ISSUE TITLE
write_canonical/1 sometimes does not emit the canonical representation

### ISSUE THREAD

**Issue by triska** [infradig/trealla#25]
Currently, I get:

<pre>
<b>?- write_canonical("abc").</b>
"abc"
</pre>

Expected: `'.'(a,'.'(b,'.'(c,[])))`.

**Comment by triska** [comment]
This is now nicely resolved, thank you a lot!

**Comment by infradig** [comment]
It is done inefficiently, but will redo it later at leisure (ha).
