### ISSUE TITLE
Quote characters on writeq-ing

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#252]
Capital letters above ASCII seem to be recognized, but they are not quoted on writing:

```
?- Ö-Œ = s-t.
Ö = s,
Œ = t.            % expected!
?- V= -'Ö'-'Œ'+(.)+'A'.
V = -Ö-Œ+'.'+'A'. % unexpected, expected: V = -'Ö'-'Œ'+'.'+'A'. 
```

**Comment by jacobfriedman** [comment]
How come 
```Ö = s ``` (etc) is expected, even though it's not covered in the spec (or draft spec)? Afaik, it hasn't been discussed openly in any ISO WGs. If you could please link to some test-cases / charsets or discussions where this is covered, I would appreciate it. Thank you!

**Comment by UWN** [comment]
> How come
> `Ö = s ` (etc) is expected, even though it's not covered in the spec (or draft spec)? Afaik, it hasn't been discussed openly in any ISO WGs. If you could please link to some test-cases / charsets or discussions where this is covered, I would appreciate it.

Every ISO Prolog conforming system has an **implementation defined** processor character set *PCS* (6.5) which is defined in the accompanying documentation. Trealla has [some tentative documentation](https://github.com/infradig/trealla#readme) which effectively states that the PCS is utf-8 and that 'Unicode uppercase' is taken into account for variables and some more (more or less clear, I have not looked into these).

Note that I just said PCS is utf-8 and did not mention Unicode. The standard implicitly assumes that the PCS has exactly one encoding. No, nobody thought that this UCS-2 chaos would break out with all the other encodings which followed. After this sorry time of interregnum and incompatibility it seems more and more that UTF-8 is just the way to go and all these extra encodings are a matter of the past. A [link](https://utf8everywhere.org/) in Trealla's documentation suggests that this is the vision for Trealla too.

Nevertheless, currently, Trealla has some anachronistic, obsolete by design, [UCS-2 escapes](https://github.com/infradig/trealla/issues/237#issuecomment-901673888) which unnecessarily complicate the tokenizer. Hopefully these will be removed resulting in a simplified and stable tokenizer. The `\x` escape in ISO not only subsumes these, it is even open to further extensions since there is no limit to the size of the code point.

As for the example characters chosen, I took one capital character already in [Latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) (Ö) and one that was in the predecessor of Latin-1, [DEC-MCS](https://en.wikipedia.org/wiki/Multinational_Character_Set) but which was then removed much to the detriment of many (Œ) and which by itself and the introduction of the Euro-Sign caused another very similar character set to emerge, [Latin 0](https://en.wikipedia.org/wiki/ISO/IEC_8859-15) which in many systems was aliased with Latin-1. Brief, I was very happy to see that these two characters were treated in the same manner in Trealla.

**Comment by jacobfriedman** [comment]
Thank you for the clarification!

Admittedly, I was confusing your expectation *of Trealla* with *ISO*
expectations* of how certain UTF characters could, or, would be handled.

We must give credit to Trealla for paving a way forward, i.e., "way to go"!
This, if not in the WG, is where impactful industry decisions are made.

In future, I would like to see a flagged e.g. location-specific PCS, if
only to give us a contextual use for characters such as ∑.

**Comment by jacobfriedman** [comment]
---

This is off-topic (again) but I don't really know where else to post it,
given all of the discussion on ISO it's probably best to make an ISO prolog
Git repo: the WG could store discussions, tests, etc. It would also serve a
de facto Wiki (over Wikipedia).

The complang site is an excellent resource and would only benefit from
being hosted, and extrapolated upon, GitHub. Any issues could be easily
referenced... The list goes on.

It's something to seriously consider and act upon. I'm not sure if such a
task needs approval, but hopefully I can get enough thumbs up here to
justify the request.

---

**Comment by UWN** [comment]
Perfect, yet...

```
?- char_code(Ch, 0x1E9E).
Ch = 'ẞ'.
```

Vatt? [Tiss lettär](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E) exists? The cost of German reunification exceeds all forecasts.

**Comment by infradig** [comment]
Yes, that would have made my German grandmother happy.
