### ISSUE TITLE
Unidentified =/=

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#254]
```
?- 1 =/= 2.
uncaught exception: error(type_error(callable,1),call/1) % unexpected, what is this? 
false.
?- write_canonical(1=/=2).
1true.                                                   % entirely unexpected
?- current_op(Pri,Fix,=/=).
false.                                                   % why?
?- atom(=/=).
true.
?- write_canonical(=/=).
'=/='true.                                               % why is it quoted?
?- write_canonical(==).
==true.
?- write_canonical(\==).
\==true.
?- write_canonical(=\=).
=\=true.
?- ex_nihilo.
uncaught exception: error(existence_error(procedure,ex_nihilo/0),ex_nihilo/0)
false.
?- ex_nihilo(_).
uncaught exception: error(existence_error(procedure,ex_nihilo/1),ex_nihilo/1)
false.
?- ex_nihilo(_,_).
uncaught exception: error(existence_error(procedure,ex_nihilo/2),ex_nihilo/2)
false.
?- 
```

And these falses are now so glaringly red. They usually are no problem. I am always happy if I get a false on a query which means I have not found an inconsistency.

**Comment by infradig** [comment]
This is the same error as issue #252.

**Comment by infradig** [comment]
And you're right. The red was an experiment and I don't like it either.

**Comment by infradig** [comment]
I meant same as issue #245

**Comment by UWN** [comment]
> This is the same error as issue #252.
> […](#)
> On Mon, Aug 23, 2021 at 3:08 AM UWN ***@***.***> wrote: ?- 1 =/= 2. uncaught exception: error(type_error(callable,1),call/1) % unexpected, what is this?

@infradig,
how can it be the same issue? Or, to put it the other way round: What did Trealla parse in that situation? (Just to understand to help me find "similar" bugs.)
