### ISSUE TITLE
Odd syntax error when proving a goal that doesn't perform any read operation

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#268]
Trying to understand the single test failure for the Logtalk `closed_world_assumption`, I instrumented the code in its `closed_world_assumption.lgt` file:

```logtalk
	fun :-
		{trace},
		pool.
```

We get (with the `{tester}` goal from the example directory:

```text
 [0] EXIT trace
 [1] EXIT '$lgt_debug'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])))
 [2] CALL '$logtalk#0.trace_event#2'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])),_)
 [3] FAIL '$logtalk#0.trace_event#2'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])),_)
 [4] REDO '$lgt_debug'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])))
 [5] EXIT '$lgt_debug'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])))
 [6] CALL '$logtalk#0.debug_handler_provider#1'(_,_)
 [7] FAIL '$logtalk#0.debug_handler_provider#1'(_,_)
 [8] REDO '$lgt_debug'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])))
 [9] EXIT '$lgt_debug'(goal(pool,'$house#0.pool#0'(c(house,house,r(tests,house,[],[])))),c(house,house,r(tests,house,[],[])))
 [10] CALL call('$house#0.pool#0'(c(house,house,r(tests,house,[],[]))))
 [11] EXIT call('$house#0.pool#0'(c(house,house,r(tests,house,[],[]))))
 [12] CALL '$call'('$house#0.pool#0'(c(house,house,r(tests,house,[],[]))))
 [13] EXIT '$call'('$house#0.pool#0'(c(house,house,r(tests,house,[],[]))))
Error: syntax error, near 'house' operator expected ''
 [14] EXIT '$lgtunit#0.check_error#7'(closed_world_assumption_06,[error(existence_error(procedure,_19767),_19768)],error,'/Users/pmoura/Documents/Logtalk/logtalk3/examples/closed_world_assumption/tests.lgt',47-50,1.216422,1,c(lgtunit,lgtunit,r(tests,tests,[],[])))
```

The trace is noisy due to the code being compiled instrumented for collecting code coverage stats. But we can see the odd syntax error (there's no `house` operator defined) and that instead of the expected exception (the `pool/0`predicate is intentionally not defined) term we simply get `error`.

**Comment by infradig** [comment]
Throwing an exception from code involves formatting an exception message
and parsing it back. It should be rewritten sometime to avoid this.

**Comment by infradig** [comment]
This is the formatted exception:

  error(existence_error(procedure,($house#0.pool#0)/1

hence the syntax error. Should be straight-forward...

**Comment by pmoura** [comment]
So the syntax error is also due to the missing quotes in the `'$house#0.pool#0'` atom? Wirth this bug fixed, all tests for the `closed_world_assumption` example should pass.

**Comment by infradig** [comment]
Yes, and they do.

**Comment by pmoura** [comment]
```text
$ logtalk_tester -p trealla
% Batch testing started @ 2021-09-23 00:56:38
%         Logtalk version: 3.51.0-b01
%         Trealla Prolog version: 1.13.42
%
% Documents/Logtalk/logtalk3/examples/closed_world_assumption
%         6 tests: 0 skipped, 6 passed, 0 failed (0 flaky)
%         completed tests from object tests in 2 seconds
%         clause coverage 85.71428571428571%
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 6 tests: 0 skipped, 6 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2021-09-23 00:56:40
```

**Comment by infradig** [comment]
Also fixes 7 tests/logtalk fails. Running the full suite...

**Comment by pmoura** [comment]
Same here. I got what look like a random crash (could not reproduce) with `library/base64`.The total number of failed tests is now 608. But meanwhile I pushed improved test for the standard `call/1-N` predicates and I get a segmentation fault that I think is related to the error formatting fix:

```text
?- {tester}.
% 
% tests started at 2021-09-23, 01:17:42
% 
% running tests from object tests
% file: /Users/pmoura/Documents/Logtalk/logtalk3/tests/prolog/control/call_1/tests.lgt
% 
% iso_call_1_01: success (in 2.799999999991698e-05 seconds)
% iso_call_1_02: success (in 1.099999999998325e-05 seconds)
% iso_call_1_03: success (in 8.999999999925734e-06 seconds)
% iso_call_1_04: success (in 8.000000000008001e-06 seconds)
% iso_call_1_05: success (in 9.999999999998899e-05 seconds)
% iso_call_1_06: success (in 5.900000000003125e-05 seconds)
% iso_call_1_07: success (in 0.0002580000000000915 seconds)
% iso_call_1_08: success (in 0.000199999999999978 seconds)
Segmentation fault: 11
```

Can you do a git pull and see if you can reproduce the crash?

**Comment by infradig** [comment]
No, the crash happens in earlier releases.

**Comment by infradig** [comment]
I get a crash in base64

**Comment by infradig** [comment]
Something about these two:

 test(base64_roundtrip_01, true) :-
this(This),
object_property(This, file(_, Directory)),
os::path_concat(Directory, 'test_files/logtalk.png', Path),
reader::file_to_bytes(Path, Bytes0),
base64::generate(codes(Codes), Bytes0),
base64::parse(codes(Codes), Bytes),
^^assertion(Bytes == Bytes0).

test(base64_roundtrip_02, true) :-
this(This),
object_property(This, file(_, Directory)),
os::path_concat(Directory, 'test_files/dump_base64.txt', Path),
atom_codes('The quick brown fox jumps over the lazy dog.', Bytes0),
base64::generate(file(Path), Bytes0),
base64::parse(file(Path), Bytes),
^^assertion(Bytes == Bytes0).

The second one crashes in situ. Remove it and the first causes a crash at
the end. Remove it and all's well. The crash is a memory corruption of some
sort.

**Comment by infradig** [comment]
Replace the assertions:

 test(base64_roundtrip_01, true) :-
this(This),
object_property(This, file(_, Directory)),
os::path_concat(Directory, 'test_files/logtalk.png', Path),
reader::file_to_bytes(Path, Bytes0),
base64::generate(codes(Codes), Bytes0),
base64::parse(codes(Codes), Bytes),
^^assertion(true == true).

test(base64_roundtrip_02, true) :-
this(This),
object_property(This, file(_, Directory)),
os::path_concat(Directory, 'test_files/dump_base64.txt', Path),
atom_codes('The quick brown fox jumps over the lazy dog.', Bytes0),
base64::generate(file(Path), Bytes0),
base64::parse(file(Path), Bytes),
^^assertion(true == true).

and it works.

**Comment by infradig** [comment]
This works too...

test(base64_roundtrip_01, true) :-
this(This),
object_property(This, file(_, Directory)),
os::path_concat(Directory, 'test_files/logtalk.png', Path),
reader::file_to_bytes(Path, Bytes0),
base64::generate(codes(Codes), Bytes0),
base64::parse(codes(Codes), Bytes),
Bytes == Bytes0,
^^assertion(true).

test(base64_roundtrip_02, true) :-
this(This),
object_property(This, file(_, Directory)),
os::path_concat(Directory, 'test_files/dump_base64.txt', Path),
atom_codes('The quick brown fox jumps over the lazy dog.', Bytes0),
base64::generate(file(Path), Bytes0),
Bytes == Bytes0,
^^assertion(true).

**Comment by infradig** [comment]
Ok, it's a heap corruption somehow. Boost INITIAL_NB_HEAP from 8000 to
16000 fixes it.

**Comment by pmoura** [comment]
Confirmed that the crash in the `logtalk3/tests/prolog/control/call_1` test set no longer occurs with v1.13.44. Same for the `logtalk3/library/base64` test set.

**Comment by pmoura** [comment]
Running all tests:

```text
$ logtalk_tester -p trealla -g "set_logtalk_flag(clean,off)" -w -t 360
% Batch testing started @ 2021-09-23 07:59:47
%         Logtalk version: 3.51.0-b01
%         Trealla Prolog version: 1.13.44
...
% 516 test sets: 436 completed, 79 skipped, 0 broken, 1 timedout, 0 crashed
% 7376 tests: 149 skipped, 6619 passed, 608 failed (2 flaky)
%
% Batch testing ended @ 2021-09-23 08:16:09
```

608 test failures - 2 flaky tests (expected to fail) - 534 non-deterministic success = 72 test failures to look into first. Of these 72 failures, 50 are cases are the wrong error is being thrown. In most of these 50 failures, the issue is in the second argument of the `error/2` term. A good candidate to debug these failures is the `logtalk3/tests/logtalk/predicates/create_category_4` test set. Checking for the expected errors uses the `subsumes_term/2` predicate. I suspect that the process you describe where "throwing an exception from code involves formatting an exception message and parsing it back" introduces new variables that make the subsumes call fail. For example:

```text
!     create_category_4_25: failure (in 0.000124000000000013 seconds)
!       test goal throws the wrong error:
!         expected error(permission_error(complement,self,'$VAR'(0)),logtalk(create_category('$VAR'(1),[complements('$VAR'(1))],[],[]),'$VAR'(2)))
!         but got  error(permission_error(complement,self,c2),logtalk(create_category('$VAR'(3),[complements('$VAR'(4))],[],[]),c(user,user,r(user,user,[],[]))))
!       in file /Users/pmoura/logtalk/tests/logtalk/predicates/create_category_4/tests.lgt between lines 129-133
```

Abstracting the exception terms gives us:

```text
?- subsumes_term(a(A,B,B), a(1,D,E)).
false.
```

while if the variables were preserved we would get:

```text
?- subsumes_term(a(A,B,B), a(1,D,D)).
true.
```

**Comment by infradig** [comment]
Good thinking, and good motivation to rewrite that code.
