### ISSUE TITLE
User-defined functions giving type_error exception

### ISSUE THREAD

**Issue by josd** [infradig/trealla#275]
While running the example in https://github.com/infradig/trealla#user-defined-functions
we get
```
?- F is fac(20).
uncaught exception: error(type_error(evaluable,fac/1),(is)/2)
true.
```
I am looking forward to use user-defined functions in https://sourceforge.net/p/eulersharp/code/HEAD/tree/trunk/2021/est/etc/complex.pl

**Comment by infradig** [comment]
You're right.

**Comment by josd** [comment]
Fine, it now works :-)
I was under the impression that it could work for complex number functions but is/2 is only for reals :-(
