### ISSUE TITLE
Order of command line options is too permissive

### ISSUE THREAD

**Issue by triska** [infradig/trealla#28]
The `README` states:

<pre>
tpl [options] [files]
</pre>

However, it then uses a different order, namely `[files] [options]`, in two examples:

<pre>
./tpl samples/sieve -g test2,halt
./tpl samples/sieve -g test2,halt
</pre>

I think it would be very good to *strictly enforce* that options to `tpl` must appear before any file names. The reason is that in the future, you may want to allow additional options that do not affect `tpl` itself, but are only accessible (for example via `argc`, `argv` flags) and meaningful to the program that is being interpreted. These options could then all be placed *after* the files.

**Comment by infradig** [comment]
Noted,

**Comment by triska** [comment]
Perfect, thank you a lot!
