### ISSUE TITLE
Building Trealla on Android via Termux

### ISSUE THREAD

**Issue by josd** [infradig/trealla#284]
White trying to build Trealla on Android Termux the following error occured
```
~/trealla $ make
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/functions.o src/functions.c
In file included from src/functions.c:12:
src/internal.h:36:19: error: typedef redefinition with different types ('uintmax_t' (aka 'unsigned long') vs 'unsigned int')
typedef uintmax_t uint_t;
                  ^
/data/data/com.termux/files/usr/include/sys/types.h:131:29: note: previous definition is here
typedef unsigned int        uint_t;
                            ^
1 error generated.
make: *** [<builtin>: src/functions.o] Error 1
```
After making the following change 
```
~/trealla $ git diff
diff --git a/src/internal.h b/src/internal.h
index f35dc2368d..2854144ceb 100644
--- a/src/internal.h
+++ b/src/internal.h
@@ -33,7 +33,7 @@
 #endif

 typedef intmax_t int_t;
-typedef uintmax_t uint_t;
+typedef uintmax_t ulong_t;

 #define INT_T_MAX INTMAX_MAX
 #define INT_T_MIN INTMAX_MIN
```
it is building fine and I would  say  that all trealla and retina tests work fine:
```
...
Running tests/issues/test074.pl ...
Running tests/issues/test081.pl ...
2c2
< [[3.000000000000004,2.000000000000001],[5.000000000000005,0.9999999999999927],[-5.773159728050814e-15,1.000000000000003],[0.9999999999999962,1.000000000000004]]
---
> [[3.000000000000004,2.000000000000001],[5.000000000000006,0.9999999999999931],[-6.217248937900877e-15,1.000000000000002],[0.999999999999996,1.000000000000003]]
Running tests/issues/test082.pl ...
Running tests/issues/test088.pl ...
Running tests/issues/test091.pl ...
Running tests/issues/test093.pl ...
Running tests/issues/test094.pl ...
Running tests/issues/test108.pl ...
Running tests/issues/test116.pl ...
Running tests/issues/test132.pl ...
Running tests/issues/test231.pl ...
Running tests/issues/test245.pl ...
Running tests/issues/test246.pl ...
Running tests/issues/test252.pl ...
Running tests/issues/test254.pl ...
Running tests/issues/test271.pl ...

============
TEST SUMMARY
============
Failed: 1
Succeeded: 132
```

```
diff --git a/prolog/tpl.txt b/prolog/tpl.txt
index 77e8618..f9f4295 100644
--- a/prolog/tpl.txt
+++ b/prolog/tpl.txt
@@ -248,7 +248,7 @@ namespace_prefix('etc:','https://josd.github.io/retina/etc/ns#').
 % running polynomial.pl
 namespace_prefix('etc:','https://josd.github.io/retina/etc/ns#').
 'etc:roots'([[1,0],[-10,0],[35,0],[-50,0],[24,0]],[[4.000000007450581,0.0],[2.999999992549419,0.0],[1.999999992549419,0.0],[1.000000007450581,0.0]]).
-'etc:roots'([[1,0],[-9,-5],[14,33],[24,-44],[-26,0]],[[3.000000000000004,2.000000000000001],[5.000000000000005,0.9999999999999927],[-5.773159728050814e-15,1.000000000000003],[0.9999999999999962,1.000000000000004]]).
+'etc:roots'([[1,0],[-9,-5],[14,33],[24,-44],[-26,0]],[[3.000000000000004,2.000000000000001],[5.000000000000006,0.9999999999999931],[-6.217248937900877e-15,1.000000000000002],[0.999999999999996,1.000000000000003]]).

 % running prime.pl
 namespace_prefix('etc:','https://josd.github.io/retina/etc/ns#').
```

**Comment by infradig** [comment]
Ok, i'll look at renaming the types.

**Comment by josd** [comment]
Thanks and it now builds fine with the latest version:

~/trealla $ make
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o tpl.o tpl.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/history.o src/history.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/functions.o src/functions.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/predicates.o src/predicates.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/contrib.o src/contrib.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/control.o src/control.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/library.o src/library.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/module.o src/module.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/parser.o src/parser.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/print.o src/print.c
src/print.c:100:17: warning: variable 'bytes' set but not used [-Wunused-but-set-variable]
        int chars = 0, bytes = 0;
                       ^
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/prolog.o src/prolog.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/query.o src/query.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/format.o src/format.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/skiplist.o src/skiplist.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/base64.o src/base64.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/network.o src/network.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/utf8.o src/utf8.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/imath/imath.o src/imath/imath.c
src/imath/imath.c:1700:51: warning: unused parameter 'osize' [-Wunused-parameter]
static mp_digit *s_realloc(mp_digit *old, mp_size osize, mp_size nsize) {
                                                  ^
1 warning generated.
xxd -i library/builtins.pl library/builtins.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/builtins.o library/builtins.c
xxd -i library/lists.pl library/lists.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/lists.o library/lists.c
xxd -i library/apply.pl library/apply.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/apply.o library/apply.c
xxd -i library/http.pl library/http.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/http.o library/http.c
xxd -i library/atts.pl library/atts.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/atts.o library/atts.c
xxd -i library/error.pl library/error.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/error.o library/error.c
xxd -i library/dcgs.pl library/dcgs.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/dcgs.o library/dcgs.c
xxd -i library/format.pl library/format.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/format.o library/format.c
xxd -i library/charsio.pl library/charsio.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/charsio.o library/charsio.c
xxd -i library/freeze.pl library/freeze.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/freeze.o library/freeze.c
xxd -i library/ordsets.pl library/ordsets.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/ordsets.o library/ordsets.c
xxd -i library/assoc.pl library/assoc.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/assoc.o library/assoc.c
xxd -i library/dict.pl library/dict.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/dict.o library/dict.c
xxd -i library/dif.pl library/dif.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/dif.o library/dif.c
xxd -i library/ugraphs.pl library/ugraphs.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/ugraphs.o library/ugraphs.c
xxd -i library/pairs.pl library/pairs.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/pairs.o library/pairs.c
xxd -i library/random.pl library/random.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/random.o library/random.c
xxd -i library/lambda.pl library/lambda.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o library/lambda.o library/lambda.c
cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1   -c -o src/version.o src/version.c
rm src/version.o                                                                     cc -Isrc -I/usr/local/include -DVERSION='"v1.16.1-8-g3f523"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -DUSE_OPENSSL=1 -o src/version.o -c src/version.c
cc -o tpl tpl.o src/history.o src/functions.o src/predicates.o src/contrib.o src/heap.c src/control.o src/library.o src/module.o src/parser.o src/print.o src/prolog.o src/query.o src/format.o src/skiplist.o src/base64.o src/network.o src/utf8.o src/imath/imath.o library/builtins.o library/lists.o library/apply.o library/http.o library/atts.o library/error.o library/dcgs.o library/format.o library/charsio.o library/freeze.o library/ordsets.o library/assoc.o library/dict.o library/dif.o library/ugraphs.o library/pairs.o library/random.o library/lambda.o src/version.o  -L/usr/local/lib -lreadline -lm -L/usr/local/opt/openssl/lib -lssl -lcrypto
rm library/builtins.c library/atts.c library/error.c library/apply.c library/format.c library/charsio.c library/http.c library/dcgs.c library/freeze.c library/lambda.c library/lists.c library/ugraphs.c library/assoc.c library/ordsets.c library/random.c library/dict.c library/dif.c library/pairs.c

**Comment by josd** [comment]
It now runs fine on Android https://github.com/josd/retina/commit/28645d823965ed0cbcd560b7228b89d77d12df0b#diff-3592c3b3facfd1a3ba97ba80e1fee113cd3160531ae22c13d3085ff3253ccae5

**Comment by infradig** [comment]
Great, thanks for that.

**Comment by josd** [comment]
The new link is actually https://github.com/josd/eye/tree/master/reasoning/prolog
