### ISSUE TITLE
Top level: dif/2 no residual goal

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#292]
```
?- dif(X,X).
false.
?- dif(X,Y), X = Y.
false.
?- dif(X,Y).
true.  % unexpected, expected dif(X,Y)
```

**Comment by infradig** [comment]
Yes, that's still to come.

**Comment by UWN** [comment]
UWN_open

**Comment by infradig** [comment]
There is some rewriting to do in order to handle attvars properly. Your
between/3 case highlighted that. Once that gets done and things are working
better, i'll look at residuals.
