### ISSUE TITLE
Regression in use_module

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#294]
Calling `use_module/1` as a predicate with a full path argument used to work. But now:

```text
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.17.4-13-g0e038
?- use_module('/Users/pmoura/Documents/Prolog/trealla/library/lists.pl').
Error: module file not found: library/../library//Users/pmoura/Documents/Prolog/trealla/library/lists.pl
false.
```

It seems that there's an attempt to expand what's already an absolute path.

**Comment by pmoura** [comment]
This issue seems to be partially solved. Before, both `logtalk3/examples/module_aliases` and `logtalk/tests/logtalk/directives/use_module_2` were broken. Now all the tests for the former pass but the latter is still broken. It seems that the path issue is fixed only when `use_module/1` is used as a directive but not if used as a predicate.

**Comment by infradig** [comment]
Odd, as I only changed the predicate version. Perhaps you got the that
backwards? I'll have a look again.

**Comment by infradig** [comment]
Actually, I don't I changed use_module directive at all recently.

**Comment by infradig** [comment]
Ok, so Logtalk uses the Trealla use_module predicate for both cases? I say
that because the error message only comes from the predicate.

**Comment by pmoura** [comment]
Thanks for the quick fix. Confirmed. All tests for both test sets now pass.
