### ISSUE TITLE
No warning/error for unknown directive

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#295]
```
?- [user].
:- op(900,fx,op1), op(900,fx,op2).
true. % unexpected
?- current_op(Pri,Fix,op1).
false.
?- current_op(Pri,Fix,op2).
false.
?- [user].
:- op(900,fx,op3).
true.
?- current_op(Pri,Fix,op3).
Pri = 900, Fix = fx 
```

The term `:- op(900,fx,op1), op(900,fx,op2).` is not a directive, because `(',')/2` is not a directive.

BTW, do you intend to fix #289, #237, #233?

**Comment by infradig** [comment]
Currently Trealla silently ignores directives it doesnt understand, as you
can see.
