### ISSUE TITLE
between/3: Inconsistent semantics

### ISSUE THREAD

**Issue by triska** [infradig/trealla#3]
From the source code, it seems that `between(1, a, 3)` throws a **type error** saying that an *integer* is expected for the second argument. This works correctly.

However, the predicate *succeeds* for `between(1, inf, 3)`, where the second argument is *not* an integer.

This is inconsistent and thus prevents automated logical reasoning about programs: The system indicates that the second argument must be an integer, yet at the same time succeeds also for cases where it is *not* an integer.

Please consider correcting this inconsistency and throw a *type error* also for cases like `between(1, inf, 3)`.

In addition to improving logical consistency and allowing declarative debugging, this would yield another major benefit in that it guarantees that `between/3` **always&nbsp;terminates**. This means that when users encounter unexpected nontermination in programs (a very common mistake when writing Prolog code), `between/3` cannot be responsible for it and need not be considered in automated analyses of code.

**Comment by infradig** [comment]
Will look into it.
