### ISSUE TITLE
Ctrl+c does not work reliably

### ISSUE THREAD

**Issue by triska** [infradig/trealla#30]
With `as.pl` consisting of:

<pre>
as --> [].
as --> [a], as.
</pre>

I get:

<pre>
<b> ./tpl as.pl</b>
Trealla ProLog (c) Infradig 2020, v1.2.20
<b>?- phrase(as, As), false.</b>
^C
Action (a)bort, (c)ontinue, (e)xit: a

<i>aaa^Caaa/*(I'm trying to interrupt this, and it apparently does not work.)*/</i>
</pre>

**Comment by triska** [comment]
I now get:

<pre>
<b>$ ./tpl as.pl</b>
Trealla ProLog (c) Infradig 2020, v1.2.20
<b>?- phrase(as, As), false.</b>
^C
Action (a)bort, (c)ontinue, (e)xit: a

^C
<b>$</b>
</pre>

i.e., it quits the system entirely instead of returning to the top-level.

**Comment by infradig** [comment]
I know. But at least it quits nicely. I need to figure out where it's going.

**Comment by triska** [comment]
This works perfectly now, thank you a lot!
