### ISSUE TITLE
term_variables/2 (looped) rejects list

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#300]
Given your fix of #297,

<pre>
?- L=[L], term_variables(T,L).
L = [_0], T = L.    % kindof expected, better would be L = [L], T = L.
<s>?- L=[a|L], term_variables(T,L).
*loops*             % unexpected, expected type_error(list, L)</s>
</pre>

what is now your commitment to infinite trees? In the past (#233), you ignored this issue, maybe reconsider this now. Implementing [`skip_max_list/4`](https://github.com/mthom/scryer-prolog/issues/1023) is a banality compared to the overheads so far encountered. Note that there is still another tiny issue to address, but not even [SICStus](http://www.complang.tuwien.ac.at/ulrich/sicstus-prolog/#201) has it.

One of the main reasons to support them is the better termination properties and thus better testing properties. It took me an entire hour to identify #299 as it was overshadowed by #297. And, (as I have seen in other systems that do not support rational trees &mdash; e.g., B) many problematic areas cannot be ruled out with `acyclic_term/1` nor `unify_with_occurs_check/2` alone.

**Comment by infradig** [comment]
Totally committed to rational trees. I have other commitments that limit
the time I have available.

**Comment by UWN** [comment]
> I have other commitments that limit ...

Such as

```
?- L=[a|L], length(L,N).
uncaught exception: error(instantiation_error,cyclic_term)  % unexpected
?- L=[a|L], length(L,0).
uncaught exception: error(type_error(cyclic_term,0),length/2) % unexpected, the type error says what is expected, not what is unexpected.
?- L=[L], length(L,N).
uncaught exception: error(instantiation_error,cyclic_term) % expected N = 1
```
All are non-sensical.

In comparison to the effort you spent to produce these results, a **single** built-in '$skip_max_list'(Skipped, Max, Xs0,Xs) would solve all these problems, once and for all.

**Comment by UWN** [comment]
```
?- L=[a|L], term_variables(T,L).
uncaught exception: error(type_error(list,[a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a|...]),term_variables/2) % expected
?- L=[L], term_variables(T,L).
uncaught exception: error(type_error(list,[_0]),term_variables/2) % unexpected, this is a list
```

**Comment by infradig** [comment]
I also noticed that

?- L=[L|L], term_variables(T,L).
caught:
LOOPS

sends Scryer into a loop.

**Comment by infradig** [comment]
Are these desirable?

~/trealla (devel) $ rlwrap scryer
?- L=[L|a], length(L,N).
false.
?- L=[a|L], length(L,0).
false.
?- L=[L|L], length(L,N).
false.

**Comment by UWN** [comment]
No, undesirable, see [#6](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/length#26). But please, first do $skip_max_list/4, I'll put an item for that.

**Comment by UWN** [comment]
> sends Scryer into a loop

Sends the top level into a loop.
```
?- catch((L=[L|L], term_variables(T,L)),Error,true).
   Error = error(type_error(list,[[[...,
```

**Comment by UWN** [comment]
Closed, because original issue is fixed, not the remaining ones.
