### ISSUE TITLE
dif/2: Unexpected instantiation error atomic?

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#304]
<pre>
Trealla Prolog (c) Infradig 2020-2021, v1.17.10
?- [user].
t(G) :- findall(t,G,_).
true.
?- t((A=[B],B=[C|C],D=[A|B],dif(D,B))).
<s>uncaught exception: error(instantiation_error,atomic) % unexpected</s>
</pre>
Update: Same error still occurs elsewhere.

Last commit (since git describe is now too terse)

```
commit f1d1136c4f12946a735d3e75dacf57a2449d4e91
Author: Andrew Davison <andrew@infradig.com>
Date:   Sat Dec 18 21:37:59 2021 +1000

    Fix for term_variables/2 looping on cyclic 2nd term, re issue #300
```

**Comment by infradig** [comment]
You have something in common with Paulo again, this might be related to
issue #300.

**Comment by UWN** [comment]
Actually, I intended to find cases that are entirely unrelated to STO-ness. Now I realize, the dif/2 actually attempts the loop. Wait ...

**Comment by UWN** [comment]
Ok, that is again STO, but kind of not:

```
Trealla Prolog (c) Infradig 2020-2021, v1.17.10
?- [user].
tt(EsG,_) :-
		findall(t,EsG,_).
true.
?- tt((A=[B],dif([],B),B=[A|A]),t).
uncaught exception: error(instantiation_error,atomic)
```

**Comment by UWN** [comment]
Now, it is:
```
?- findall(t, (dif([],A),A=[B],B=[A|A]), _).
uncaught exception: error(instantiation_error,atomic)
```

**Comment by infradig** [comment]
Anything to do with dif/2 is still work in progress. There is a bug i am
trying to track down to do with undo/redo the trail in the hook.

**Comment by UWN** [comment]
So you do not want these findings?

**Comment by infradig** [comment]
Getting this now...

~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.19.20
?- findall(t, (dif([],A),A=[B],B=[A|A]), _).
   true.

Same as others.

**Comment by UWN** [comment]
Closing, and opening as new issue, should something appear.

**Comment by pmoura** [comment]
Likely related bug (https://github.com/infradig/trealla/issues/301) still shows unexpected `error(instantiation_error,atomic)`.
