### ISSUE TITLE
dif/2 incorrect for NSTO case

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#306]
While I was sleeping...
```
?- C=A,A=[[]],B=[C|A],dif(A,B),C=A.
C = [[]], A = C, B = [[[]],[]].  % expected
?-     A=[[]],B=[C|A],dif(A,B),C=A.
false.                           % unexpected
```

Maybe consider a better implementation. So far, there has not been a single error in Scryer nor in SICStus. I have some [higher expectations](https://github.com/mthom/scryer-prolog/issues/1010) for Scryer, but, well, that is more ambitious.

Other systems, like SWI, are not recommended for inspiration. There, errors in `dif/2` reside [for a decade](https://github.com/SWI-Prolog/issues/issues/105) due to [lack of conformance](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/SWI7_and_ISO), an inability to localize errors and extreme difficulties in installation such that I can use it only on one system with the Ubuntu software center. Also `dif/2` issues have been closed [prematurely](https://github.com/SWI-Prolog/issues/issues/15).

Contrast this to Trealla, where I say

     git pull&&make OPT=-std=c99 NOSSL=1&&kill %1;date;git describe;time ./tpl

For conformance, things are not perfect though, in particular `length/2`.

**Comment by infradig** [comment]
These case have no dependence upon the dif/2 call, and that call should be
side-effect free. That's it's is mofe indicative another problem, most
likely with levels in if-then....

~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.17.13
?- A=[[]],B=[C|A],writeln(C),C=A.
_2

?- A=[[]],B=[C|A],dif(A,B),writeln(C),C=A.
[]
false.

which will be good to fix, as it probably has implications elsewhere.

PS I'll look into $skip-your-hoosit/4 when time permits. This weekend is
almost done.

**Comment by infradig** [comment]
Thanks Ulrich, this has shown up a bug with (\=)/2 that I can't believe
hasn't been obvious before. I could forgive you for being such an
a$%^#hole, in fact I will.
