### ISSUE TITLE
'$skip_max_list'/4 needed

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#308]
This is an internal predicate, thus the conventions do not need to conform to any thing.

`'$skip_max_list'(Skip, Max, Xs0,Xs)`

`Skip` will be always a new variable, maybe an `uninstantiation_error` for extra safety. Upon success, `Skip` is unified with the number of `'.'/2`s that have been skipped  in `Xs0` to reach `Xs`.

`Max` is kind-of an input variable. If it is instantiated, it must be a non-negative integer thus argument produces `domain_error(not_less_than_zero,-1)` for `-1` and `type_error(integer,-0.1)` for `-0.1`. If it is a variable then it means that there is no maximum. `Max` will not be unified with anything, so it is not a regular argument. Note that for very large values of `Max`, the value can be skipped if such a large cycle cannot be represented in memory. And since you have a special representation of `chars`, this `Max` would have to be as large as the address space, like `2^64` minus tagging.

`Xs0` may be any term (preferably a list or partial list, but also any other term is ok). A [list prefix](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#7.1.6.9) will now be skipped from this term until the `Max`-imum is reached, or a non-`'.'/2`, or one realizes qua [Brent](https://en.wikipedia.org/wiki/Cycle_detection#Brent's_algorithm) that we are in a cycle. The resulting value is unified with `Xs`.

Thus by inspecting `Xs` alone, we can tell what this `Xs0` actually is:

- `Xs == []` thus `Xs0` is a (well formed) list
- `var(Xs)` thus `Xs0` is a partial list including a plain variable or an atv.
- all others are *neither a list nor a partial list*, in particular
- `functor(Xs,'.',2)` thus `Xs0` is an infinite list, and `Xs` is already somewhere within the loop (currently in Scryer it is not within the loop, but `Xs0` again, that's a bit annoying)

---
Only after this internal predicate is present, I will continue to look at Trealla. It is absolutely pointless without. #233, #234, #237 are still open and it was only [someone](https://github.com/triska) asked, that I looked at `dif/2`. All this is known to you since August.

**Comment by infradig** [comment]
Made an exploratory start on this.

**Comment by UWN** [comment]
```
Trealla Prolog (c) Infradig 2020-2021, v1.17.16-9-gd56e22
?- '$skip_max_list'(Skip,1,"123",Xs).
*loops*
```

In Scryer,
```
?- [user].
skip_max_list(Skip,1,"123",Xs) :- '$skip_max_list'(Skip,1,"123",Xs).

?- 'skip_max_list'(Skip,1,"123",Xs).
   Skip = 1, Xs = "23".
```
Note that the $ is taken as an indication for an internal predicate. So one cannot call it.

**Comment by infradig** [comment]
It only does regular  dot-lists for now and it's not really test worthy.

**Comment by UWN** [comment]
```
Trealla Prolog (c) Infradig 2020-2021, v1.17.16-9-gd56e22
?- '$skip_max_list'(Skip,1,[1,2,3],Xs).
Skip = 1, Xs = Skip. % unexpected
?- 
```
Expected: Xs = [2,3]

**Comment by infradig** [comment]
It's a start and not ready for testing. Only at the point of verifying
Brent would work in-situ.

**Comment by UWN** [comment]
```
Trealla Prolog (c) Infradig 2020-2021, v1.17.16-9-gd56e22
?- '$skip_max_list'(Skip,_,[1,2,3],Xs).
Skip = 39064904, Xs = [1,2,3].
?- 
real	0m9.620s
user	0m0.078s
sys	0m0.007s
ulrich@p0:/opt/gupu/trealla$ git checkout skip_max_list
Already on 'skip_max_list'
Your branch is up-to-date with 'origin/skip_max_list'.
ulrich@p0:/opt/gupu/trealla$ git checkout main
Switched to branch 'main'
Your branch is up-to-date with 'origin/main'.
ulrich@p0:/opt/gupu/trealla$ git pull&&make OPT=-std=c99 NOSSL=1&&kill %1;date;git describe;time ./tpl
Already up-to-date.
...
*cc TEN TIMES*
...
bash: kill: %1: no such job
Mon Dec 20 11:17:47 CET 2021
v1.17.16
Trealla with .tplrc
Trealla Prolog (c) Infradig 2020-2021, v1.17.16
?- '$skip_max_list'(Skip,_,[1,2,3],Xs).
uncaught exception: error(existence_error(procedure,'$skip_max_list'/4),'\'$skip_max_list\''/4)
                                                                         ^^              ^^
```                                 
> not ready for testing.

So it will be ready for testing if it is in the main branch.

**Comment by infradig** [comment]
Stop being ridiculous, it is just barely compiled code.  In no way meant to
be functional.

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
?- L=[1,2,3|L], '$skip_max_list'(Skip,3,L,Xs).
L = [1,2,3|_0], Skip = 3, Xs = L.
?- L=[1,2,3|L], '$skip_max_list'(Skip,4,L,Xs).
L = [1,2,3|_0], Skip = 4, Xs = [2,3|_0].
?-

~/trealla (devel) $ rlwrap scryer sml.pl
?- L=[1,2,3|L], skip_max_list(Skip,3,L,Xs).
   L = [1,2,3|L], Skip = 3, Xs = [1,2,3|L].
?- L=[1,2,3|L], skip_max_list(Skip,4,L,Xs).
   L = [1,2,3|L], Skip = 4, Xs = [2,3,1|Xs].

I was confused at first by Scryer showing [2,3,1|Xs] in the last example
but it does make sense.

**Comment by UWN** [comment]
```
?- '$skip_max_list'(1+2,_,"1235",Xs).
false.
```
Expected: `type_error(integer,1+2)`

**Comment by UWN** [comment]
```
?- '$skip_max_list'(Skip,1000000000000,"1234",Xs).
Skip = 0, Xs = "1234". % unexpected
```
Expected: `Skip = 4`.

**Comment by UWN** [comment]
```
?- phrase("1234567",L,[]),'$skip_max_list'(Skip,3,L,Ls). 
L = "1234567", Skip = 1, Ls = L.
?- phrase("1234567",L,L),'$skip_max_list'(Skip,3,L,Ls). 
L = [_0|_3], Skip = 1, Ls = L.
```
Why? I'd expect Skip = 3 in both cases. And how can `Ls = L` be?

**Comment by UWN** [comment]
```
?- phrase("1234567",L,[]),'$skip_max_list'(Skip,1000000000000,L,Lx).
L = "1234567", Skip = 1, Lx = L. % unexpected
```
Expected: Skip = 7.

**Comment by UWN** [comment]
```
?- '$skip_max_list'(Skip,_,L,[]).
uncaught exception: error(uninstantiation_error([]),'\'$skip_max_list\''/4)
```

This does not make sense, as this last argument is unifiable.

*At best*, the `Skip` could be protected that way. But even there I am now a bit in hesitation. Unification is there still better.

**Comment by UWN** [comment]
```
?- L="abc", '$skip_max_list'(Skip,_,L,Lx).
L = "abc", Skip = 3, Lx = [].       % expected
?- L=[a,b,c], '$skip_max_list'(Skip,_,L,Lx).
L = "abc", Skip = 1, Lx = [].       % unexpected, expected as above
?- L=[a,b,c,d], '$skip_max_list'(Skip,_,L,Lx).
L = "abcd", Skip = 4, Lx = [].      % expected, but why "abc" did not work
```

**Comment by UWN** [comment]
And in general:

```
?- _=N, length(L,N), maplist(=(a),L),'$skip_max_list'(Skip,_,L,Lx), \+ ( Lx == [], N == Skip ).
N = 0, L = [], Skip = 1, Lx = L 
; N = 3, L = "aaa", Skip = 1, Lx = [] 
; N = 7, L = "aaaaaaa", Skip = 1, Lx = [] 
; N = 15, L = "aaaaaaaaaaaaaaa", Skip = 1, Lx = [] 
; N = 31, L = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", Skip = 1, Lx = [] 
; N = 63, L = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", Skip = 1, Lx = [] 
; N = 127, L = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", Skip = 1, Lx = [] 
; N = 255, L = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", Skip = 1, Lx = [] 
; N = 511, L = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", Skip = 1, Lx = [] 
; ...
```
So `N is 2^I-1^` for all `I >= 0` with the notable exception of `I = N = 1`
