### ISSUE TITLE
Syntax error in correct code

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#309]
Try:

```text
$ cd logtalk3/examples/bench
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.17.16-1-g24c554
?- [nand].
Error: syntax error, mismatched parens/brackets/braces, line 113 '	update_bounds(_, 21, _).
'
```

But there's no syntax error in the code.

**Comment by infradig** [comment]
Is this new? Or new-ish?

**Comment by pmoura** [comment]
Only noticed today when running all tests in the Logtalk distribution to compare withe previous run I reported in https://github.com/infradig/trealla/issues/99#issuecomment-997147068 (there are 4 more failed tests and a timeout with the `json` library).

**Comment by infradig** [comment]
It went wrong here...
commit d64f7677bcf3e3e0c386bedadc290d4a8a3bddf2 (tag: v1.17.3)
Author: Andrew Davison ***@***.***>
Date:   Wed Dec 15 12:42:55 2021 +1000

    Fix parser bug with [ WS ] & { WS }, re issue #291

**Comment by infradig** [comment]
Have reduced the problem in nand.pl to this cut-down fragment

init_state([ %
function(0,
[])
]) :-
true.

The % comment seems to be the problem. I'll look into it.

**Comment by pmoura** [comment]
Thanks for the fix. Confirmed.
