### ISSUE TITLE
Unexpected infinite loop

### ISSUE THREAD

**Issue by triska** [infradig/trealla#32]
With `as.pl` defined as:

<pre>
as --> [].
as --> [a], as.
</pre>

I get:

<pre>
?- phrase(as, Ls), Ls = "aa".
<i>nontermination</i>
</pre>

Expected: *Success*.

For comparison, the following works as expected:

<pre>
<b>?- Ls = "aa", phrase(as, Ls).</b>

Ls = "aa"

true.
</pre>

**Comment by infradig** [comment]
Intersting as.pl translates to:

as(S0_,S_) :- S0_=S_.
as(S0_,S_) :- S0_=[a|S1_],as(S1_,S_).

which is the traditional way of doing it. However if I manually change it to

as(S_,S_).
as([a|S1_],S_) :- as(S1_,S_).

which is equivalent and how other Prologs now do it, it works.

The simple solution would be to change my DCG rewrite code to do it that way, however the indication is it's exposing a more fundamental problem that hasn't shown up until now, so i'll wait off on that.

**Comment by triska** [comment]
Perfect, thank you a lot!
