### ISSUE TITLE
'$skip_max_list'/4 loops upon loop detection

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#328]
```
Trealla Prolog (c) Infradig 2020-2021, v1.18.4
?- N=1, length(L_p,N),phrase(L_p,L0,L0),'$skip_max_list'(Skip,_,[prefixel|L0],Lc).
*LOOPS*
```

**Comment by UWN** [comment]
Correction: it actually detects a loop, but a very wide one:
```
?- N=1, length(L_p,N),phrase(L_p,L0,L0),'$skip_max_list'(Skip,_,[prefixel|L0],Lc).
N = 1, L_p = [_26], L0 = [_0|_3], Skip = 2147483647, Lc = L0.
?- 2147483647 = 0x7fffffff.
true.
```

Why this number? Is this the address space?

**Comment by infradig** [comment]
signed 32-bits = 2^32-1 it seems, sizeof of an offset/index (used here as a
counter) in Trealla.

**Comment by UWN** [comment]
How long is the longest list of chars? Certainly longer than 2^32 more like 2^63. So such a skip cannot be represented with a 2^32 counter,
