### ISSUE TITLE
'$skip_max_list'/4 wrong skip with detected loop

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#329]
```
?-                   '$skip_max_list'(Skip,_,[1,2|L0],Lc).
Skip = 2, L0 = L0.        % expected
?- phrase("1",L0,L0),'$skip_max_list'(Skip,_,[1,2|L0],Lc).
L0 = [_0|_3], Skip = 1, Lc = L0.   % unexpected
?- phrase("1",L0,L0),'$skip_max_list'(Skip,_,[1,2,3|L0],Lc).
L0 = [_0|_3], Skip = 1, Lc = L0.   % unexpected
```
The `Skip` is the length of the [list prefix](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#7.1.6.9) up to the point where the loop is detected.

The second case is an instance of the first one. And thus the `Skip` must be at least as large as the original `Skip`. And for some reason you seem to get always the exact length (that is, also with larger cycles). But Brent cannot detect this that quickly. My uneducated guess is that you perform internally some marking or caching or something to that end. And the big advantage of Brent is that it is read only.

**Comment by UWN** [comment]
It is much better now in that the `Skip` is now the length up to the cycle. Now there is no chance to determine the cycle length. But I admit this is a lesser problem since this is only of interest if one is into explicitly using infinite rational trees. And I am only interested in their well-behavedness such that diagnostic procedures are not disturbed by them, e.g. via non-termination.

**Comment by infradig** [comment]
I consider it still work in progress.

**Comment by UWN** [comment]
(I try to keep open issues minimal), but after looking at unify.c:

- it seems only a single while-loop is needed (the first one)
- this loop could reuse the string optimization also for cases like L0=[a|BigString]
- the remark on Floyd seems odd: Floyd detects the cycle by two simultaneous pointers reading with different speed. So in the case of a well-formed list with n elements, it will read like n+n/2 cons-cells whereas Brent just reads the necessary n cells (and does some local bookkeeping)

**Comment by UWN** [comment]
[Mentioned here](https://github.com/mthom/scryer-prolog/issues/1176#issuecomment-1008839519).

**Comment by UWN** [comment]
> I consider it still work in progress.

It seems that this problem exists in both Trealla and Scryer and I think I have now the
[ultimate definition](https://github.com/mthom/scryer-prolog/issues/1260#issuecomment-1027209615).
