### ISSUE TITLE
Unexpected first solution

### ISSUE THREAD

**Issue by triska** [infradig/trealla#33]
With `as.pl` consisting of:

<pre>
as --> [].
as --> [a], as.
</pre>

I get:

<pre>
<b>$ ./tpl as.pl</b>
Trealla ProLog (c) Infradig 2020, v1.2.20
<b>?- phrase(as, Ls), Ls = [a|Rs].</b>

Ls = [a,a]
Rs = []

true.
</pre>

Expected: `Ls = "a"` as the first solution.

**Comment by infradig** [comment]
This is the REPL dump_vars bug, issue #40 and should be closed as it seems resolved now.

**Comment by triska** [comment]
Perfect, thank you a lot!
