### ISSUE TITLE
Message syntax error expected

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#332]
$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.8
?- ``[.], true.``
true.
?- ``[.], false.``
false.
?- ``[.][.], false.``
true. % syntax error expected
?-

**Comment by flexoron** [comment]
may I ask which answers are correct?

$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.8
?- ``[.].``
true.
?- ``[..].``
true.
?- ``[...].``
uncaught exception: error(existence_error(source_sink,...),load_files/2)
?-

$ gprolog 
GNU Prolog 1.5.0 (64 bits)
| ?- ``[.].``      
uncaught exception: error(existence_error(source_sink,'..pl'),consult/1)
| ?- ``[..].``
uncaught exception: error(existence_error(source_sink,'...pl'),consult/1)
| ?- ``[...].``
uncaught exception: error(existence_error(source_sink,...),consult/1)
| ?

**Comment by infradig** [comment]
Ok, fixed. I notice Scryer (at least in my version) has this problem as
well.

**Comment by flexoron** [comment]
$ cat pn.pl
p :- write('positive ').
n :- write('negative ').

$ trealla/tpl 
Trealla Prolog (c) Infradig 2020-2021, v1.18.9-1-g6f5ca10
?- ``[.].``
uncaught exception: error(existence_error(source_sink,'.'),load_files/2)

?- ``[pn], p.``
positive true.

?- ``[pn][pn], n.``
true.
?- ``n.``
negative true.

**Comment by flexoron** [comment]
$ cat ..pl
``'..pl' :- write('an unusual but valid filename').``

$ gprolog
| ?- ``[.].``
compiling ..pl for byte code...

| ?- ``'..pl'.``
an unusual but valid filename


$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.9-1-g6f5ca10
?- ``[.].``
uncaught exception: error(existence_error(source_sink,'.'),load_files/2)
?-

**Comment by infradig** [comment]
Somewhat simpler case...

?- X = [1][2].
X = [1].
?-

**Comment by flexoron** [comment]
Not sure about comment 'Fix partial'
Do you mean this:

Trealla Prolog (c) Infradig 2020-2021, v1.18.25
?- ``[pn][pn], p.``
Error: syntax error needs operator '[', line 1 % expected
``false.`` % ???

?- ``[pn], p.``
positive true. % expected

?- ``[pn][pn], p.``
Error: syntax error needs operator '[', line 1 % expected
``true.`` % ???
?- 

As you can see, the first wrong call reports ``false.``
The one corrected answers as expected.
The second wrong call reports ``true.``

**Comment by flexoron** [comment]
$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.28
?- [pn][pn], p.
Error: syntax error needs operator '[', line 1
?-  [pn], p.
positive    true.
?- [pn][pn], p.
Error: syntax error needs operator '[', line 1
?-

I guess this issue is resolved.
