### ISSUE TITLE
Reloading makes phrase/2 invalid

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#335]
```
ulrich@p0:/tmp$ cat d.pl
malleq :-
	phrase(mspec,[]).

mspec --> [].
ulrich@p0:/tmp$ /opt/gupu/trealla/tpl
Trealla with .tplrc
Trealla Prolog (c) Infradig 2020-2021, v1.18.9-1-g6f5ca10
?- [d].
true.
?- malleq.
true.   % expected
?- [d].  % now reload it
true.
?- malleq.
uncaught exception: error(existence_error(procedure,(=)/2),(=)/2) % unexpected
```

In more complex cases there is the same error about `(',')/2`.

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.11-2-g90861-dirty
?- [d].
true.
?- listing.
malleq :- phrase(mspec,[]).
mspec(_32,_33) :- _32=_33.
true.
?- deconsult(d).
true.
?- listing.
true.
?- [d].
true.
?- listing.
malleq :- phrase(mspec,[]).
:-(mspec(_32,_33),=(_32,_33)).
true.
?-

It's seems to lose operators.

**Comment by infradig** [comment]
But it seems only DCG translations are affected.

**Comment by UWN** [comment]
> It's seems to lose operators.

But operators are completely unrelated as it is syntax only.
