### ISSUE TITLE
op/3, current_op/3 error 

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#336]
$ scryer-prolog -f
?- ``op(700,xfx,"[]").``
true.
?- ``current_op(700,xfx,'[').``
true
?- ``current_op(700,xfx,']').``
true

$ tpl 
Trealla Prolog (c) Infradig 2020-2021, v1.18.9-1-g6f5ca10
?- ``op(700,xfx,"[]").``
true.
?- ``current_op(700,xfx,'[').``
Error: syntax error, start of rule expected, line 1 ''
true.
?- ``current_op(700,xfx,']').``
Error: syntax error, missing operand or operator
true.
?-

OR (in parentheses message ...missing... changed)

?- ``current_op(700,xfx,(']')).``
Error: syntax error, start of rule expected, line 1 ''
true.
?- ``current_op(700,xfx,('[')).``
Error: syntax error, start of rule expected, line 1 ''
true.

**Comment by UWN** [comment]
This has nothing to do with current_op/3. It is the parser:

```
Trealla Prolog (c) Infradig 2020-2021, v1.18.9-1-g6f5ca10
?- read(X).
'['.
X = '['.    % expected
?- op(700,xfx,"[").
true.
?- read(X).
'['.
         % unexpected waiting
uncaught exception: error(syntax_error(parens),read/1) % unexpected upon ^D
```

In case of doubt always try read/1 in addition to the top level reader which are a little bit different sometims.

**Comment by UWN** [comment]
```
?- current_op(700,xfx,('[')).
%                     ^   ^
```
These extra round brackets are never needed. In the position of an argument list, a single atom is never interpreted as an operator.

**Comment by flexoron** [comment]
ok, thnx, phenomenal
$ tpl 
Trealla Prolog (c) Infradig 2020-2021, v1.18.9-1-g6f5ca10
?- ``current_op(700,xfx,A).``
A = (<) 
; A = (=) 
; A = (=..)
:
?- ``op(700,xfx,"[]").``
true.
?- ``current_op(700,xfx,A).``
Error: syntax error, start of rule expected, line 1 ''
false.
?- ``current_op(700,xfx,A).``
false. % second call, missing error message and ``... line 1 ''`` <- a lonely double quote at the end?

**Comment by UWN** [comment]
Same with `op(700,xfx,"(")`

**Comment by infradig** [comment]
Not a double quote, two adjacent single quotes. Meaning the error was
detected at the end of the input.

**Comment by flexoron** [comment]
$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.15
?- ``op(700,xfx,"[]").``
true.
?- ``current_op(700,xfx,A).``
A = ('[') 
; A = (']') 
; A = (<) 
; A = (=) 
; ...

A question: ``\"`` to quote or no quotes?

$ scryer-prolog -f
?- ``op(700,xfx,"\"").``
   true.
?- current_op(700,xfx,A).
   ``A = ('\"')``
;  ...

$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.15
?- ``op(700,xfx,"\"").``
true.
?- current_op(700,xfx,A).
``A = (\")``
; ...

**Comment by flexoron** [comment]
Trealla Prolog (c) Infradig 2020-2021, v1.18.18
?- ``op(700,xfx,"[\"(])").``
true.
?- current_op(700,xfx,A).
``A = ('\"')`` 
; ``A = ('(')`` 
; ``A = (')')`` 
; ``A = ('[')`` 
; ``A = (']')``

Immaculate Condition!
