### ISSUE TITLE
'$skip_max_list'/4 unexpected type error

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#338]
```
?- Max is 2^63, '$skip_max_list'(Skip,Max,[],Xs).
uncaught exception: error(type_error(integer,9223372036854775808),'\'$skip_max_list\''/4) % unexpected
```
(Thought this was fixed)

Expected: `Max = 9223372036854775808, Skip = 0, Xs = [].`

**Comment by infradig** [comment]
The max it will allow is 2^63-1.  Maybe there's a better error.

**Comment by UWN** [comment]
It does not make sense to produce an error! If the max is so large that it will never be reached, then simply ignore it.
