### ISSUE TITLE
frozen/2: uninstantiation_error missing

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#339]
```
?- frozen(a,G).
G = true.   % unexpected
```

See [7.12.2 k](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#uninstantiation_error), [motivation](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/error_k).

**Comment by pmoura** [comment]
LVM, SICStus Prolog, and SWI-Prolog provide the same result as Trealla. ECLiPSe fails. XSB doesn't yet provide this predicate. YAP git is broken for this predicate but more stable versions most like behave as SICStus Prolog and SWI-Prolog here.

**Comment by UWN** [comment]
This seems to be change in SICStus introduced in 4.6.0. It really makes no sense. Originally (0.7) SICStus failed, then introduced `type_error(variable,_)` and after Cor.3 replaced it by an `uninstantiation_error`. Are you, @pmoura related to this change?

**Comment by pmoura** [comment]
> This seems to be a change in SICStus introduced in 4.6.0. It really makes no sense. Originally (0.7) SICStus failed, then introduced `type_error(variable,_)` and after Cor.2 replaced it by an `uninstantiation_error`.

SICStus publishes release notes:

https://sicstus.sics.se/sicstus/docs/4.6.0/html/relnotes/4_002e6_002e0-Other-Changes.html

> - The built-in frozen(+Term,-Goal) has been generalized so that Goal is the conjunction of all goals blocked on some variable in Term.

Possibly a consequence of this change. Btw, given the importance that you and a few others give to coroutining predicates (e.g. `dif/2`), here and elsewhere, where are their standardization proposals to be found?

> Are you, @pmoura related to this change?

Paranoia much?

**Comment by infradig** [comment]
I'll have to side with everyone else on this one. It stays as-is.

**Comment by UWN** [comment]
> where are their standardization proposals to be found?

First of all, any extension needs to be a valid extension qua 5.5. And the cases so far identified for `dif/2` are all invalid extensions or undesirable ones (non-termination). No need for new documents if the existing ones are not respected. What is even more difficult is that many such counterexamples are STO. Others are (possibily) hiding behind [non-termination](https://github.com/SWI-Prolog/swipl-devel/issues/919).

> > Are you, @pmoura related to this change?
>
> Paranoia much?

Your [prior](https://github.com/infradig/trealla/issues/233) [nonconforming interventions](https://github.com/infradig/trealla/issues/237#issuecomment-898886844) suggest it.
