### ISSUE TITLE
append/3: Unexpected answer

### ISSUE THREAD

**Issue by triska** [infradig/trealla#34]
Currently, I get:

<pre>
<b>$ ./tpl</b>
Trealla ProLog (c) Infradig 2020, v1.2.20
<b>?- append("abc", "def", Ls).</b>

Ls = [[a,b,c,".","."

true.
</pre>

Expected: `Ls = "abcdef"`.

**Comment by infradig** [comment]
Yes, when this is fixed string_concat/3 can be removed.

**Comment by infradig** [comment]
Ok, I have this from the classic append...

./tpl -g 'append("abc","def",Ls),write(Ls),nl,halt'                                                       
[a,b,c,d,e,f]

which is a start, had to fix some string stuff.
However, should mixed-mode inputs do...

./tpl -g 'append([a,b,c],"def",Ls),write(Ls),nl,halt'                                                       ±[●][devel]
[a,b,c,d,e,f]

as currently, or

"abcdef" as the first one should. I think mixed-mode inputs should go to strings.

**Comment by josd** [comment]
Currently I also get
```
$ tpl
Trealla ProLog (c) Infradig 2020, v1.2.23
?- append([1, 2, 3], [4, 5, 6, 7], X).

X = [[1,2,3,4,5,6,7],2,3]

true.
?-
```
BUt Trealla Prolog is really impressive!

**Comment by infradig** [comment]
Thanks, still a long way to go!

I think this is an artifact of dump_vars() in the REPL...

Trealla ProLog (c) Infradig 2020, v1.2.23-14-g5ecc7-dirty
?- append([1, 2, 3], [4, 5, 6, 7], X),writeln(X).
[1,2,3,4,5,6,7]
X = [1,2,3,4,5,6,7]
true.
?- append([1, 2, 3], [4, 5, 6, 7], X).
X = [[1,2,3,4,5,6,7],2,3]
true.
.
I will look into it.

**Comment by triska** [comment]
Yes, absolutely: Every time a list of characters is to be emitted on the top-level, it can and should simply be written as a string, using double quotes.

For instance, I currently get:

<pre>
<b>?- Xs = [a,b,c].</b>

Xs = [a,b,c]

true.
</pre>

Printing `Xs = "abc"` would be perfectly admissible, and preferable due to its brevity. String syntax can and should be used no matter how the term is *internally* stored, because from the perspective of the Prolog programmer, `[a,b,c]` and `"abc"` are not distinguishable in any way. Both are the same list of characters.

**Comment by triska** [comment]
For the original query, I now get:

<pre>
<b>?- append("abc", "def", Ls).</b>

Ls = [c,d,e,f]

true.
</pre>

**Comment by infradig** [comment]
Yes, a step on the way.

**Comment by infradig** [comment]
Also, don't trust what the repl dump_vars reports. Looking into that.

**Comment by infradig** [comment]
That would involve scanning each list before printing to see if it's a
candidate.

**Comment by triska** [comment]
Yes, absolutely: Since the list must be printed out in any case, the overhead can be completely ignored.

The same holds when parsing a list: If it's a list of characters, it can be stored compactly, no matter how it is written in the actual code. It can even be converted to a more compact internal form later, when more about it becomes known.

**Comment by infradig** [comment]
Noted.

**Comment by infradig** [comment]
> For the original query, I now get:
> 
> ?- append("abc", "def", Ls).
> 
> Ls = [c,d,e,f]
> 
> true.

If you add a writeln(Ls) at the end of the query you see the correct result. This needs to be raised as a separate issue as it is a REPL/dump_vars problem. I will do that.

**Comment by triska** [comment]
The remaining issue indeed seems to be only a top-level problem, because the following succeeds (as expected):

<pre>
<b>?- append("abc", "def", Ls), Ls = "abcdef".</b>

Ls = [[a,b,c,d,e,f],b,c]

true.
</pre>

Only, the reported answer is written wrongly (#40).

**Comment by infradig** [comment]
> Yes, absolutely: Since the list must be printed out in any case, the overhead can be completely ignored.
> 
> The same holds when parsing a list: If it's a list of characters, it can be stored compactly, no matter how it is written in the actual code. It can even be converted to a more compact internal form later, when more about it becomes known.

Ok, parsing "" give [] internally, fine. But what about printing []? Is it ok to always print ""? Does this mean that [] is never visible anymore (except write canonical), can only be read for comptability purposes effectively?

**Comment by triska** [comment]
Strictly speaking, since`[] == ""` (i.e., they really are the same term), it does not matter which of them is printed for the empty list.

However, `[]` is a good choice in general, because `"..."` suggests a list of characters, whereas `[...]` can be used for any list at all, so `[]` makes sense in the general context.

So, I think the current solution is very good!
