### ISSUE TITLE
[user]. Despite strange syntax error message, program works

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#345]
$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.15
?- ``op(700,xfx,'"').``
true.
?- current_op(700,xfx,A).
``A = (\")``
; ...
?- [user].
``'"'(X,Y) :- write(X), write(Y).``
Error: syntax error, near '8' operator expected ''
true.
?- ``a'"'b.``
abtrue.
?- ``a'\"'b.``
abtrue.
?-

**Comment by infradig** [comment]
I'm not seeing *any* syntax error here.

**Comment by flexoron** [comment]
$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.15
?- ``op(700,xfx,'"').``
true.
?- [user].
``'"'(X,Y) :- write(X), write(Y).``
Error: syntax error, near 'D2' operator expected ''


Enter key pressed immediately after .... write(Y).\<Enter\>
the error message shows up.
This time it says ``... near 'D2' ...``

**Comment by infradig** [comment]
Odd.

**Comment by flexoron** [comment]
$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.15
?- op(700,xfx,'"').
true.
?- [user].
'"'(X,Y) :- write(X), write(Y).
Error: syntax error, near '' operator expected ''
true.
?- [user].
'"'(X,Y) :- write(X), write(Y).
true.
?- 

odd ... now it says near '' ...
entering it a second time, no error message

**Comment by flexoron** [comment]
you get the error message when defining operator first:
?- op(700,xfx,'"').
?- [user].
...

**Comment by infradig** [comment]
Did it exactly as you did, but no error.

**Comment by flexoron** [comment]
No error message
Trealla Prolog (c) Infradig 2020-2021, v1.18.15
?- [user].
'"'(X,Y) :- write(X), write(Y).
true.
?- op(700,xfx,'"').
true.
?- a'"'b.
abtrue.

**Comment by flexoron** [comment]
funny, now near 'D'
tried in Gnome-terminal(bash) and Alacritty(fish). Seems its not the terminal/shell problem.

?- op(700,xfx,'"').
true.
?- [user].
'"'(X,Y) :- write(X), write(Y).
Error: syntax error, near 'D' operator expected ''

**Comment by flexoron** [comment]
Alright, with version v1.18.18, the error message is gone.

$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.18
?- op(700,xfx,'"').
true.
?- [user].
'"'(X,Y) :- write(X), write(Y).
true.
?- a'"'b.
abtrue.

**Comment by flexoron** [comment]
hmm...here's the error message again:

Trealla Prolog (c) Infradig 2020-2021, v1.18.18
?- ``op(700,xfx,"'").``
true.
?- [user].
``'\''(X,Y) :- X = Y.``
Error: syntax error, near 'Wo6V' operator expected ''
true.
?- ``a'\''a.``
true.
?- ``a'\''b.``
false.
?- ``A'\''b.``
A = b.
?- ``a'\''B.``
B = a.
?-

**Comment by infradig** [comment]
Mac?

**Comment by flexoron** [comment]
No, AMD FX(tm)-8350 Eight-Core Processor (PC)

here a test in another nearly up-to-date Linux (Linux nutyx 5.15.11)

Trealla Prolog (c) Infradig 2020-2021, v1.18.19
?- [user].
``'\''(X,Y) :- X = Y.``
Error: syntax error, near '@' operator expected ''
true.
?- ``op(700,xfx,"'").``
true.
?- ``A'\''B.``
B = A.

**Comment by flexoron** [comment]
Another host: Intel Corporation Xeon E3-1200/2nd Generation I7
Clear Linux from Intel (5.15.11, too).

Compiler: clang 11.1
Trealla Prolog (c) Infradig 2020-2021, v1.18.19-dirty
?- [user].
``'\''(X,Y) :- X = Y.``
Error: syntax error, near '' operator expected ''


And fyi: gcc crash in this environment: gcc version 11.2.1
here:
gcc -Isrc -I/usr/local/include -DVERSION='"v1.18.19"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char    -c -o src/functions.o src/functions.c
during RTL pass: expand
src/functions.c: In function ‘fn_iso_copysign_2’:
src/functions.c:1137:1: internal compiler error: Segmentation fault
0x8efc75 crash_signal

**Comment by flexoron** [comment]
Devel branch seems ok
Trealla Prolog (c) Infradig 2020-2021, v1.18.19-6-ga70d1d-dirty
?- [user].
'\''(X,Y) :- X = Y.
true.

but now I get this clang warning:

clang -Isrc -I/usr/local/include -DVERSION='"v1.18.19-6-ga70d1d-dirty"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char    -c -o src/unify.o src/unify.c

src/unify.c:95:4: ``warning: expression which evaluates to zero treated as a null pointer constant of type 'cell *' (aka 'struct cell_ *') [-Wnon-literal-null-conversion]``

**Comment by infradig** [comment]
There's a change in the devel branch you should try, if you haven;t.

**Comment by flexoron** [comment]
Environment: PC/AMD, Linux LTS 5.10 (Manjaro),  gcc 11.1

Error message is gone again:
Trealla Prolog (c) Infradig 2020-2021, v1.18.20
?- [user].
``'\''(X,Y) :- X = Y.``
true.
?-  ``op(700,xfx,"'").``
true.
?- ``a'\''B.``
B = a.

**Comment by flexoron** [comment]
Environment: PC/Intel, Clear Linux 5.15.11, clang 11.1.0

clang warning is gone. Great!
error message, too:
Trealla Prolog (c) Infradig 2020-2021, v1.18.20
?- [user].
``'\''(X,Y) :- X = Y.``
true.
?- ``op(700,xfx,"'").``
true.
?- ``a'\''B.``
B = a.

FYI if interest, it is my performance platform and do compile/install nothing here but selected programs written in C.
https://www.phoronix.com/scan.php?page=article&item=macos12-windows-linux&num=6
https://clearlinux.org/about

**Comment by infradig** [comment]
I hadn't heard of Clear Linux before.

**Comment by flexoron** [comment]
a paradise for performance-oriented programming, for programmers like you.

**Comment by flexoron** [comment]
Environment: Clear Linux, gcc 11.2.1
Ironically flag -O3 or -O2  causing the compiler to crash.
Compiling with -O1, Trealla runs (error message free).
I'm thinking about to open a bug report here: https://github.com/clearlinux/distribution/issues
How you see it?
