### ISSUE TITLE
Syntax: Unescaped newline occurs in a quoted token

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#346]
```
?- writeq('
').
'\n'true. % unexpected
```
Expected: syntax error

In DEC10, the only rule for quoted tokens was that they end with a quote and twice the quote in between means a single quote. So any character could occur in between. However this produces much more harm, for reproduction and during interaction. Think of "invisible" spaces at the end of the line. Depending on the precise environment they may be here or not.

**Comment by infradig** [comment]
Clearly a mistake, thanks.

**Comment by infradig** [comment]
So no more...

main :- write('foo
  bar
  baz'), nl.

Scryer and gprolog give a syntax error here.

**Comment by UWN** [comment]
One more issue with this: Scryer, GNU, Ciao, IF, Minerva, ECLiPSe (-L iso) [all](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#2) produce an error immediately after the first newline is encountered within a single quoted token. In fact, 8.14.1.1 g states that after each character the input is parsed as a sequence of tokens. The two characters  `"'\n"` alone cannot be completed to form a valid token, thus the syntax error 8.14.1.3 k applies.

Only SICStus and IV wait for another single quote and then produce the error. Trealla currently waits  even longer first for that single quote and then for a single finishing dot as if everything would be fine.

So if you are stuck on the top level, and you cannot (over-) see the complete input then you are &mdash; öhm &mdash; stucked. (^C does not work either). On the other hand, in the above six systems, simply entering Return will free you and return the input in a consistent state.

**Comment by infradig** [comment]
The trealla top-level reads line at a time. So can only parse late.

**Comment by UWN** [comment]
>The trealla top-level reads line at a time. So can only parse late.
That is not the problem. Just:
```
Trealla Prolog (c) Infradig 2020-2021, v1.18.23
?- writeq('


'
).
```
So here are many, many lines it can read at a time. And still it does not react. It awaits the **token** dot. OTOH, read/1 alone reacts immediately.

**Comment by infradig** [comment]
By line i meant a complete input line with dot terminator. It will take
some reorganisation to change... i have made a start.

**Comment by UWN** [comment]
Closing, since `read/1` is OK. And the top level is subject to 1 NOTE f.

**Comment by UWN** [comment]
>  dot terminator.

It is not the token dot, see above, where a `.` declenches parsing even if it is "hidden" behing a % . And this % is either a comment percent or we are still within a single quoted token.

**Comment by infradig** [comment]
Yes i need to fix up ad-hocery. The interaction with GNU readline/history
needs to be considered as well.
