### ISSUE TITLE
Top level: Sudden exit with .

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#348]
```
Trealla Prolog (c) Infradig 2020-2021, v1.18.23
?- .
Error: syntax error, unexpected end of clause
ulrich@p0:~/iso-prolog$    % unexpected
```

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.24-dirty
?- .
Error: syntax error, unexpected end of rule
false.
?- halt.
~/trealla (devel) $

Maybe got fixed in the mix?

**Comment by UWN** [comment]
> Maybe got fixed in the mix?

Not in

```
Trealla Prolog (c) Infradig 2020-2021, v1.18.25
?- .
Error: syntax error, unexpected end of rule

real	0m2.187s
user	0m0.085s
sys	0m0.008s
```

(Called as `time ./tpl`)

**Comment by josd** [comment]
Here I get 
```
$ time ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.25
?- .
Error: syntax error, unexpected end of rule
false.
?-
```

**Comment by flexoron** [comment]
$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.25
?- .
Error: syntax error, unexpected end of rule
false.
?-

**Comment by UWN** [comment]
Déjà vu ? Heu, ...

OK, this time it's easier. It's my `.tplrc`. Without it, no problem.

**Comment by UWN** [comment]
Maybe this is a reminder for #296
