### ISSUE TITLE
string_concat/2 should be renamed to append/2

### ISSUE THREAD

**Issue by triska** [infradig/trealla#35]
The README mentions the predicate `string_concat/2`. However, it does not seem to be defined:

<pre>
<b>?- string_concat(Lss, Ls).</b>
Error: uncaught exception... error(existence_error(procedure,string_concat/2),string_concat/2)
false.
</pre>

In addition, it would be more useful to instead provide the predicate **`append/2`**, because it works for *all* lists, not only lists of characters.

**Comment by infradig** [comment]
I am removing string_concat/3. Once chars-list printing recogonizes strings it is not necessary.

**Comment by triska** [comment]
Perfect, thank you a lot! `append/3` is all that's needed!

It is really encouraging that well-known and versatile predicates like `append/3`, `reverse/2` etc., known to every Prolog beginner, can simply be used to reason about strings in your system! The compact representation combines this convenience with great efficiency.

**Comment by triska** [comment]
This is now excellently resolved, thank you a lot!
