### ISSUE TITLE
Question about loading a file

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#351]
Trealla Prolog (c) Infradig 2020-2021, v1.18.28
?- [nonexistent] ``;`` true.
uncaught exception: error(existence_error(source_sink,nonexistent),load_files/2)
?-
shouldn't that print true?

I ask because
?- false ``;`` [existent].
   true.

aka
?- [nonexistent] ``;`` [existent].

**Comment by infradig** [comment]
No Prolog system I know of would give true for the first one.

**Comment by flexoron** [comment]
okey

Trealla Prolog (c) Infradig 2020-2021, v1.18.28
?- [pn]  ``,`` p.
positive    true.
?- [pn] ``,`` [pn].
   true.
?- [pn] ``;`` [pn].
true ;
Segmentation fault (core dumped)

**Comment by flexoron** [comment]
Trealla Prolog (c) Infradig 2020-2021, v1.18.31
?- ``[pn];[pn];p,n.``
true ;
true ;
positive negative  true.
?-
