### ISSUE TITLE
File: comment needs space

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#359]
$ cat c.pl
``c. %c``
``cc.%cc``
``c. %c``

Trealla Prolog (c) Infradig 2020-2021, v1.18.31
?- ``[c].``
Error: syntax error, near '.%', operator expected 'cc.%cc
'
   true.
?- ``c.``
   true.
?- ``prompt unexpected``
?- ``c.``
true ;
true. %expected

OR
rejecting the file en bloc

**Comment by infradig** [comment]
Isn't this the same as #358?

**Comment by flexoron** [comment]
Im unsure what makes the difference between interactive and batch.

So every line in a file is the same as if entered at the prompt?

If this is true then the comment in a file needs a fullstop to be in sync with repl.
and it is indeed the same as 358

**Comment by infradig** [comment]
Well actually, maybe they are worthy of separate issues.

**Comment by flexoron** [comment]
?- [user].
c. %c
cc.%cc
Error: syntax error, near '.%', operator expected 'cc.%cc
'
   true.
?- c.
   true.
?- [user].
c. %c
   true.
?- c.
true ;
   true.
?-

**Comment by flexoron** [comment]
strange

Without error:

?- [user].
c. %c
   true.
?- c.
   true.
?- [user].
c. %c
   true.
?- c.
   true.
?-

**Comment by flexoron** [comment]
swipl messing around.

$ cat c.pl
c.
cc.,
c.
c.

$ swipl
?- [c].
ERROR: c.pl:2:5: Syntax error: Operator expected
true.

?- c.
true ;
true.

?-  ``c is true three times.``

**Comment by infradig** [comment]
Interesting, so SWI carries on after errors. GNU & Scryer abort and unload.

**Comment by infradig** [comment]
So is consulting a file an atomic transaction (all or nothing) or not? I
suspect it should be.

**Comment by flexoron** [comment]
yes but it seems SWI ignores the next line right after the error-line:
$ cat c.pl
c.
cc..
d.
c.

?- [c].
:
?- d.
ERROR: Unknown procedure: d/0

**Comment by flexoron** [comment]
my opinion:
from a discontinuos mode point of view 
it could be non-atomic and go on collecting good predicates known so far (those without the error and others without error)
and ignoring the error-predicate(s) with a warning.

**Comment by infradig** [comment]
Sounds dangerous, from a logic point of view.

**Comment by flexoron** [comment]
Not so dangerous when the file contains independent predicates.
On the other hand, a syntax error is an error and should be corrected,
so consulting a file is an atomic transaction.

**Comment by pmoura** [comment]
> Not so dangerous when the file contains independent predicates.
> On the other hand, a syntax error is an error and should be corrected,
> so consulting a file is an atomic transaction(from syntax error point of view).

Look again into the SWI-Prolog example you posted. The consulting goal **succeeds** despite the error. The danger here have nothing to do with (in)dependent predicates but with the error being missed. The error may have scrolled out of sight do to other output. Not to mention that not all file consulting goals happen at the top-level... It's even worse on systems like SWI-Prolog that allow arbitrary goals to be used as directives. Most users, seeing the errors, will fix them and reload, instead of restarting. Only that those arbitrary "directives" often have side-effects that will be repeated, resulting in subtle bugs.

**Comment by flexoron** [comment]
but the error pops up when you use the 'faulty' predicate:
$ cat c.pl
c.
cc..
d.
c.

?- [c].
ERROR: c.pl:2:2: Syntax error: Operator expected
true.
:
:
:
error message out of sight
:
?- cc.
ERROR: Unknown procedure: cc/0 (DWIM could not correct goal)

**Comment by flexoron** [comment]
Trealla Prolog (c) Infradig 2020-2021, v1.18.37
?- [c].
Error: syntax error, near '..', operator expected 'cc..
'
   true.
?- c.
uncaught exception: error(existence_error(procedure,c/0),c/0)

Resolved!

SWI worse indeed
$ cat c.pl
c.
cc..
. % ugly
d.
c.

?- [c].
ERROR: c.pl:2:2: Syntax error: Operator expected
Warning: c.pl:5:
Warning:    Clauses of c/0 are not together in the source-file
Warning:    Earlier definition at c.pl:1
Warning:    Current predicate: d/0
Warning:    Use :- discontiguous c/0. to suppress this message
true.

?- c.
true ;
true.

?- d.
true.

**Comment by flexoron** [comment]
sorry, too fast,  the reported issue still exist
$ cat c.pl
c.
cc.% cc

Trealla Prolog (c) Infradig 2020-2021, v1.18.37
?- [c].
Error: syntax error, near '.%', operator expected 'cc.% cc
'

**Comment by infradig** [comment]
Yes, havent looked at that.
