### ISSUE TITLE
Existence error sometimes indicates the wrong predicate

### ISSUE THREAD

**Issue by triska** [infradig/trealla#36]
Currently, I get:

<pre>
<b>$ ./tpl</b>
Trealla ProLog (c) Infradig 2020, v1.2.20
<b>?- append(Lss, Ls).</b>
Error: uncaught exception... error(existence_error(procedure,append/2),append/2)
false.
<b>?- x(Lss, Ls).</b>
Error: uncaught exception... error(existence_error(procedure,append/2),append/2)
false.
</pre>

The last error message should not mention `append/2`, because that was not used in the immediately preceding query. It should mention `x/2`.

**Comment by infradig** [comment]
Yes, there is currently a problem in the REPL in that it t gets stuck on
reporting the first exception.

**Comment by triska** [comment]
Perfect, thank you a lot!
