### ISSUE TITLE
hex_bytes/2 prevents logical reasoning about code

### ISSUE THREAD

**Issue by triska** [infradig/trealla#361]
Currently, we have:

<pre>
<b>?- Hs = "a", hex_bytes(Hs, [10]), Hs = "a".</b>
   Hs = "a".
</pre>

Yet, **a generalization fails**:

<pre>
<b>?-           hex_bytes(Hs, [10]), Hs = "a".</b>
   false.
</pre>

With the current state of the system, and Prolog tools in general, it is easy to ignore such issues as unimportant, but they will come back to haunt all programmers who want to use automated, tool-assisted development techniques once they become more widely available. In particular, a Prolog program could reason automatically about the exact fragments of a program that are responsible for failing queries. This only works if such fundamental logical properties are preserved by as many predicates as possible.

For this reason, it is also so important to be as strict as possible with the **types** a predicate accepts: The type error should give perfectly clear and valid information about the set of terms that are acceptable. Automated analysis tools must be able to rely on this information. The more superficially "accommodating" you make the predicates by accepting things beyond their actual types and domains, the more useless these tools will become.

**Comment by flexoron** [comment]
Excuse me, a stupid question
What are hex bytes? 0xABC = 'A', 'B', 'C' ?
Does something like hex_octs() exist?

**Comment by triska** [comment]
"hex" in this context means a string in Base16-encoding, such as `"03ffae"`.

Such strings are frequently used to specify hashes and signatures: They are a straight-forward way to write a list of bytes using only ASCII characters. For example, I get:

<pre>
<b>$ shasum
hello</b>
f572d396fae9206628714fb2ce00f72e94f2258f
</pre>

This would be represented as the Prolog string `"f572d396fae9206628714fb2ce00f72e94f2258f"`.  The corresponding list of bytes is:

<pre>
<b>?- hex_bytes("f572d396fae9206628714fb2ce00f72e94f2258f", Bs).</b>
   Bs = [245,114,211,150,250,233,32,102,40,113,79,178,206,0,247,46,148,242,37,143].
</pre>

Strings are the best encoding for text, especially if it is transient and short-lived, and occurs only in a specific context and not "globally" in a program. The reason is that we can easily use DCGs to parse and reason about lists. For longer-lived data that is referenced and used for its actual meaning in many places in a program, you would usually use atoms instead of strings.

A more compact encoding of lists of bytes is Base64, but it is not so straight-forward to encode and decode. You would use it especially if it pays off more (i.e., saves more space), such as for email attachments etc. that are usually longer than just a comparatively short hash or signature.

**Comment by flexoron** [comment]
ah ok .. conversion, thnx
hex_decs
When I think of bytes I have a more or less kinda abstract data type in mind

**Comment by triska** [comment]
"byte" in Prolog has a specific meaning. Quoting from the ISO standard:

<pre>
<b>7.1.2.1 Bytes</b>

B, a set of bytes, is a subset of I where:

B = {i E I | 0 =< i =< 255}
</pre>

So, a term of type `byte` is an integer between 0 and 255. The name `bytes` uses a plural `s` to denote a *list* of bytes.

**Comment by flexoron** [comment]
perfect! thank you.

**Comment by infradig** [comment]
Yeah, it's a bug.

**Comment by triska** [comment]
Perfect, thank you a lot, I am closing this issue!

Regarding the documentation:

<blockquote>
Convert a hexadecimal string to a codes-list where each code
 represents an integer 0..255 in value.
</blockquote>

This can be stated more compactly and also more meaningfully as:

<blockquote>
Convert a hexadecimal string to a list of <i>bytes</i>, i.e., integers between 0 and 255.
</blockquote>

In addition, I have recently uploaded a short video about the cryptographic functionality of Scryer Prolog that describes the design of its `library(crypto)`, I hope you find it useful for implementing similar predicates in Trealla:

**https://www.metalevel.at/prolog/videos/cryptography**

**Comment by infradig** [comment]
I saw some of the video, as i have others of yours. I wish time permitted
to watch more.

 No plans for general crypto functionality. The crypto_data_hash/3 allowed
getting rid of some predicates, which is always good.
