### ISSUE TITLE
cosmetic effect?

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#362]
Trealla Prolog (c) Infradig 2020-2021, v1.18.37
?- member(a,"ab").
true
``;``
``...``
``false.``

?- member(a,"ab").
true
;  false.  % semicolon entered

$ scryer-prolog 
?- member(a,"ab").
true
``;  ...``

?- member(a,"ab").
   true
;  false. % semicolon entered

**Comment by flexoron** [comment]
oh UWN mentioned it already #357

**Comment by UWN** [comment]
One general remark: Please put the entire transscript in a preformatted `<pre>` ... `</pre>` or a three backtick environment (` ``` ` ... ` ``` `). Otherwise the leading spaces are removed and since `call_nth/2` or so we had there some missing spaces. Currently we have:

```
Trealla Prolog (c) Infradig 2020-2021, v1.18.39
?- member(X,"abc").
   X = a
;   ... .
% here there is one space too much, not a big drama though
```

**Comment by UWN** [comment]
(Fixed in v1.18.40)

**Comment by flexoron** [comment]
@UWN, sorry, you're right.
I opened this issue mainly because Trealla prints ``false.`` while Scryer doesn't.
Now, clean formatted you see ``true`` not  indented as well
and on the other hand Scryer missing a ``.``

```
Trealla Prolog (c) Infradig 2020-2021, v1.18.40
?- member(a,"ab").
true
;  ... .
   false.
```
```
$ scryper-prolog
?- member(a,"ab").
   true
;  ...
?-
```
Sorry again but sometimes I'm confused because the prolog systems I can use varying (as you can see above)
and I can't assess these issues.

**Comment by UWN** [comment]
OK, I did not spot this in your original post. Maybe due to the different formatting

**Comment by flexoron** [comment]
was meant as highlighting.

So ``true should be indented`` and ``false. printed``? (semicolon not entered)
```
?- member(a,"ab").
   true
;  ... .
   false.
```

**Comment by UWN** [comment]
`false.` is superfluous. The `.` in `... .` finishes the answer.

**Comment by flexoron** [comment]
Not so good for the User Experience.

Every time I see ``false`` I feel alarmed.

Here in this case I was happy to got a ``true``.

So I stopped the query (``true<return>``)
and stopping cannot be false, or?

**Comment by UWN** [comment]
(It seems we have here something mixed up. So let me state everything again):

I agree that the answer should not be

```
?- member(a,[a,b]).
true                        
;  ... .
   false.
```

but is should be rather

```
?- member(a,[a,b]).
   true
;  ... .
```

**Comment by flexoron** [comment]
ok, I understand..a superfluous thing is a question of taste.

**Comment by flexoron** [comment]
Excuse me, just to get it right.

My understanding of 'superfluous' is this:

``1 + (2 + 3)`` <- superfluous parentheses (can be but does not have to)

```
writeq(+1^2).
+ (1^2)
```
According to conformity 277 it should be: ``+1^2``

Taking conformity test serious 
the parentheses in this case 
are not superfluous but rather
a misexposition or an error.

**Comment by UWN** [comment]
> Taking conformity test serious ...

You are right!

However, if you insist on a complete all or nothing approach then the purpose of a standard is missed entirely. Think of [#286](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#286) which is just a problem of the codex alone. No one misinterprets this, so it is not really an urgent matter either. Problems only surface if systems are run. And running the standard is much more complex: Someone needs to read it, think of *all* possible interpretations (and not only the intended one) etc. Similarly, the table contains distinctions that are not present in the standard at all: misinterpretations, rejections, write syntax deviations. Formally, they are all errors but with different degree of seriousness. Write syntax deviations will only bite if this syntax is used in another context than just rereading it with read/1. Rejections are relatively easy to detect. Misinterpretations are the most serious problems.

(The effect of our discussion here is that the issue in question has still not been fixed.)

**Comment by flexoron** [comment]
Because I'm not member of THE PROLOG-PROJECT
(skill not acquired, barely sufficient)
I remain modest and should just insist on
"Don't bite if used in another context" 

"What we have been considering are two alternative ways of explaining
the meanings of sentences of a language in terms of how we establish
them as true; and in terms of what is involved in accepting them as true.
They are complementary in that both are needed to give an account of
the practice of speaking the language."
(Michael Dummett, The Seas of Language, Oxford 1993)
