### ISSUE TITLE
Syntax: prefix - in functional notation

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#368]
When the argument of (-)/1 is another operator, the `-` is output currently in functional notation instead of operator notation (including examples mentioned within #363):

```
Trealla Prolog (c) Infradig 2020-2021, v1.18.41
?- writeq(-(a*b)).
-(a*b)   true.
?- writeq(-(-a)).
-(- a)   true.
?- writeq(-(-(-a))).
-(-(- a))   true.
?- writeq(-(-(1))).
-(- (1))   true.
?- writeq(-(-1- +1)).
-(-1-(+1))   true.
?- writeq(-(-1-1)).
-(-1-1)   true.
?- writeq(-(-(-a))).
-(-(- a))   true.
```

All occurrences of `-(` of prefix `-` are here functional notation. Note that `-(+1)` in `-(-1-(+1))` is not in functional notation as it is an infix, but the round brackets are also not expected.

[7.10.5 f](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/draft-7.10.5#f):

> f) Else if Term has a principal functor which is not
a current operator, or if there is an effective write-
option ignore_ops(true), then the term is output in
functional notation (6.3.3) ...

Thus this subclause does not apply but h does.

**Comment by UWN** [comment]
Now, no unexpected functional notation, but too many round brackets:

```
?- writeq(-(-a)).
- (- a)   true.
?- writeq(-(-(-a))).
- (- (- a))   true.
?- writeq(-(-(1))).
- (- (1))   true.
?- writeq(-(-1- +1)).
- (-1-(+1))   true.
?- writeq(-(-1-1)).
- (-1-1)   true.
?- writeq(-(-(-a))).
- (- (- a))   true.
```

**Comment by infradig** [comment]
Why is this seemingly wrong...

~/trealla (devel) $ tpl
- experimental Trealla -
?- writeq(-(-1-1)).
- -1-1   true.
?-

Every other Prolog gives...
- (-1-1)

Note space after leading - op. It seems to me the parentheses are
superfluous ie. no ambiguity. I must be wrong though.

**Comment by UWN** [comment]
Only one case left!

**Comment by infradig** [comment]
Which? Apart from redundant parens...

~/trealla (devel) $ scryer-prolog -f w.pl -g main,halt
- - a
- (1)
- -1
- - - a
- - (1)
- (-1- +1)
- (-1-1)
- - - a
~/trealla (devel) $ tpl -f w.pl -g main,halt
- -a
- (1)
- -1
- - -a
- - (1)
- (-1-(+1))
- (-1-1)
- - -a
~/trealla (devel) $ cat w.pl
main :-
writeq(-(-a)), nl,
writeq(-(1)), nl,
writeq(-(-1)), nl,
writeq(-(-(-a))), nl,
writeq(-(-(1))), nl,
writeq(-(-1- +1)), nl,
writeq(-(-1-1)), nl,
writeq(-(-(-a))), nl.
~/trealla (devel) $

**Comment by UWN** [comment]
> Which? Apart from redundant parens...

The one that I did not strike through. So there are redundant round brackets. (Maybe you use another interface, I am using the webinterface)

```
Trealla Prolog (c) Infradig 2020-2021, v1.18.47
?- writeq(-(-1- +1)).
- (-1-(+1))   true. % unexpected extra round brackets
```

**Comment by UWN** [comment]
To keep the example in sync with the subject:

```
?- writeq(-(-1- -a)).
- (-1-(-a))   true. % unexpected extra round brackets around -a
```

**Comment by infradig** [comment]
Looking into it.

What's your opinion on...

  $ scryer-prolog
  ?- writeq((1*2)/(3*4)), nl.
  (1*2)/(3*4)

Scryer is the only Prolog I can find that does this

* tested SWI, GNU, Cx, Ciao

**Comment by UWN** [comment]
Agreeed! What Scryer is very good at from the very beginning is `read/1`-ing.

**Comment by UWN** [comment]
```
Trealla Prolog (c) Infradig 2020-2021, v1.19.1-2-gcd9b5
?- writeq(-(-1- -a)).
- (-1-(-a))   true. % unexpected
?- writeq(-(-1- +a)).
- (-1- +a)   true. % expected
?- writeq(-(-1- +1)).
- (-1- +1)   true. % expected
```

Why is `-` and `+` treated differently as prefix operators in `writeq(-(-1- -a)).`? [7.10.5] h 2 iv does not apply here.
