### ISSUE TITLE
writeq: syntax error not revealed

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#369]
Trealla Prolog (c) Infradig 2020-2021, v1.18.43
```
?- op(100,xf,'').
   true.
?- writeq(0'').
0''   true.

?- writeq(0''').
39   true.

?- writeq(0''abc).
0''   true.  % syntax error expected?
?-
```

**Comment by infradig** [comment]
The last one is a de facto standard that has been discussed here
previously, ad nauseum, and won't be discussed here again in this
particular case.
