### ISSUE TITLE
current_op(200,X,\\) unkown operator

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#373]
Trealla Prolog (c) Infradig 2020-2021, v1.19.1-2-gcd9b5
```
?- current_op(200,X,Y).
:
;  X = xfy, Y = (\\)  % ???
;  X = fy, Y = (\\)   % see below Y = (\)
:
```

Scryer, GNU, SWI
```
?- current_op(200,X,Y).
:
;  X = fy, Y = (\)
:
```

**Comment by infradig** [comment]
Seems to be a printing error.

**Comment by flexoron** [comment]
```
xfy (\\)
what kind of operator should it be?
- X is 1\1.
uncaught exception: error(type_error(evaluable,(\\)/2),(is)/2)
```

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.19.1-8-ga8c3c-dirty
?- X = (\).
   X = (\\).
?-

**Comment by infradig** [comment]
xfy \ is for internal use only.

**Comment by flexoron** [comment]
ok, should I change the headline to

"current_op(200,xfy,\) internal operator exposed"

or
close the issue because it is just a harmless printing error?

**Comment by infradig** [comment]
Well the fy (\) printing as (\\) is an error to be fixed.

The xfy (\\) is just printing an operator you don't know about.

So just leave it as is.

**Comment by flexoron** [comment]
Trealla Prolog (c) Infradig 2020-2021, v1.19.6
```
?- current_op(200,X,Y).
Error: syntax error, invalid quoted character, line 13
   X = xfx, Y = (**)
```
still in stage WIP?

**Comment by infradig** [comment]
Not seeing this.

**Comment by flexoron** [comment]
Henceforth neither do I.

Trealla Prolog (c) Infradig 2020-2021, v1.19.9

```
?- current_op(200,X,Y).
:
;  X = fy, Y = (\)
:
```
