### ISSUE TITLE
Syntax: internal chars representation leaking to the outside

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#374]
```
Trealla Prolog (c) Infradig 2020-2021, v1.19.2-3-g132fd6
?- [L,'\'']==[L|"'"].
   true.
?- writeq([L|"'"]).
[_0|"\'"]   true. % could be compact as above
?- writeq([L,'\'']).
[_0,'\'']   true. % leak of representation
?- writeq([L,a,b,c]).
[_0,a,b,c]   true. % leak of representation
?- [L,a,b,c]=[L|"abc"].
   true.   % expected
?- writeq([L|"abc"]).
[_0|"abc"]   true. % expected
```

**Comment by infradig** [comment]
> ?- writeq([L,a,b,c]).
> [_0,a,b,c] true. % leak of representation

Do you want "abc" here?

**Comment by UWN** [comment]
> Do you want "abc" here?
Yes,

What **has to be** here is the same as for `writeq([L|"abc"]).` If it is different, then it is a leak.

**Comment by UWN** [comment]
There is still a leak of representation:

```
?- writeq([L|"'"]).
[_0|"'"]   true.
?- writeq([L,'\'']).
[_0,'\'']   true.
```

These leaks are the worst when debugging - which for me means replacing some part by some equivalent part and then looking if nothing changed. But this noise here would be very distracting.

**Comment by UWN** [comment]
( `[L|"'"]` still present) It hurts to write this as `[L,'\'']` doesn't it?

**Comment by infradig** [comment]
Do want this...

?- writeq([L,'\'']).
[_0,'\'']   true.

or this

?- writeq([L,'\'']).
[_0|"'"]   true.

**Comment by infradig** [comment]
Sorry, this...

?- writeq([L,'\'']).
[_0,'\'']   true.

or this...

?- writeq([L,'\'']).
[_0|"'"]   true.

**Comment by infradig** [comment]
Ugh, formatting on github. Forget that.

**Comment by UWN** [comment]
No formatting error, just

```
?- [L|"'"] = [L,'\''].
   true.
?- writeq([L,'\'']).
[_0,'\'']   true.

```
