### ISSUE TITLE
string_hex/2 and string_octal/2 are better subsumed by format_//2

### ISSUE THREAD

**Issue by triska** [infradig/trealla#38]
To subsume and generalize *ad hoc* predicates such as `string_hex/2` and `string_octal/2`, and also to encourage more convenient formalisms for describing strings, I recommend the non-terminal **`format_//2`**.

`format_//2` is like `format/2`, except that it declaratively *describes* a string, using a given format string and arguments.

For instance, using `format_//2` and the `~Nr` specifier to specify a number in a given *radix*, we can use:

<pre>
<b>?- phrase(format_("~16r", [12]), Ls).</b>
   Ls = "c".
<b>?- phrase(format_("~8r", [12]), Ls).</b>
   Ls = "14".
</pre>

This easily generalizes to any radix between 2 and 36.

Together with the new predicate `phrase_to_file/2`, such versatile DCG nonterminals are very well suited for declaratively describing complex strings, and efficiently emitting them to files when needed.

**Comment by infradig** [comment]
I know what you mean, I just needed a quick way to parse hex numbers that
HTTP chunked gives you. Now you'll probably say that HTTP should be parsed
by a DCG grammar...

**Comment by infradig** [comment]
I'm not removing them for now, but have renamed them as hex_chars/2 &
octal_chars/2 to mirror number_chars/2 and get away from the *string* usage
that is so SWI-Prolog like.

I will look into format_//2, so keep this open.

**Comment by infradig** [comment]
I plan to include your format_//2 in a coming release. Thanks for placing it in the public domain.

**Comment by triska** [comment]
Very nice, thank you a lot!
