### ISSUE TITLE
Multifile loading ignores choice point

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#381]
$ cat a.pl
a :- c.
c :- write(c).

$ cat b.pl
a :- d.
d :- write(d).

```
v1.19.16

$ tpl
?- [a],[b].
   true.
?- listing.
a :- c.
a :- d.
c :- write(c).
d :- write(d).
   true.
?- a.
c   true.
?-
% based on listing/0, expecting
?- a.
c   true
;d  true.
```
and
```
?- xyz:a.  % ???
c   true.
```

**Comment by pmoura** [comment]
Is this a top-level bug? Interesting that the Logtalk tests for the `multifile/1` directive don’t catch it.

**Comment by infradig** [comment]
It should have failed like the example, from what I can see. But it didn't.
