### ISSUE TITLE
read_term_from_chars/2 unexpected error/loops

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#384]
```
ulrich@TU-Wien:/opt/gupu/trealla$ ./tpl -f
Trealla Prolog (c) Infradig 2020-2021, v1.19.19
?- read_term_from_chars("a b",T).
uncaught exception: error(syntax_error(operator_expected),read_term_from_chars/2) % expected
?- read_term_from_chars("",T).
*loops* % unexpected
```
Sometimes (with more things around) I get also the unexpected `type_error(chars, [])` which is cannot be for two reasons:

1. `chars` isn't a type to be reported, it is either `list` or `character`.
2. The culprit `[]` is in fact of type `chars`

**Comment by UWN** [comment]
```
ulrich@p0:~/ftp/trealla-prolog$ cat t3.pl
:- initialization(catch(read_term_from_chars([],_),error(syntax_error(_),_),fail)).
ulrich@p0:~/ftp/trealla-prolog$ /opt/gupu/trealla/tpl -f t3.pl
uncaught exception: error(type_error(chars,[]),read_term_from_chars/2)
Trealla Prolog (c) Infradig 2020-2021, v1.19.19
?- read_term_from_chars([],_).
```

Note that the error does not always appear on the top level.

**Comment by UWN** [comment]
Now.,

```
ulrich@p0:/opt/gupu/trealla$ ./tpl -f
Trealla Prolog (c) Infradig 2020-2021, v1.19.23
?- read_term_from_chars("",T).
   T = []. % unexpected
?- read_term_from_chars([],T).
* loops *  % unexpected
```

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.19.23
?- X = "".
   X = [].
?- read_term_from_chars("",T).
   T = [].
?- read_term_from_chars([],T).
   T = [].

Is this not right?

**Comment by UWN** [comment]
> Is this not right?

No, the term `[]` is represented by the string `"[]"` and related ones modulo layout and quoting.

**Comment by UWN** [comment]
After recloning and recompiling: it's gone, except for this `T = []`

**Comment by infradig** [comment]
So *read_term_from_chars("",T)* should throw?

**Comment by infradig** [comment]
Or return T=end_of_file ?

**Comment by UWN** [comment]
As you like. I would say, rather syntax error

**Comment by UWN** [comment]
Precedent:

```
?- number_chars(N,[]).
uncaught exception: error(syntax_error(incomplete),number_chars/2)
```


So when there is no number to read it is a syntax error. And when there is no term to read, why `end_of_file`?

**Comment by infradig** [comment]
GNU Prolog gives T=end_of_file

**Comment by pmoura** [comment]
Other systems (e.g. SWI-Prolog, Logtalk) return the `end_of_file` term in this case (empty input list).

**Comment by pmoura** [comment]
The `number_chars/2` predicate expects a number. The read from chars/codes predicates are more akin to reading from a stream.

**Comment by infradig** [comment]
I'd prefer to go with T=end_of_file for compatibility.

**Comment by UWN** [comment]
It's still T = [].
