### ISSUE TITLE
dif/2 loops on Ubuntu 14.04.6 LTS

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#386]
```
?- dif(A,B),A=[A|A].
*loops
```

**Comment by UWN** [comment]
It is hard to identify other problems as long as there are such loops.

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.19.23
?- dif(A,B),A=[A|A].
   A = [_0|_0].
?-

**Comment by UWN** [comment]
```
ulrich@p0:/opt/gupu/trealla$ git pull&&make OPT=-std=c99 NOSSL=1&&kill %1;date;git describe;time ./tpl
Already up-to-date.
make: Nothing to be done for `all'.
bash: kill: %1: no such job
Thu Jan 13 11:55:58 CET 2022
v1.19.23
Trealla with .tplrc
Trealla Prolog (c) Infradig 2020-2021, v1.19.23
?- dif(A,B),A=[A|A].
*loops*
```

**Comment by infradig** [comment]
Somethings screwy with git. Try removing the directory and re-cloning.

**Comment by UWN** [comment]
OTOH, same as your result on `g1`.

**Comment by infradig** [comment]
Looks like your Ubuntu git is the problem.

**Comment by UWN** [comment]
(While recloning & recompiling which takes quite some time ...) This is on `p0`, an Ubuntu 14.04.6 LTS.

**Comment by josd** [comment]
Is also fine here
```
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.19.23
?- dif(A,B),A=[A|A].
   A = [_0|_0].
?-
```
```
$ uname -srmo
Linux 4.19.104-microsoft-standard x86_64 GNU/Linux
```

**Comment by UWN** [comment]
On p0, an  Ubuntu 14.04.6 LTS the loop is still there after recloning

**Comment by UWN** [comment]
Is there a way how I can put labels on items? Or, say, just some specific labels? Such that you can close them, but I still get an overview of the unsolved issues (think of #253)? Alternatively, I could just use the pre-github method I used for [SICStus](http://www.complang.tuwien.ac.at/ulrich/sicstus-prolog/), [SWI](http://www.complang.tuwien.ac.at/ulrich/swi-prolog/) and some other systems.

**Comment by UWN** [comment]
Now, in v1.19.27 it is really gone.

**Comment by infradig** [comment]
I am closing all issues related to dif/2 and won't accept new ones.
Attributed variables is still work in progress, one that I have no time
look at unfortunately.

**Comment by UWN** [comment]
This is a pity, you could have with really small effort a correct `dif/2` implementation.

In any case, I am now putting a label to all those closed items that I consider still open. The label is the only solution to:

```
?- phrase(("U",{_=a},"W",{_=b},"N",{_=c},"_",{_=d},"open"),Label).
```

However, you are also [locking issues](https://github.com/infradig/trealla/issues/339). So should this happen again, I am off this site.

**Comment by infradig** [comment]
The problem is not dif.pl (that's a copy of Scryer's code). It's the
internal handling to do with attvars needs work.

**Comment by UWN** [comment]
Just note that the implementation of between/3 in Scryer [was incorrect](https://github.com/mthom/scryer-prolog/issues/1186). Often, many aspects are here at stake.
