### ISSUE TITLE
is_string/1 exposes internal representation details to Prolog

### ISSUE THREAD

**Issue by triska** [infradig/trealla#39]
Currently, I get:

<pre>
<b>?- Ls = "abc", Ls == [a,b,c], is_string(Ls).</b>

Ls = "abc"

true
</pre>

However, I also get:

<pre>
<b>?- Ls = [a,b,c], Ls == [a,b,c], is_string(Ls).</b>
false.
</pre>

So, on the one hand, Prolog states that `"abc"` is the same term as `[a,b,c]`, which works exactly as expected. However, on the other hand, it tells us that `"abc"` is a string, whereas `[a,b,c]` is not. In other words, an internal representation detail is unexpectedly exposed to the Prolog level.

Instead of distinguishing between the representations, I expect rather the opposite development: Ideally, `[a,b,c]` should *automatically* be represented in the most compact way possible, no matter how it appears in programs, whether as `[a,b,c]` or `"abc"` etc. Even if I write `T = [X|Xs], X = a, Xs = [b,c]`, a (future) compacting garbage collector could replace `T` by an efficiently allocated string, using only 3&nbsp;bytes.

**Comment by infradig** [comment]
I've removed it from the docs. If I end up not needing it I will remove it.

**Comment by triska** [comment]
This is a good solution: It may be useful for internal testing, but not as a publicly visible (documented and advertised) predicate.

Thank you a lot!
