### ISSUE TITLE
DCG incomplete

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#397]
```
?- phrase((("V"|"U")), L).
   L = "V". % unexpectedly incomplete, missing L = "U"
?- phrase((("V";"U")), L).
   L = "V". % unexpectedly incomplete, missing L = "U"
```

**Comment by infradig** [comment]
Changing...

phrase_((A | B), S0, S) :-
    (  phrase(A, S0, S) ; phrase(B, S0, S)  ).

to...

phrase_((A | _), S0, S) :-
  phrase(A, S0, S).
phrase_((_ | B), S0, S) :-
  phrase(B, S0, S).

Seems to work. So why is the problem now.

**Comment by infradig** [comment]
Note...

?- phrase((("V";"U")), L).
   L = "V".
?-

has the same problem.

**Comment by infradig** [comment]
Ok, seems to be an over-ambitious cut in an if-then-else. For a while @paulom has been mentioning this, but without a compact easily reproducible example it has not been possible to track down. Seems like this is it.

**Comment by infradig** [comment]
Super-simple reduction...

~/trealla (devel) $ cat disj.pl
f(1) :- !.
f(2).

test :-
(f(N) ; f(N)),
writeq(N), nl.

And then...

~/trealla (devel) $ tpl -f disj.pl
?- test.
1
   true.
?- % Note choice-point in 'test' has gone

~/trealla (devel) $ scryer-prolog -f disj.pl
?- test.
1
   true
;  1
true.
?-

I don't know how such a basic error has been undetected before.

**Comment by infradig** [comment]
Of course this works...

test :-
(call(f(N)) ; f(N)),
writeq(N), nl.

**Comment by infradig** [comment]
Odd, seems like it's actually a top-level artifact...

~/trealla (devel) $ tpl
?- forall(phrase((("V";"U")), L), (writeq(L), nl)).
"V"
"U"
   true.
?- findall(L, phrase((("V";"U")), L), Ls).
   Ls = ["V","U"].
?- phrase((("V";"U")), L).
   L = "V".
?-

Same with disj.pl

**Comment by UWN** [comment]
```
?- phrase(([]|[]), L).
   L = [].
```

**Comment by UWN** [comment]
```
?- [user].
myrun2 :-
   phrase(("V"|"U"), L),
   writeq(L),nl,
   false.

   true.
?- myrun2.
"V"
   false.
```

Et donc : It is not the poor top level but, er, something else.

**Comment by infradig** [comment]
To be clear. It's the lack of an initial guarding choice point at the top
level  that causes the problem. It used to have this as part of some setup
code, but that got removed last month I think.

**Comment by infradig** [comment]
| ?- phrase(([]|[]), L).
| L = [].

Assuming you're not refering to the disjunction problem, do you want L =
"". That sis should [] always display as "" if dq =chars mode is on?

**Comment by UWN** [comment]
It seems rather better to be `[]` because otherwise it would also show for 'regular' lists. Instead of

```
?- append(As,Bs,[1,2]).
   As = [], Bs = [1,2]
;  As = [1], Bs = [2]
;  As = [1,2], Bs = []
;  false.
```

it would now be

```
?- append(As,Bs,[1,2]).
   As = "", Bs = [1,2]
;  As = [1], Bs = [2]
;  As = [1,2], Bs = ""
;  false.
```
