### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by triska** [infradig/trealla#4]
The README mentions:

<blockquote>
Atoms (<b>synonymous with strings</b>) ...
</blockquote>

However, "strings" should better be used to denote **lists of characters** (or, as a less readable alternative, lists of character&nbsp;<i>codes</i>).

The intended use case of Prolog is efficient and convenient reasoning about text, especially using DCGs, and especially using lists of characters. Ideally, the following succeeds:

<pre>
<b>?- "abc" = [a,b,c].</b>
true.
</pre>

In every ISO Prolog system, this works if the the flag `double_quotes` is set to `chars`.

In the example above, the list `"abc"` is called a string.

**Comment by infradig** [comment]
I admit to using the term loosely and will change the README.
