### ISSUE TITLE
Quirk

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#412]
```
v1.20.8

?- [user].
c^[.
Error: syntax error, near 'perator expected 'c

rue.
```
Input:  c\<escape\>.
Quirk:  '``perator`` and ``rue``

and a little more:
```
?- [user].
^[^.
Error: syntax error, incomplete statement, line 2 ' ?- halt.

$
```
Input: \<escape\>^.
Quirk: ``prompt``

**Comment by infradig** [comment]
Don't they all do this? A peculairityof ansi escape codes on terminal input.

**Comment by infradig** [comment]
CTRL-[ is the start of an ANSI escape sequence, it will always swallow the
next input character.

**Comment by flexoron** [comment]
yes, right, found by chance.
amazingly true, I mean rue. I wonder why it hits true.
