### ISSUE TITLE
UTF-8: Some Unicode need space separator

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#419]
```
?- C = 𝄡.     % U+1D121 (119073), musical symbol C clef
   C = '𝄡'.

?- G = 𝄞.
Error: syntax error, missing operand or operator

?- G = 𝄞 .    % U+1D11E (119070), G clef
   G = '𝄞'.
```

**Comment by triska** [comment]
The ISO standard defines the notion of a **solo character**:

<pre>
6.5.3 Solo characters

solo char (* 6.5.3 *)
   = cut char (* 6.5.3 *)
   | open char (* 6.5.3 *)
   | close char (* 6.5.3 *)
   | comma char (* 6.5.3 *)
   | semicolon char (* 6.5.3 *)
   | open list char (* 6.5.3 *)
   | close list char (* 6.5.3 *)
   | open curly char (* 6.5.3 *)
   | close curly char (* 6.5.3 *)
   | head tail separator char (* 6.5.3 *)
   | end line comment char (* 6.5.3 *) ;

...

<b>A solo character need not be separated from the previous and
following tokens by a layout character or comment.</b>
</pre>

Maybe this has something to do with this?

Note that if for example `cut char` were *not* a solo character, then we would have to write:

<pre>
p :- ! .
</pre>

instead of:

<pre>
p :- !.
</pre>

**Comment by flexoron** [comment]
A problem, too?
```
?- _c = c.
   _c = c.

?- _𝄡 = c.
Error: syntax error, near '𝄡', operator expected ''
```

**Comment by infradig** [comment]
> ?- _𝄡 = c.

> Error: syntax error, near '𝄡', operator expected ''

Variable names are composed of underscores or alphanumeric characters. As
𝄡 is not an alpha by Unicode classification it is an error.

**Comment by infradig** [comment]
I don't know why the difference in treatment for the C-Clef vs. G-Clef, I
can't see anything.

**Comment by flexoron** [comment]
``_𝄡 = c. Somehow it makes not really sense; for example there is no atom_upper(𝄡,C).  etc.``

```
First case
Interesting, SWI prints the space when displayed:

?- G = 𝄞.
G = 𝄞 .

```

**Comment by infradig** [comment]
SWI:

> ?- G = 𝄞 .   % Note space
> G = 𝄞 .

Yes, Trealla *should* do this too.

**Comment by flexoron** [comment]
Yes, swi processing both inputs(with and without space).

There are other quirks. Enter this, bring it back with history and try to remove the term (with backspace).
Here, the readline does  remove, still it looks like the sign has been shifted a bit to the left(and  stays visible).
```
?- ᷕ = F.  % no space between prompt and sign
   F = 'ᷕ'.
?- ᷕ       % term has been removed with bs but sign stays visible 

```

**Comment by infradig** [comment]
It's not a charcter so can't be part of a variable name. It's clasified as So (symbol other).
BTW some characters can have no upper case. Some can have no lower case. Some can be both, as far as I rcall anyway.

> `_𝄡 = c. Somehow it makes not really sense; for example there is no atom_upper(𝄡,C). etc.`
> 
> ```
> First case
> Interesting, SWI prints the space when displayed(without quoting):
> 
> ?- G = 𝄞.
> G = 𝄞 .
> ```

**Comment by flexoron** [comment]
```
U+1D120 has to be 'space-bordered'(pre/post space):

?- D120 = 𝄠 . % pre/post space
   D120 = '𝄠'.

?- D120=𝄠 .   % no pre-space

Error: syntax error, near '=𝄠', operator expected ''

Question: Who is the operand missing the operator?
```
```
U+1D121 and U+1D122 need no spaces

?- D121=𝄡.
   D121 = '𝄡'.

?- D122=𝄢.
   D122 = '𝄢'.

then U+1D123 again, space-bordered

?- D123  = 𝄣 .   % same as D120
   D123 = '𝄣'.
```

**Comment by infradig** [comment]
?- D120 = 𝄠 . % pre/post space
   D120 = '𝄠'.

?- D120=𝄠 .   % no pre-space
Error: syntax error, near '=𝄠', operator expected '

These are *both* correct as 𝄠 is a symbol. The only thing wrong is it
should print (𝄠) as the answer.


The error is why 𝄡 doesn't do the same. That is, why it doesn't
require a pre/post space.

**Comment by flexoron** [comment]
Perhaps the reason:
```
Bit-patterns

𝄡 111100001001110110000100 10100001
𝄞 111100001001110110000100 10011110

In function: get_token()

       while (*src) {
                static const char *s_delims = "!(){}[]|_,;`'\"";
                 :
                ch = peek_char_utf8(src);

                if (strchr(s_delims, ch) ||   ....  HERE is the problem 


Function peek_char_utf8(), get_char_utf8()

the bit-pattern of 𝄡 10100001 returns hex 0x21 = '!' /* A Delimiter */
the bit-pattern of 𝄞 10011110 returns hex 0x2e = record separator

get_char_utf8()
               :
               } else if ((ch & 0b10000000) == 0b10000000) {
                        n <<= 6;
                        n |= ch & 0b00111111;
               :
```

**Comment by infradig** [comment]
I already have a fix, just not uploaded yet. I was waiting to clarify
something related. I will do it today.

**Comment by flexoron** [comment]
Cool!  But be cognisant, there're abstract bugs in there.
