### ISSUE TITLE
tpl: runtime.c:138: create_vars: Assertion `!g->overflow' failed.

### ISSUE THREAD

**Issue by triska** [infradig/trealla#42]
With `as.pl` defined as:

<pre>
as --> [].
as --> [a], as.
</pre>

I get:

<pre>
<b>$ ./tpl as.pl </b>
Trealla ProLog (c) Infradig 2020, v1.2.34
<b>?- length(_,E), writeln(E), N is 2^E, length(Ls, N), phrase(as, Ls), false.</b>
0
1
2
tpl: runtime.c:138: create_vars: Assertion `!g->overflow' failed.
Aborted
</pre>

**Comment by infradig** [comment]
This is now crashing on E = 15.

**Comment by infradig** [comment]
I have reduced the max number of vars from 65535 to 32767 for now and it finishes cleanly. There is some memory error in going above that, not sure why, will take more digging (later).

**Comment by triska** [comment]
Very nice, thank you a lot!
