### ISSUE TITLE
Variable unification, result not displayed

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#420]
v1.20.12
```
?- _x = x.
   _x = x.

?- __x = y.
   true.  % failed?  __x = y?
```
scryer, swi : displays __x = y.
trealla, gnu: true resp. yes

well, it seems not really an error 
```
:- __x = y, write(__x).
y   true.
```

**Comment by infradig** [comment]
Hah, I used to use two leading underscores for some internal bookkeeping,
so didn't want to dump them with results. I don't do that anymore so should
remove that test.

**Comment by flexoron** [comment]
Alienation: next time 10 years in prison.
