### ISSUE TITLE
Syntax: defect yields true

### ISSUE THREAD

**Issue by flexoron** [infradig/trealla#422]
v1.20.14
```
?- !;!,;!.
   true.
?-
```

**Comment by infradig** [comment]
You can see what's happened here...

?- X = (!;!,;!).
   X = (!;!,(;)).
?-

**Comment by flexoron** [comment]
ok, thanx.

**Comment by infradig** [comment]
I still think it's wrong!

**Comment by flexoron** [comment]
fixed with v1.20.20
?- !;!,;!.
Error: syntax error ...
