### ISSUE TITLE
Ugly crash when abusing modules.

### ISSUE THREAD

**Issue by ACleverDisguise** [infradig/trealla#47]
I know modules aren't done yet, but a crash is probably not desired behaviour:

```
$ tpl
Trealla ProLog (c) Infradig 2020, v1.2.34
?- foo:bar.
Segmentation fault (core dumped)
$
```

Minor glitches like this aside, this is a great little interpreter.  I'm evaluating it as something for certain kinds of embedded systems.  (Bare metal embedded, not SoC funky PC form factor "embedded".)

**Comment by infradig** [comment]
Interesting  idea, I have thought of doing a similar thing but don't have
the time. Let me know if you go anywhere with it, and if I can help with
any changes let me know.

**Comment by ACleverDisguise** [comment]
I'll do that.  I think there's room for a decently-performing Prolog in larger embedded spaces.  My target's the higher end STM32L4 or H7 line.
