### ISSUE TITLE
puzzle.pro in Scryer Prolog

### ISSUE THREAD

**Issue by triska** [infradig/trealla#5]
The reason `puzzle.pro` does not compile in Scryer Prolog is that it is saved with `DOS` file&nbsp;conventions. It works as expected if you convert it to Unix line endings, and remove the inclusion of `library(apply)`, which does not exist in Scryer&nbsp;Prolog.

Also, Scryer Prolog provides `time/1` in `library(time)` to measure the CPU time of a goal.

**Comment by infradig** [comment]
Thanks.

**Comment by infradig** [comment]
Yes, removing library(apply) for maplist works! Yap requires it, but I guess that doesn't really matter anymore.
