### ISSUE TITLE
running code from http://alain.colmerauer.free.fr/alcol/ArchivesPublications/Equation4/Equation4.pdf

### ISSUE THREAD

**Issue by josd** [infradig/trealla#51]
While trying to run the code from http://alain.colmerauer.free.fr/alcol/ArchivesPublications/Equation4/Equation4.pdf
which is attached as equation4.txt but should be renamed to equation4.pl I am getting
```
$ tpl -g "racines([[1,0],[-10,0],[35,0],[-50,0], [24,0]],Z), writeln(Z), halt" equation4.pl
Error: uncaught exception... error(instantiation_error,=../)
```
This exception can be reproduced with
```
$ tpl
Trealla ProLog (c) Infradig 2020, v1.2.41-9-g0570
?- a(b,c) =.. [X].
Error: uncaught exception... error(instantiation_error,=../)
```
and I think it should be
```
?- a(b,c) =.. [X].
false.
```
After working around by writing `T =.. [F]` as `T =.. Q, Q = [F]` and similarly for the 2 other `T =..` cases
it seems to run a while and then abort
```
$ tpl -g "racines([[1,0],[-10,0],[35,0],[-50,0], [24,0]],Z), writeln(Z), halt" equation4.pl
Error: out of environment
Aborted
```
Running with swipl gives
```
$ swipl -g "racines([[1,0],[-10,0],[35,0],[-50,0], [24,0]],Z), writeln(Z), halt" equation4.pl
[[4.000000007450581,0.0],[2.9999999925494194,0.0],[1.9999999925494194,0.0],[1.0000000074505806,0.0]]
```

[equation4.txt](https://github.com/infradig/trealla/files/5360325/equation4.txt)

**Comment by infradig** [comment]
I have fixed the rather obvious type check bug in  univ/2 and now get...

tpl -g "racines([[1,0],[-10,0],[35,0],[-50,0], [24,0]],Z), writeln(Z),
halt" equation4.pl
[]

Still more to look at then, don't know where the problem lies at this
point. So keep this issue open...

**Comment by infradig** [comment]
Ok, next problem is

$ swipl
                                  ±[●][devel]
?- div([-10,0],fois([-4,0],[1,0])) =.. [F,X,Y].
F =  (div),
X = [-10, 0],
Y = fois([-4, 0], [1, 0]).
?-

$ ./tpl
                                  ±[●][devel]
Trealla ProLog (c) Infradig 2020, v1.2.41-3-g6466
?- div([-10,0],fois([-4,0],[1,0])) =.. [F,X,Y].
false.
?-
So still issues with univ/2

**Comment by josd** [comment]
Thanks for the fix, it is amazing to see this ball rolling :-)
Not sure wether it is related with the [] result, but using -t I see
```
 [11] CALL div([-10,0],fois([-4,0],[1,0])) =.. [F,X,Y]
 [11] FAIL div([-10,0],fois([-4,0],[1,0])) =.. [F,X,Y]
```
so the following fails
```
$ tpl
Trealla ProLog (c) Infradig 2020, v1.2.41-9-g0570
?- div([-10,0],fois([-4,0],[1,0])) =.. [F,X,Y].
false.
```
whereas I think it should be
```
?- div([-10,0],fois([-4,0],[1,0])) =.. [F,X,Y].
F =  (div),
X = [-10, 0],
Y = fois([-4, 0], [1, 0]).
```

**Comment by infradig** [comment]
Yep fixed that, now onto the next....

**Comment by josd** [comment]
Unbelievable, after changing `div`( to `divid(` it works perfectly!
```
$ tpl -g "racines([[1,0],[-10,0],[35,0],[-50,0], [24,0]],Z), writeln(Z), halt" equation4.pl
[[4.000000007450581,0.0],[2.999999992549419,0.0],[1.999999992549419,0.0],[1.000000007450581,0.0]]
```
It really shows the inherent potential of your impressive work!!

**Comment by infradig** [comment]
Ok, ahead of me!

**Comment by infradig** [comment]
I am embarrassed about all the small things that have need fixing and
wasting people's time. But getting there.

**Comment by josd** [comment]
For sure getting there and I can only repeat that I'm deeply impressed and having a very good feeling while doing all this!

**Comment by infradig** [comment]
Ok, it now works with the original div. Thanks!
