### ISSUE TITLE
1r3 notation is not conforming syntax

### ISSUE THREAD

**Issue by triska** [infradig/trealla#6]
Using `1r3` to denote a rational numbers is not conforming to the ISO standard, because `r` could be defined as an operator, and in that case the term must be interpreted as `r(1,3)`.

Please consider removing this syntax.

**Comment by infradig** [comment]
Rational support is still experimental and I suppose I was too swayed by SWI-Prolog on that one. I do like the look of it though but will probably make it a flag to turn it on.

**Comment by infradig** [comment]
I have decidied to remove thr 1r3 notation.
