### ISSUE TITLE
maplist and library predicates

### ISSUE THREAD

**Issue by josd** [infradig/trealla#61]
The following
```
:- initialization(main).

main :-
    maplist(col([[1,2],[3,4]]), [1,2], X),
    writeln(X),
    halt.

col(Matrix, N, Column) :-
    maplist(nth1(N), Matrix, Column).
```
gives
`Error: uncaught exception... error(existence_error(procedure,nth1/3),nth1/3)`
instead of
`[[1,3],[2,4]]`

The following works fine
```
Trealla ProLog (c) Infradig 2020, v1.2.50
?- nth1(3, [1, 2, 3, 4], X).

X = 3.
```

**Comment by josd** [comment]
Currently it gives
```
Error: uncaught exception... error(type_error(number,.))
Trealla ProLog (c) Infradig 2020, v1.2.56
?-
```

**Comment by infradig** [comment]
Currently I can get this working but it breaks something else. Need to look
further...

**Comment by josd** [comment]
Now in the latest version it works fine and gives `[[1,3],[2,4]]`

This test was extracted from a more elaborate example in which unbound variables can occur, like in
```
:- initialization(main).

main :-
    maplist(col([[A,2],[3,A]]), [1,2], X),
    writeln(X),
    halt.

col(Matrix, N, Column) :-
    maplist(nth1(N), Matrix, Column).
```
and for that test the current version gives
`[[col([[_1,2],[3,_1]]),3],[2,col([[_1,2],[3,_1]])]]`
instead of
[[A,3],[2,A]]
Sorry, to be nitpicking esp. after all your hard work
Take your time and have a nice evening!

**Comment by infradig** [comment]
Probably an error printing within the context for the variable(s).

**Comment by infradig** [comment]
Working, though I need to get the REPL to dump var names.

**Comment by josd** [comment]
Thanks for the fix and it now nicely prints variables.

We are almost there I guess, but the following
```
:- initialization(main).

main :-
    maplist(length, M, [2,2]),
    writeln(M),
    maplist(col(M), [1,2], X),
    writeln(X),
    halt.

col(Matrix, N, Column) :-
    maplist(nth1(N), Matrix, Column).
```
gives
```
[[_14,_15],[_27,_28]]
[[_14,_14],[_15,_15]]
```
instead of
```
[[_14,_15],[_27,_28]]
[[_14,_27],[_15,_28]]
```
It looks like `maplist(col(M), [1,2], X)` changes M from `[[_14,_15],[_27,_28]]` to `[[_14,_15],[_14,_15]]`

**Comment by josd** [comment]
Perfect and thanks for all your efforts!
