### ISSUE TITLE
ldap library?

### ISSUE THREAD

**Issue by matteoredaelli** [infradig/trealla#64]
Will a ldap library be supported / included?

A sample lib is at

  https://github.com/EricssonResearch/ldap4pl

Regards
Matteo

**Comment by infradig** [comment]
It's not something i'm keen to do, personally (I used OpenDAP many years ago and didn't like it). But a foreign call service is definitely on the to-do list. It might then be relatively easy to then use the Ericsson Prolog code (it's Apache licensed).
