### ISSUE TITLE
setof/2 to collect a set of variables

### ISSUE THREAD

**Issue by josd** [infradig/trealla#65]
Using setof/2 to collect a set of variables we currently get
```
?- setof(I, member(I, [A,B,B,A]), Set).

Set = [I].

true.
```
whereas I think it should be
```
?- setof(I, member(I, [A,B,B,A]), Set).
Set = [A, B].
```

**Comment by infradig** [comment]
I discovered with #61 that meta-programming with variables has not been
handled well and was expecting more problems, so not that surprised with
this. Using bagof/3 you get a similarly valiant but incorrect result as
well.

**Comment by infradig** [comment]
Ok, this can be reduced to:

?- member(I, [A,B,B,A]), writeln(I), fail.
I
I
I
I

**Comment by josd** [comment]
swipl would give
```
?- member(I, [A,B,B,A]), writeln(I), fail.
_8004
_8010
_8010
_8004
false.
```

**Comment by infradig** [comment]
Yes. tpl is not reporting the binding correctly.

**Comment by infradig** [comment]
Now getting:

Trealla ProLog (c) Infradig 2020, v1.2.60-21-g1180-dirty
?- member(I, [A,B,B,A]), writeln(I), fail.
_1
_2
_2
_1
false.

Which doesn't help the origin issue.

**Comment by josd** [comment]
Now the original case works fine :-)

There is still an issue when the variables are created "outside" i.e.
```
:- initialization(main).

main :-
    prepare(List),
    writeln(List),
    setof(I, member(I, List), Set),
    writeln(Set),
    halt.

prepare(List) :-
    append([A,B],[B,A], List).
```
gives
```
[_5,_6,_6,_5]
[_2]

```
instead of
```
[_5,_6,_6,_5]
[_5,_6]
```

**Comment by infradig** [comment]
Yeah, was expecting this. I need to add a copy_term into bagof/setof.

**Comment by infradig** [comment]
This is now fixed, except it breaks tests/tests/test028.pl so holding off
pushing anything.

**Comment by josd** [comment]
That's what I really admire, such a nice and strong regression test driven approach!!

**Comment by josd** [comment]
Excellent! Thanks!
