### ISSUE TITLE
issue with clause/2 in explanation-based learning example

### ISSUE THREAD

**Issue by josd** [infradig/trealla#74]
The following program where line 74 is added to see what happens
```
% Example from https://www.cs.unm.edu/~luger/ai-final2/CH7_Machine%20Learning%20Algorithms%20in%20Prolog.pdf

% Explanation-based learning uses an explicitly represented domain theory
% to construct an explanation of a training example, usually a proof that
% the example logically follows from the theory. By generalizing from the
% explanation of the instance, rather than from the instance itself,
% explanation-based learning filters noise, selects relevant aspects of
% experience, and organizes training data into a coherent structure.

:- initialization(main).

main :-
	ebl(cup(obj1), cup(_), Rule),
	writeln(Rule),
	halt.

% domain theory
cup(X) :-
	liftable(X),
	holds_liquid(X).

holds_liquid(Z) :-
	part(Z, W),
	concave(W),
	points_up(W).

liftable(Y) :-
	light(Y),
	part(Y, handle).

light(A):-
	small(A).
light(A):-
	made_of(A, feathers).

% training example
cup(obj1).
small(obj1).

part(obj1, bottom).
part(obj1, bowl).
part(obj1, handle).

owns(bob, obj1).

points_up(bowl).

concave(bowl).

color(obj1, red).

made_of(obj2, feathers).

% operational criteria
operational(small(_)).
operational(part(_, _)).
operational(owns(_, _)).
operational(points_up(_)).
operational(concave(_)).

% explanation-based learning
ebl(Goal, Gen_goal, (Gen_goal :- Premise)) :-
	ebl(Goal, Gen_goal, _, Gen_proof),
	extract_support(Gen_proof, Premise).

ebl(A, GenA, A, GenA) :-
	clause(A, true).
ebl((A, B), (GenA, GenB), (AProof, BProof), (GenAProof, GenBProof)) :-
	!,
	ebl(A, GenA, AProof, GenAProof),
	ebl(B, GenB, BProof, GenBProof).
ebl(A, GenA, (A :- Proof), (GenA :- GenProof)) :-
	clause(GenA, GenB),
	writeln(clause(GenA, GenB)),
	copy_term(GenA-GenB, A-B),
	B \= true,
	ebl(B, GenB, Proof, GenProof).

extract_support(Proof, Proof) :-
	operational(Proof).
extract_support((A :- _), A) :-
	operational(A).
extract_support((AProof, BProof), (A, B)) :-
	extract_support(AProof, A),
	extract_support(BProof, B).
extract_support((_ :- Proof), B) :-
	extract_support(Proof, B).
```
gives
```
clause(cup(_1),liftable(cup(obj1)),holds_liquid(cup(obj1)))
clause(liftable(cup(obj1)),light(liftable(cup(obj1))),part(liftable(cup(obj1)),handle))
clause(light(liftable(cup(obj1))),small(light(liftable(cup(obj1)))))
clause(light(liftable(cup(obj1))),made_of(light(liftable(cup(obj1))),feathers))
clause(liftable(cup(obj1)),light(liftable(cup(obj1))),part(liftable(cup(obj1)),handle))
clause(light(liftable(cup(obj1))),small(light(liftable(cup(obj1)))))
clause(light(liftable(cup(obj1))),made_of(light(liftable(cup(obj1))),feathers))
```
whereas swipl gives
```
clause(cup(_6480),(liftable(_6480),holds_liquid(_6480)))
clause(liftable(_6480),(light(_6480),part(_6480,handle)))
clause(light(_6480),small(_6480))
clause(holds_liquid(_6480),(part(_6480,_6784),concave(_6784),points_up(_6784)))
clause(concave(bowl),true)
cup(_6480):-(small(_6480),part(_6480,handle)),part(_6480,_6784),concave(_6784),points_up(_6784)
```
The last line is the expected result.

So I see that sometimes clause/2 and sometimes clause/3 is written and that variables in the body are grounded.

**Comment by infradig** [comment]
Printing is missing some parentheses. I will look at it and further probs.

**Comment by infradig** [comment]
Yep, clause/2-3 needs work.

**Comment by infradig** [comment]
I have fixed some probs with clause/2,3 but #74 still not working. Will
continue looking at it when I can.

**Comment by infradig** [comment]
Gotta admit i'm stumped at this stage. It's close but, but no cigar as they
say. That said, neither Yap, GNU-Prolog nor ScryerProlog will run it
correctly either.

**Comment by josd** [comment]
Not sure if this helps, but the following innocent change
```
$ git diff
diff --git a/tests/issues/test074.pl b/tests/issues/test074.pl
index ad20440..b14b835 100644
--- a/tests/issues/test074.pl
+++ b/tests/issues/test074.pl
@@ -63,7 +63,7 @@ ebl(Goal, Gen_goal, (Gen_goal :- Premise)) :-
        extract_support(Gen_proof, Premise).

 ebl(A, GenA, A, GenA) :-
-       clause(A, true).
+       clause(A, B), B = true.
 ebl((A, B), (GenA, GenB), (AProof, BProof), (GenAProof, GenBProof)) :-
        !,
        ebl(A, GenA, AProof, GenAProof),
```
gives a Segmentation fault
```
$ tpl tests/issues/test074.pl
clause(cup(_1),(liftable(_1),holds_liquid(_1)))
clause(liftable(_1),(light(_1),part(_1,handle)))
clause(light(_1),small(_1))
clause(small(obj1),true)
clause(light(_1),made_of(_1,feathers))
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
Was a bug causing crash, which is now fixed, but doesn't help sadly. But
the result is different when it shouldn't be so I will look into that.

This example uses no longer legal Prolog (clause/2 has been changed).
SWI-Prolog accepts it so i'm happy to keep pursuing it, at least to keep it
alive as an issue.

**Comment by infradig** [comment]
Ok, this highlighted a problem which has been fixed.

  clause(A,true)

was giving a wrong result, whereas

  clause(A,B), B=true

was correct. The result now is different than the original one. Still
incorrect sadly.

**Comment by infradig** [comment]
Thanks, that was the spark needed to find the cause!

**Comment by infradig** [comment]
Oops. Premature close.

**Comment by infradig** [comment]
Now this is fixed it leaves a quandry. Only Trealla and SWI-Prolog can run this because it depends on non-ISO standard behaviour. Yap, GNU-Prolog & Scryer all refuse to do unacceptable things here with clause/2. But there is surely a lot of old code like this that depends on it?

**Comment by josd** [comment]
That's really nice, thanks a lot!

We use clause/2 in a few places, like 5 times in https://github.com/josd/eye/blob/master/eye.pl
but we also want to follow the ISO standard, and reading the attaches pages I was not aware of any non-ISO standard behaviour in tests/issues/test074.pl
Could you pinpoint and/or propose a correction for tests/issues/test074.pl to be ISO-Prolog standard compliant?

![20201029_143000](https://user-images.githubusercontent.com/193444/97581447-de773100-19f4-11eb-88cf-651e114a0f5d.jpg)
![20201029_142853](https://user-images.githubusercontent.com/193444/97581444-ddde9a80-19f4-11eb-941a-410712bf2b51.jpg)

**Comment by triska** [comment]
The answer is in:

<pre>
<b>7.5.3 Private and public procedures</b>

...

Each built-in predicate and control construct shall be private, 
<b>and a static user-defined procedure shall be private by default.</b>

A clause of a public procedure can be inspected, a clause of 
a private procedure cannot be inspected.
</pre>

Thus, to make it fully conforming, declare the predicates you want to inspect as *dynamic*, using the `dynamic/1` directive&nbsp;(7.4.2.1).

**Comment by josd** [comment]
Thanks @triska and I was unaware as I am using the book "Prolog : the standard ; reference manual / Pierre Deransat" from 1996 and chapter 7 ends with 7.4.3 .
The update is made in the pull request https://github.com/infradig/trealla/pull/78

**Comment by josd** [comment]
Nice and thank you very much @infradig and @triska

**Comment by triska** [comment]
You are very welcome!

One small comment: I think the check would be better written as `A \= (_,_)`. This is shorter than using `functor/3`, and has the additional advantage that it is more specific: For instance, it would be possible to have a predicate `(',')/3`, and in that case we want to apply `clause/2`.

However, it would be even more preferable to limit the use of `clause/2` to just one of the clauses, and reduce the other case to only handling `true`, if that is possible.

**Comment by josd** [comment]
Yes indeed and it is now simplified https://github.com/infradig/trealla/pull/80
Thanks for your valuable help!
Also thanks for your great https://github.com/triska/the-power-of-prolog
