### ISSUE TITLE
RFC: cache friendly memory pool

### ISSUE THREAD

**Issue by cehteh** [infradig/trealla#77]
Some years ago i wrote a cache friendly memory pool implementation. Even pretty unoptimized (alloc/free being slower than libc's malloc/free) using it for list nodes and other things that heavily rely on dereferencing and walking pointers the benefits from cache local allocation is substantial. Some benchmarks showed that real use cases programs run 20-40% faster on modern CPU architectures.

The idea is that one has  `alloc_near(..., void* hint)` like API's that try to allocate an element close to the 'hint'.
 
trealla looks like a good candidate to benefit from this. I am curious about this and  i'll start to hack on integrating the mpool code and see.

I created a branch where i work on this:
 https://github.com/cehteh/trealla/tree/mpool

Currently nothing is integrated and it needs some modifications / extensions to become usable for trealla.

The code is currently under GPLv2, when this experiment becomes a success i'll relicense it under MIT to be mergeable with the mainline.

**Comment by infradig** [comment]
Your welcome to experiment. Not a lot of dynamic structures like that. A rule is stored as a simple array of cells. But a predicate is an allocated list of rules so could probably benefit, especially with dynamics. The skiplist code currently used for indexing might do as well, that was a case of works good enough for now so use it.
