### ISSUE TITLE
Please consider interpreting double-quoted strings as lists of characters

### ISSUE THREAD

**Issue by triska** [infradig/trealla#8]
For instance, currently, we get:

<pre>
?- Ls = "abc".

<b>Ls = [97,98,99]</b>

true.
</pre>

A much more readable answer would be:

<pre>
?- Ls = "abc".

<b>Ls = [a,b,c]</b>

true.
</pre>

This is conforming to the standard, on the understanding that the *implementation defined* Prolog flag `double_quotes` is set to **`chars`**. The newest Prolog systems, Scryer&nbsp;Prolog and Tau&nbsp;Prolog, are doing this too, as did the original version of Prolog, Marseille&nbsp;Prolog. Chars are an ideal representation of strings, and can also be implemented very compactly and efficiently, using packed UTF-8 encoding internally, and at the same time interpreting the internal sequence of bytes as a list of characters.

Another goal of this feature is to eventually allow extremely fast parsing of large files, using `mmap (2)` to map file contents from disk to memory, and to apply a DCG directly to the mapped contents, which are available in memory as a sequence of bytes, and internally interpreted as a sequence of characters.

**Comment by infradig** [comment]
Fine by me.
