### ISSUE TITLE
absolute_file_name/2 predicate or equivalent to expand a relative file path into an absolute file path?

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#85]
I didn't find in the current version an `absolute_file_name/2` predicate or equivalent to expand a relative file path into an absolute file path. Planned? Did I missed an alternative?

**Comment by infradig** [comment]
Definitely onto it.

**Comment by pmoura** [comment]
It would be useful if the `absolute_file_name/2-3` predicates could expand paths that contain (or at least that start with) environment variables. In a POSIX system, a simple (albeit limited) solution would be check if the first character in the first argument is a `$`. I'm trying to locate C code that could do the expansion.

**Comment by infradig** [comment]
So this basically?

$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.2.1)
?- absolute_file_name('$HOME/.tpl_history',F,[expand(true)]).
F = '/home/andrew/.tpl_history'.

**Comment by pmoura** [comment]
Yes, that's a good example. Thanks for looking into this.

**Comment by triska** [comment]
Please note that '$' may occur in the actual path. For example, what do I do if a directory or file is actually called `'$HOME'`, and I want to determine its absolute path?

**Comment by infradig** [comment]
Use expand(false)?

**Comment by triska** [comment]
OK, thank you!

**Comment by infradig** [comment]
I get this...

$ echo foo >'$XYZ'
ls -l '$XYZ'
-rw-r--r-- 1 andrew andrew 4 Nov  4 16:56 '$XYZ'
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.91-7-g14bb
?- absolute_file_name('$XYZ',P).
 P = "/home/andrew/trealla/$XYZ".

**Comment by pmoura** [comment]
Thanks for the quick resolution. This predicate was the missing bit in the Logtalk adapter file that I wrote for Trealla Prolog (https://github.com/LogtalkDotOrg/logtalk3/blob/master/adapters/unsupported/trealla.pl). I'm now getting a strange compilation failure with an `initialization/1` directive in the `https://github.com/LogtalkDotOrg/logtalk3/blob/master/paths/paths.pl` file. But I will create a separate issue for it.
