### ISSUE TITLE
initialization/1 directive error

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#87]
I get a misleading file existence error when trying to load the following files:

```text
$ tpl
Trealla ProLog (c) Infradig 2020, v1.2.92-1-g5862
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/adapters/unsupported/trealla.pl').
true.
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/paths/paths.pl').
Error: uncaught exception... error(existence_error(cannot_open_file,/Users/pmoura/Documents/Logtalk/logtalk3/paths/paths.pl),consult/1)
```

The source files are available at [https://github.com/LogtalkDotOrg/logtalk3](https://github.com/LogtalkDotOrg/logtalk3). Commenting out the `initialization/1` directive at the beginning of the file solves the error. Initially I assumed a bug with asserting clauses for a multifile predicate. But so far I have been unable to abstract the directive into a simpler one for this bug report. P.S. Note that the source files load without issues in 14 other Prolog systems; this is definitely a Trealla Prolog bug.

**Comment by infradig** [comment]
Trealla does not yet support complex initialization goals. I'll be looking
at it soon.

**Comment by infradig** [comment]
Actually it seems a reporting error using consult.

**Comment by pmoura** [comment]
If we modify that `initialization/1` directive to be:

```logtalk
:- initialization((
	(	'$lgt_environment_variable'('LOGTALK_STARTUP_DIRECTORY', _) ->
		LOGTALK_STARTUP_DIRECTORY = '$LOGTALK_STARTUP_DIRECTORY/'
	;	'$lgt_current_directory'(LOGTALK_STARTUP_DIRECTORY0),
		(	sub_atom(LOGTALK_STARTUP_DIRECTORY0, _, _, 0, '/') ->
			LOGTALK_STARTUP_DIRECTORY = LOGTALK_STARTUP_DIRECTORY0
		;	atom_concat(LOGTALK_STARTUP_DIRECTORY0, '/', LOGTALK_STARTUP_DIRECTORY)
		)
	),
	assertz(logtalk_library_path(startup, LOGTALK_STARTUP_DIRECTORY)),
	writeq('HERE'), nl
)).
```

we then get:

```text
$ tpl
Trealla ProLog (c) Infradig 2020, v1.2.92-1-g5862
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/adapters/unsupported/trealla.pl').
true.
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/paths/paths.pl').
'HERE'
Error: uncaught exception... error(existence_error(cannot_open_file,/Users/pmoura/Documents/Logtalk/logtalk3/paths/paths.pl),consult/1)
```

And, as I wrote above, commenting out the directive allows the file to be consulted without issues.

**Comment by pmoura** [comment]
Tested your fix. The file now loads without issues. Thanks.
