### ISSUE TITLE
Operator parsing bug

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#88]
Consider the following file, `bug.pl`:

```logtalk
:- op(600, xfy, ::).

a::b.

X::Y :-
	X = a,
	Y = b.
```

We get:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.96-9-g1ba1
?- [bug].
Error: unknown module: 
Error: '.', line nbr 3
true.
```

From the error message, it seems to be an operator parsing bug where the first `:` of the `::` operator is misinterpreted as the `:` operator.

**Comment by infradig** [comment]
Yes, good one. Would be important for Logtalk. Reminds me to check for the
space operator ' '.

**Comment by pmoura** [comment]
Nice progress. But there's still an operator parsing bug when the same atom is both a prefix and an infix operator. With a modified `bug.pl` file from above:

```logtalk
:- op(600, xfy, ::).
:- op(600,  fy, ::).

a::b.

X::Y :-
	X = a,
	Y = b.
```

we get:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.99-1-g0051
?- consult(bug).
Error: no fact or clause head
Error: '.', line nbr 8
true.
```

The correct implementation of operators is one of the most difficult tasks when writing a Prolog parser.

**Comment by infradig** [comment]
Odd, there's other operators (obviously) that are both.

**Comment by pmoura** [comment]
A possible difference here is that the infix operator is being used also in rule head where we also have the `(:-)/2` operator. The fact, which also uses the infix operator, is parsed without errors.

**Comment by infradig** [comment]
Nah, it's simply the second op directive overwriting the first due to bad
logic. Will fix when I can get back to my computer.

**Comment by pmoura** [comment]
First confirmed. Thanks for the quick fix.
