### ISSUE TITLE
For ephemeral data, please consider using strings more heavily

### ISSUE THREAD

**Issue by triska** [infradig/trealla#9]
Currently, the README contains several examples of `format/2` and `http_get/3` where an *atom* is used as the first argument.

Major drawbacks of using atoms are that every new atom requires modification and maintenance of the atom&nbsp;table, that they cannot be reasoned about with DCGs, and also that they do not allow partial instantiations and automated generalizations.

Especially for data that are only used very ephemerally (such as format-strings and URLs), please consider using double-quoted strings (lists of characters) instead. For instance:

<pre>
?- format(<b>"~w"</b>, [hello]).
</pre>

where the first argument is a list of characters. Such lists can be efficiently allocated and garbage-collected on the heap.

Ideally, also file names and directories are represented in this way, so that they all become amenable to built-in mechanisms such as DCGs and built-in predicates for reasoning about lists.

**Comment by infradig** [comment]
Sure.

**Comment by infradig** [comment]
Ok, I have pretty much allowed for chars and codes lists whenever atoms were previously expected. A few notatble exceptions but they have *atom* in their name so not surprising. I will look into them as well.

**Comment by triska** [comment]
Thank you a lot! One important point: I meant also to actively *yield* lists of characters.

For example, currently, I get:

<pre>
?- sha256."test", Ls).

<b>Ls = 'E3B98A4DA31A127D4BDE6E43033F66BA274CAB0EB7EB1C70EC41402BF6273DD8'</b>

true.
</pre>

In this case, `Ls` is an atom. However, a list of characters would be much more convenient here: Most importantly, DCGs and well-known predicates over lists (`append/3`, `last/2`, `reverse/2` etc.) only work with lists and cannot be used with atoms. Second, using an atom here is wasteful since it modifies the atom table for a constant that is short-lived, is not used for indexing etc. Therefore, it would be more convenient to yield:

<pre>
<b>Ls = "E3B98A4DA31A127D4BDE6E43033F66BA274CAB0EB7EB1C70EC41402BF6273DD8"</b>
</pre>

The same holds for `base64/2`, for obtaining the files of a directory etc.: In such cases, strings are a much more suitable representation for convenient reasoning.

**Comment by infradig** [comment]
Yes, I plan on doing that.

**Comment by infradig** [comment]
Markus, referring to a previous comment of yours, i'm thinking of implementing something like...

	view_as_bytes(+in,-list)
	view_as_codes(+in,-list)
	view_as_chars(+in,-list)

Creates a mapped view onto an atom, string or stream that appears as
a list, but without the overhead of creating an actual list...

	?- view_as_codes('123', L).
	L = "123"

	?- open("README.md",read,S), view_as_chars(stream(S), L).
	L = "Trealla ProLog\n==============\n,..."

Could then add something like...

        ?- open(mmap("README.md"),read,S), view_as_chars(stream(S), L).

or
        ?- mmap("README.md",read,S), view_as_chars(stream(S), L).

**Comment by triska** [comment]
This should all happen *internally* in the Prolog system. In other words, a list of characters should always *internally* be represented in packed UTF-8 encoding, as a sequence of bytes. While to Prolog code, it should appear as a normal list.

The trick should happen in the *unification algorithm*: It must be prepared to encounter a special type of pointer that points into a (C-level)`char` buffer, and the algorithm must be made aware of the fact that this is to be considered as a list of (Prolog) characters.

So, in other words, when I write for example `"README.md"`, I expect the system to *internally* allocate a buffer with 9&nbsp;bytes. While on the Prolog level, for example the following should succeed: `"README.md" = ['R','E'|_]`.

So, it should not be necessary to expose `view_as_chars/2` to users: Parsing from a file should become very efficient with a predicate like `phrase_from_file/2`, which *internally* reads chunks of bytes, that (on the Prolog level) appear as a list of characters.

Please not that as soon as lists of characters are efficiently implemented in this way, there is no need to view them as codes or bytes: Characters are the most convenient and most readable representation, and they can represent bytes too. So, ideally, lists of characters should be efficiently and conveniently supported, while support for "codes" should be limited only to what the ISO standard prescribes, since it is an inconvenient representation for reasoning about text, especially for languages where nobody knows the codes by heart, whereas characters are easily readable.

Regarding the `mmap`-example, this should be encapsulated in the predicate `phrase_from_file/2`: It mmaps the file to memory (using internal mechanisms), and then applies a given DCG nonterminal to the resulting list of characters, which are simply the file contents. This works as long as the file does not contain `0`-characters, which is the typical case.

I have uploaded a video that explains the internal representation that you can use for strings, and also partial strings, please have a look:

https://www.metalevel.at/prolog/videos/representing_strings

Is this sufficiently clearly explained? Please let me know any time if you have any questions or comments about this representation: Having this representation in a Prolog system, and especially in conjunction with `mmap`ed files, would be a groundbreaking development, and pave the way for very interesting new Prolog applications!

**Comment by infradig** [comment]
Ok, I think I get what you're saying here!

**Comment by infradig** [comment]
Ok, development of this is looking good...

> Trealla ProLog (c) Infradig 2020, v1.2.5-4-g6e6f-dirty
> ?- Ls="abc",Ls=[A,B,C].
> Ls = [a,b,c]
> A = a
> B = b
> C = c
> true.

This is with the new packed strings. Not generally working though. Should have it finished today.

**Comment by infradig** [comment]
There may be a few case to track down where a C function needs a C-string (such as a file or path name) passed to it that I may have missed. I'll check later. But seems to work efficiently and well.

**Comment by triska** [comment]
Wow, this is now brilliantly resolved, thank you a lot!

I noticed that a few atoms remain in the README examples, notably for URLs:

<pre>
L = ['www.google.com','www.bing.com','www.duckduckgo.com'],
</pre>

It would be better to use strings for them so that the atom table is not affected.

**Comment by infradig** [comment]
Note... In devel I haved added mmap(Ls) as an option to open/4. It's
untested as yet. So you will be able to:

  setup_call_cleanup(
   open(filename, read, Str, [mmap(Ls)]),
   foo_with_strings(Ls),
   close(Str) ).

That's the idea at least.

**Comment by triska** [comment]
Yes, I noticed that, this is awesome, and I am really looking forward to it!

For reasoning about strings in Prolog, DCGs are best suited, so this should simply become `phrase_from_file(foo_with_strings, Filename)`.

I have filed #13 as a potentially useful resource for adding DCGs to your system. This hides all the low-level detail involving opening and closing, and allows to only expose the single high-level predicate `phrase_from_file/2` that is available for programmers to use.

**Comment by infradig** [comment]
test91 :-
	setup_call_cleanup(
		open("README.md", read, Str, [mmap(Ls)]),
		writeln(Ls),
		close(Str)
	).

seems to be working now.

**Comment by infradig** [comment]
> Wow, this is now brilliantly resolved, thank you a lot!
> 
> I noticed that a few atoms remain in the README examples, notably for URLs:
> 
> L = ['www.google.com','www.bing.com','www.duckduckgo.com'],
> It would be better to use strings for them so that the atom table is not affected.

Yep, but I think there is a problem with maplist/calln I need to look at here...

**Comment by triska** [comment]
Using `phrase_from_file/2`, the example can be written as follows:

<pre>
list([]) --> [].
list([L|Ls]) --> [L], list(Ls).

test91 :- phrase_from_file(list(Ls), "README.md"), writeln(Ls).
</pre>

This has the advantage that more is tested at the same time, and that higher-level constructs are better advertised.
