### ISSUE TITLE
Performance table results for GNU Prolog

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#90]
In the [`README.md`](https://github.com/infradig/trealla/blob/master/README.md) file, there's a performance table that includes results for GNU Prolog. Those results are misleading and don't reflect GNU Prolog true performance. In the same page we find that those results were collected by using goals such as:

```bash
$ time gprolog --query-goal test5,halt --consult-file samples/sieve.pl
```

But GNU Prolog *interprets* consulted files. Actual compilation requires using GNU Prolog `gplc`. That will give much better results and make it more of an apples to apples comparison (as the other systems, well, at least SWI-Prolog and YAP, compile files on consult).

**Comment by infradig** [comment]
I will add a note to that effect. Also swipl has a -O (non-default) option
that gives even better results.

**Comment by pmoura** [comment]
You can use something like:

```bash
$ gplc -o sieve samples/sieve.pl
$ echo "test5,halt." | time ./sieve
...
        0.19 real         0.18 user         0.00 sys
```
