### ISSUE TITLE
Compiler error with fact with no arguments

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#91]
Consider the following `bug.pl` file:

```logtalk
foo :-
	bar,
	fail.

foo.

bar.


'$l_foo' :-
	'$l_bar',
	fail.

'$l_foo'.

'$l_bar'.
```

We get:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.100
?- consult(bug).
Error: no fact or clause head
Error: '.', line nbr 14
true.
```

Possibly the bug is related with the `'$l_foo'/0` predicate name. But other clauses preceding the one in the original file from where this example was derived are apparently compiled fine. The trigger seems to be the fact having no arguments.

**Comment by infradig** [comment]
Quoted facts with no args is the problem.

fred.               % ok
'fred'.              % not ok
'fred' :- true.    %ok

Will look into it.

**Comment by pmoura** [comment]
Fix confirmed. Thanks.
