### ISSUE TITLE
Error handling, robustness

### ISSUE THREAD

**Issue by cehteh** [infradig/trealla#92]
There are some places where the code does some calls that may fail but doesn't care for error checking. I would like to add some robustness there. What would be the preferred way to do so?

My suggestion would be to pass errors up as much as possible:

```
foo*
foo_create()
{
  foo* x = malloc(sizeof(foo));
  if (x)
  {
     // do stuff with x here -> initilalization
  }
  return x;
}
```

and eventually handle errors where doable, but for now or when in doubt just call abort() until proper handling code is in place. At least never continue on a undefined state.

```
int main()
{
  foo* thefoo = foo_create(); if (!thefoo) abort();
}
```

Notes:

- `malloc` is only used as example, other functions like `fopen` and so on may fail as well.
- This checks are very cheap since the argument tested is very likely already in a register.
- Eventually errors should be passed up as prolog exceptions, but for now i only look at the C side.

**Comment by cehteh** [comment]
I felt free to start working on this:

https://github.com/cehteh/trealla/tree/errorhandling

Mostly handled skiplists.c and parse.c yet.

Pretty incomplete, just for review, not a pull request yet.

GO/NO-GO?

**Comment by infradig** [comment]
Yes, sounds good.

I am very much iterative in my approach... sketch out some code that
basically works (sometimes crudely), then come back with a critical eye for
a major revamp.

**Comment by cehteh** [comment]
I pretty much like the iterative approach and see how trealla is coming along. Even when that comes down to trash a lot code and rewrite it better.

Adding this error handling was meant as iteration as well. Eventually it could be reworked, having any 'abort()' left in the code isn't the intention, but its better than crashing in undefined ways.

Eventually i would like if trealla can 'gracefully' recover from any error, even in constrained/embedded systems. If it can't do a job because if resource exhaustion it should fail soft and report it.

Note: i am started to integrate the memory pool i mentioned in #77 and noticed it would be a 'nice to have' if allocation failures are already handled.

**Comment by infradig** [comment]
I have thought of adding a generic allocator for ephemeral stuff, allocated
per query so that if normal cleanup (eg. on backtracking or exceptions)
fails to do it's job the end of query will free it. Leaking memory is bad.
And I haven't been diligent with valgrind lately. So if you thoughts on
addressing that concept it would great. Feel free to put forward something
concrete.

**Comment by cehteh** [comment]
I pretty like the current approach, it may need a few checks and insurances that every entity created in C (prolog. parser, module, query ....) should be complete closures and owner of the stuff within so that any 'destroy_*' will clean things reliably up.

Still I am not so deep in the implementation yet to have figured out how the exception and backtracking working en detail.

Eventually I'd like to add some assertions to check for memory correctness, keeping stats about alloc/frees in debug builds so that one can check for memory leaks without relying on the slow valgrind machinery. So far this seems not to be a big issue and trealla is on the right track...

**Comment by infradig** [comment]
I just ran the full tests under valgrind and no leaks or funny accesses. So
that's good.

Adding an abort handler would be a worthwhile thing to do, allowing
gracefull recovery.

**Comment by cehteh** [comment]
i am not even that far as adding an 'abort-handler', where easily doable i let errors fall through, do local cleanup and then return a sentinel value (thats NULL for pointers) up.

Canonical example:
https://github.com/cehteh/trealla/blob/errorhandling/parse.c#L800

adding 'abort()' where its undecided how to handle things yet. As i saied above eventually the aborts should be all removed and replaced with proper handling. But first things first, mark the problematic spots with abort's.

Thats not just memory but also other things where trealla acquires resources (file/socket handles etc).

**Comment by cehteh** [comment]
Is there any reason that bool / stdbool.h isn't used for boolean flags? (struct module etc.). If not i'd like to add/modify that in a few places.

**Comment by infradig** [comment]
Is it in C99? That's the backwards compatibility i'm aiming for. Does it
store as a bit? Module isn't a problem but others that might get allocated
many 10s even 100s of thousand or millions of times could be a problem. If
so go ahead.

**Comment by cehteh** [comment]
yes stdbool is C99, usually these are implemented as machine words which can only store true (1) or false (0).

C99 compatibility is nice i wouldn't aim for newer. My thinking was to to make the code more readable in the first place (when I see bool or enum i know the intention and valid values), and secondary (well C's weak point) more typesafe. One could use bools in bitfields as well to take only single bits.

**Comment by infradig** [comment]
you build without library pre-loading:

 make NOLDLIBS=1 debug

you get get some strange errors with 'make test'

Running tests/tests/test056.pl ...
parse.c:1726 parser_dcg_rewrite: q failed
./tests/run.sh: line 14: 92056 Aborted                 (core dumped) $cmd "$source" > $TMP
1,20d0
< [the,woman,shoots,the,woman]
< [the,woman,shoots,the,man]

I don't know why create_query would fail?

**Comment by cehteh** [comment]
On 2020-11-13 15:34, Andrew Davison wrote:

> you build without library pre-loading:
> 
>  make NOLDLIBS=1 debug
> 
> you get get some strange errors with 'make test'
> 
> Running tests/tests/test056.pl ...
> parse.c:1726 parser_dcg_rewrite: q failed

seems there is a errno = 0 missing before the calloc's (line 922).

actually I was already thinking about doing the failure check based on
errno is a bad idea. If there are any other recursvie calls that leave
a stale errno then it will fail.

so better around line 1006:

- if (errno) {
+ if (!q->framea || !q->slots || !q->choices || !q-trails) {
     	destroy_query (q);
	q = NULL;
  }

I can fix that as well, but dunno if i find time over the weekend.

Either way my plan is to squash any bugs in 'normal' builds first,
ideally the faultinject stuff must never ever report a segfault (and no
sigaborts either).

Later on, other build configurations should be fixed.

**Comment by infradig** [comment]
Thanks, now I know what it is i'll fix it. NOLDLIBS=1 is necessary for OSX
compilation.

**Comment by pmoura** [comment]
The fix discussed above for `parse.c` solved the crash I was observing in macOS.
