### ISSUE TITLE
Unexpected error: "Error: not a public method module/2"

### ISSUE THREAD

**Issue by pmoura** [infradig/trealla#94]
While trying to load the Logtalk core files, I'm getting a puzzling error:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.101-2-g16b5
?- consult('logtalk3/adapters/unsupported/trealla.pl').
true.
?- consult('logtalk3/paths/paths.pl').
true.
?- consult('logtalk3/core/core.pl').
Error: not a public method module/2
Error: not a public method module/2
Error: not a public method module/2
true.
```

But there are no calls to a `module/2` predicate in the code being loaded. Any idea of what may be causing this error?

**Comment by infradig** [comment]
I'm seeing this..

Trealla ProLog (c) Infradig 2020, v1.2.101-2-g16b5-dirty
?- consult('../logtalk3/adapters/unsupported/trealla.pl').
true.
?- consult('../logtalk3/paths/paths.pl').
true.
?- consult('../logtalk3/core/core.pl').
Error: no fact or clause head
Error: '.', line nbr 516

but i'll look into it tomorrow.

**Comment by pmoura** [comment]
Odd. With the latest git version, I still get the same error I reported above:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.101-8-ge4803
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/adapters/unsupported/trealla.pl').
true.
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/paths/paths.pl').
true.
?- consult('/Users/pmoura/Documents/Logtalk/logtalk3/core/core.pl').
Error: not a public method module/2
Error: not a public method module/2
Error: not a public method module/2
true.
```

The error you got seems to be one that I was getting before one of your recent fixes.

> but i'll look into it tomorrow.

Thanks. Much appreciated.

**Comment by pmoura** [comment]
I managed to reduce this issue to a likely related error. Consider the following `bug.pl` file:

```logtalk
'$l_foo' :-
	'$l_bar',
	'$l_baz'.

'$l_bar'.

'$l_baz'.
```

We get:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.102
?- consult(bug).
true.
?- '$l_foo'.
Error: uncaught exception... error(existence_error(procedure,$l_foo),$)
?- '$l_bar'.
true.
?- '$l_baz'.
true.
```

**Comment by infradig** [comment]
Unrelated, but a bug never the less.

**Comment by pmoura** [comment]
The "not a public method module/2"  error messages no longer occur on v1.2.104. Thanks for the fixes.
